import {beforeEach,afterEach,describe,it,expect} from 'vitest';
import {createDb} from '../src/db/connection.js';import {seed,token} from './helpers/coordinator-fixture.js';import {QueueRepository} from '../src/domain/queue-repository.js';import {CoordinatorAuthorityService} from '../src/domain/coordinator-authority-service.js';import {makePiNativeProver,type RuntimeAvailability} from '../src/domain/coordinator-runtime-availability.js';import {coordinatorRoutes} from '../src/routes/coordinator.js';import {Hono} from 'hono';import {makeCoordinatorContinuityPolicy} from '../src/domain/policies/coordinator-continuity.js';import {EventBus} from '../src/domain/event-bus.js';
const deferred=<T>()=>{let resolve!:(x:T)=>void;const promise=new Promise<T>(r=>resolve=r);return {promise,resolve};};
describe('operation-owned availability',()=>{
 let db:ReturnType<typeof createDb>,svc:CoordinatorAuthorityService,clock:number;
 beforeEach(async()=>{db=createDb();seed(db);clock=10000;svc=new CoordinatorAuthorityService(db,undefined,undefined,()=>clock);const repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>svc.generation(s)});await repo.create({qitemId:'baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'coordinate',nudge:false});svc.enable('operator-agent@kernel','operator-agent-g1',{rigId:'xv',batonId:'baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:10000,operationId:'enable'});db.prepare("UPDATE queue_items SET state='in-progress',claimed_at='fixture',claimed_by_generation_uuid='lead-g1' WHERE qitem_id='baton'").run();db.prepare("UPDATE coordinator_authority SET state='active',lease_until=1").run();});
 afterEach(()=>db.close());
 const evidence=(session:string,state:'present'|'absent'|'unknown'='present'):RuntimeAvailability=>({session,generation:session==='lead@xv'?'lead-g1':'peer-g1',state,observedAt:10000,fingerprint:'native'});
 const input=(id='recover')=>({token,expectedLeaseUntil:1,operationId:id,obligationsDigest:svc.reconciliationDigest('xv'),windowMs:10000});
 const recover=()=>svc.recoverExpiredActive('operator-agent@kernel','operator-agent-g1',input());
 it('real HTTP A present commits while B pending without erasing A',async()=>{const a=deferred<RuntimeAvailability|null>(),b=deferred<RuntimeAvailability|null>();let calls=0;svc.setRuntimeObserver(async s=>s==='lead@xv'?(++calls===1?a.promise:b.promise):evidence(s));const app=new Hono();app.use('*',async(c,next)=>{c.set('queueRepo' as never,{coordinatorAuthority:svc} as never);await next();});app.route('/api/coordinator',coordinatorRoutes({bearerToken:'test-only'}));const request=(id:string)=>app.request('/api/coordinator/active-expiry-recover',{method:'POST',headers:{Authorization:'Bearer test-only','Content-Type':'application/json','X-OpenRig-Session':'operator-agent@kernel','X-OpenRig-Occupant-Generation':'operator-agent-g1'},body:JSON.stringify(input(id))});const first=request('A');while(calls<1)await Promise.resolve();const second=request('B');while(calls<2)await Promise.resolve();a.resolve(evidence('lead@xv'));expect((await first).status).toBe(200);b.resolve(evidence('lead@xv'));expect((await second).status).toBe(409);});
 it('A missing cannot borrow completed B or a populated legacy cache',async()=>{svc.setRuntimeObserver(async s=>evidence(s));await svc.refreshRuntimeAvailability('xv');const a=deferred<RuntimeAvailability|null>(),b=deferred<RuntimeAvailability|null>();let calls=0;svc.setRuntimeObserver(async s=>s==='lead@xv'?(++calls===1?a.promise:b.promise):evidence(s));const first=svc.withFreshRuntimeAvailability('xv',async()=>{await svc.refreshRuntimeAvailability('xv');return recover();});const second=svc.withFreshRuntimeAvailability('xv',()=>svc.hasFreshUnavailableOwner('xv'));b.resolve(evidence('lead@xv'));await second;a.resolve(null);await expect(first).rejects.toThrow('Fresh generation-bound native presence');});
 it.each(['stale','future','absent','unknown','generation','session','fingerprint','missing'])('%s refuses',async kind=>{svc.setRuntimeObserver(async s=>{if(s!=='lead@xv')return evidence(s);if(kind==='missing')return null;const e=evidence(s);if(kind==='stale')e.observedAt=clock-1001;if(kind==='future')e.observedAt=clock+1;if(kind==='absent')e.state='absent';if(kind==='unknown')e.state='unknown';if(kind==='generation')e.generation='retired';if(kind==='session')e.session='peer@xv';if(kind==='fingerprint')e.fingerprint='';return e;});await expect(svc.withFreshRuntimeAvailability('xv',recover)).rejects.toThrow('Fresh generation-bound native presence');});
 it.each(['generation','roster'])('%s drift after probing refuses',async kind=>{svc.setRuntimeObserver(async s=>evidence(s));await expect(svc.withFreshRuntimeAvailability('xv',()=>{if(kind==='generation')db.prepare("UPDATE occupant_tenures SET generation_uuid='retired' WHERE node_id='peer@xv'").run();else db.prepare("UPDATE coordinator_authority SET coordinators='[]'").run();return recover();})).rejects.toThrow('Fresh generation-bound native presence');});
 it('production continuity policy retains its own age across yields despite a fresh cache',async()=>{
  svc.setRuntimeObserver(async session=>({...evidence(session,'absent'),observedAt:clock}));let first=true;
  const policy=makeCoordinatorContinuityPolicy(svc,async()=>{if(first){first=false;clock+=1001;await svc.refreshRuntimeAvailability('xv');}});
  const result=await policy.evaluate({registeredBySession:'operator-agent@kernel',target:{session:'operator-agent@kernel'},context:{rigId:'xv'},jobId:'job'} as never);
  expect(result).toMatchObject({action:'skip',reason:'no-authoritative-exclusion'});
 });
 it('absence is own-batch only and still expires across async phases',async()=>{svc.setRuntimeObserver(async s=>evidence(s,'absent'));await svc.withFreshRuntimeAvailability('xv',async()=>{expect(svc.hasFreshUnavailableOwner('xv')).toBe(true);await Promise.resolve();clock+=1001;expect(svc.hasFreshUnavailableOwner('xv')).toBe(false);});});
});
describe('Pi identity and honest quiescence',()=>{
 const row={nodeId:'n',runtime:'pi',tmux_pane:'%4',tmux_session:null,generation_uuid:'g',resume_token:'/state/pi/lead@xv/sessions/s.json'};const census='100 1 /bin/zsh -l\n101 100 node /d/adapters/pi-runner.js --session-name lead@xv --launch-id L --state-root /state/pi\n102 101 /opt/node /x/@earendil-works/pi-coding-agent/dist/bundle/cli.js --mode rpc';
 const observe=(change:string)=>{let samples=0;return makePiNativeProver({prepare:()=>({all:()=>[row]})} as never,async()=>'%4|100|0',{piStateRoot:'/state/pi',argvCensus:async()=>change==='lineage'&&samples>0?census.replace('102 101','102 100'):census,procArgs:async()=>new Map([[101,'g'],[102,change==='kernel-generation'&&samples>1?'other':'g']]),fs:{readFile:()=>{const second=++samples>1;return JSON.stringify({ready:true,launchId:change==='launch'&&second?'other':'L',sessionFile:change==='session'&&second?'other':row.resume_token,updatedAt:second?'2026-10-08T00:00:02Z':'2026-10-08T00:00:01Z',lastEntryId:'cursor',quiescence:{settled:true,launchId:'L',generation:change==='generation'&&second?'other':'g',sessionFile:row.resume_token,lastEntryId:change==='cursor'&&second?'other':'cursor',observedAt:'2026-01-01T00:00:00Z'}});}},now:()=>Date.parse('2026-10-08T00:00:05Z')});};
 it('sidecar time changes preserve identity and stale original quiescence timestamp',async()=>{const p=await observe('time')('lead@xv');expect(p?.state).toBe('present');expect(p?.fingerprint).not.toContain('sidecarUpdatedAt');expect(p?.quiescence).toEqual({settled:true,observedAt:'2026-01-01T00:00:00Z'});});
 it.each(['launch','session','lineage','kernel-generation'])('%s identity changes refuse',async c=>expect(await observe(c)('lead@xv')).toBeNull());
 it.each(['generation','cursor'])('%s quiescence binding remains unknown',async c=>expect((await observe(c)('lead@xv'))?.quiescence).toEqual({settled:null,observedAt:null}));
});
