import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createDb} from '../src/db/connection.js';import {EventBus} from '../src/domain/event-bus.js';import {QueueRepository} from '../src/domain/queue-repository.js';import {OutboxHandler} from '../src/domain/outbox-handler.js';
import {CoordinationRecoveryService,type CoordinationActivity} from '../src/domain/coordination-recovery-service.js';
import {CoordinatorAuthorityService,digest,legacyProposalDigest,type LegacyEnrollment} from '../src/domain/coordinator-authority-service.js';
import {HistoricalEffectDispositionService,historicalDigest,type HistoricalPlan,type HistoricalDisposition} from '../src/domain/historical-effect-disposition.js';
import {SeatDeliveryGuard,resolveGuardTarget} from '../src/domain/seat-delivery-guard.js';import {seed,token} from './helpers/coordinator-fixture.js';
let dir:string,db:ReturnType<typeof createDb>,repo:QueueRepository,outbox:OutboxHandler,history:HistoricalEffectDispositionService;
const actor='operator-agent@kernel',gen='operator-agent-g1';const svc=()=>repo.coordinatorAuthority;
beforeEach(async()=>{vi.useFakeTimers({toFake:['Date']});dir=mkdtempSync(join(tmpdir(),'held-adopt-'));db=createDb(join(dir,'db'));seed(db);db.prepare("INSERT INTO self_host_identity(singleton,host_id,minted_at,reconciled_at) VALUES (1,?,?,?)").run("local",new Date().toISOString(),new Date().toISOString());for(const n of ['lead@xv','peer@xv','builder@xv','reviewer@xv',actor])db.prepare('INSERT INTO bindings(id,node_id,tmux_session) VALUES (?,?,?)').run(n,n,n);repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>repo.coordinatorAuthority.generation(s)});outbox=new OutboxHandler(db);repo.attachOutbox(outbox);history=new HistoricalEffectDispositionService(db);
 await repo.create({qitemId:'baton',sourceSession:actor,destinationSession:'lead@xv',body:'coordinate',nudge:false,identityProvenance:'transport:v1'});repo.claim({qitemId:'baton',destinationSession:'lead@xv'});
 await repo.create({qitemId:'work',sourceSession:'lead@xv',destinationSession:'builder@xv',body:'valuable ongoing work',nudge:false,identityProvenance:'transport:v1'});repo.claim({qitemId:'work',destinationSession:'builder@xv'});
 outbox.record({outboxId:'wake-intent-old',senderSession:'lead@xv',destinationSession:'builder@xv',body:'UNKNOWN prior input',auditPointer:'work'});
 const p:HistoricalPlan={rigId:'xv',leadBatonId:'baton',leadGeneration:'lead-g1',operatorGeneration:gen,operationId:'hold',authorizationId:'hold-auth',expiresAt:Date.now()+600000,effects:history.inspect('xv',['wake-intent-old'])};
 await repo.create({qitemId:'hold-auth',sourceSession:'lead@xv',destinationSession:actor,body:JSON.stringify({kind:'outbox-historical-quarantine-authorization',requestDigest:historicalDigest({actor,generation:gen,input:p})}),nudge:false,identityProvenance:'transport:v1'});repo.claim({qitemId:'hold-auth',destinationSession:actor});history.quarantine(actor,gen,p);
});afterEach(()=>{vi.useRealTimers();db.close();rmSync(dir,{recursive:true,force:true});});
async function packet():Promise<LegacyEnrollment>{
 const inv=svc().legacyInventory('xv','authorization',true);const deadline=Date.now()+600000;
 await repo.create({qitemId:'recovery',sourceSession:'lead@xv',destinationSession:actor,body:JSON.stringify({kind:'coordinator-held-history-recovery.v1',rigId:'xv',operationId:'migrate',owner:actor,generation:gen,lead:'lead@xv',leadGeneration:'lead-g1',effects:inv.heldHistory?.map(h=>h.outboxId)??['wake-intent-old'],action:'reconcile-preserved-unknown-history',deadline,returnPath:{session:'lead@xv',queueId:'recovery'}}),expiresAt:new Date(deadline).toISOString(),nudge:false,identityProvenance:'transport:v1'});repo.claim({qitemId:'recovery',destinationSession:actor});
 const inventory=svc().legacyInventory('xv','authorization',true);
 return {rigId:'xv',batonId:'baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:60000,operationId:'migrate',authorizationId:'authorization',inventory,heldHistoryRecovery:{queueId:'recovery',rowHash:historicalDigest(db.prepare('SELECT * FROM queue_items WHERE qitem_id=?').get('recovery'))},obligations:inventory.rows.map(q=>q.queueId==='work'?{queueId:'work',kind:'work' as const,evidenceRef:'exact-current-work-contract',packageKey:'p1',resourceScope:'exclusive' as const,contract:{inputDigest:digest('inputs'),bodyHash:digest('valuable ongoing work'),destination:'builder@xv',resources:['source/a'],returnContract:{destination:'lead@xv',evidenceRequired:['tests']}}}:{queueId:q.queueId,kind:'coordination' as const,evidenceRef:'actual-control-return'})};
}
async function authorize(p:LegacyEnrollment){await repo.create({qitemId:'authorization',sourceSession:'lead@xv',destinationSession:actor,body:JSON.stringify({kind:'coordinator-legacy-enrollment',proposalDigest:legacyProposalDigest(p)}),identityProvenance:'transport:v1',nudge:false});repo.claim({qitemId:'authorization',destinationSession:actor});}
const migrate=(p:LegacyEnrollment)=>svc().migrateLegacy(actor,gen,p);
const original=()=>({effects:db.prepare('SELECT * FROM outbox_entries ORDER BY outbox_id').all(),work:repo.getById('work'),holds:db.prepare('SELECT * FROM outbox_historical_quarantines').all()});
it('explicit contained history imports actual claimed work and recovery, ACK and independent transport pickup without history replay',async()=>{
 const p=await packet();await authorize(p);const before=original();expect(migrate(p).state).toBe('reconciling');expect(original()).toEqual(before);expect(migrate(p).epoch).toBe(1);
 const debt=db.prepare('SELECT * FROM coordinator_held_history').get() as any;expect(debt.pre_custody_hash).not.toBe(debt.post_custody_hash);expect(JSON.parse(debt.receipt)).toMatchObject({deliveryConclusion:'unknown',originalMutations:0,recovery:{queueId:'recovery'}});
 svc().acknowledge('lead@xv',token,{obligationsDigest:svc().reconciliationDigest('xv'),operationId:'ack'});
 const contract={inputDigest:digest('independent'),destination:'reviewer@xv',bodyHash:digest('ready independent work'),resources:[],returnContract:{destination:'lead@xv',evidenceRequired:['review']}};svc().admit(actor,gen,'xv','ready',contract);
 const pickups:string[]=[];repo.attachTransport({send:async(_s,_b,opts)=>{for(const id of opts!.committedOutboxIds!){const e=outbox.getById(id)!;if(e.auditPointer){repo.claim({qitemId:e.auditPointer,destinationSession:e.destinationSession});pickups.push(e.auditPointer);}}return {ok:true,verified:true};}});
 const q=await repo.create({qitemId:'ready-work',sourceSession:'lead@xv',destinationSession:'reviewer@xv',body:'ready independent work',dispatch:{token,packageKey:'ready'},nudge:true});await repo.drainPendingWakeIntents();expect(pickups).toContain(q.qitemId);expect(repo.getById(q.qitemId)?.state).toBe('in-progress');expect(outbox.getById('wake-intent-old')?.deliveryState).toBe('pending');expect(outbox.isHistoricalQuarantined('wake-intent-old')).toBe(true);
});
it('default inventory and enable remain refusing; bare or changed quarantine provenance never qualifies containment',async()=>{
 expect(svc().legacyInventory('xv','authorization').uncertainEffects).toHaveLength(1);expect(()=>svc().enable(actor,gen,{rigId:'xv',batonId:'baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:60000,operationId:'enable'})).toThrow();
 for(const sql of ["DELETE FROM outbox_historical_operations","UPDATE outbox_historical_quarantines SET original_hash='forged'","UPDATE outbox_historical_operations SET receipt='null'"]){db.exec('SAVEPOINT trial');db.exec(sql);expect(svc().legacyInventory('xv','authorization',true).uncertainEffects).toHaveLength(1);db.exec('ROLLBACK TO trial');db.exec('RELEASE trial');}
});
it('mixed held plus uncontained effect refuses atomically',async()=>{outbox.record({outboxId:'uncontained',senderSession:'lead@xv',destinationSession:'builder@xv',body:'unknown uncontained'});const p=await packet();await authorize(p);const before=original();expect(()=>migrate(p)).toThrow('Uncertain delivery');expect(original()).toEqual(before);expect(svc().get('xv')).toBeUndefined();expect(db.prepare('SELECT count(*) n FROM coordinator_held_history').get()).toEqual({n:0});});
it('current source/hold/custody/generation/expiry/recovery claim drift refuses without partial adoption',async()=>{
 for(const kind of ['body','hold','claim','operator','expiry','recovery-claim','recovery-purpose']){
  const p=await packet();await authorize(p);db.exec('SAVEPOINT trial');
  if(kind==='body')db.prepare("UPDATE outbox_entries SET body='changed'").run();if(kind==='hold')db.prepare("UPDATE outbox_historical_quarantines SET state='disposed'").run();if(kind==='claim')db.prepare("UPDATE queue_items SET claimed_by_generation_uuid='old' WHERE qitem_id='work'").run();if(kind==='operator')db.prepare("UPDATE occupant_tenures SET generation_uuid='new' WHERE node_id=?").run(actor);if(kind==='expiry')db.prepare("UPDATE queue_items SET expires_at='2000-01-01T00:00:00Z' WHERE qitem_id='recovery'").run();if(kind==='recovery-claim')db.prepare("UPDATE queue_items SET state='pending' WHERE qitem_id='recovery'").run();if(kind==='recovery-purpose')db.prepare("UPDATE queue_items SET body='{}' WHERE qitem_id='recovery'").run();
  const before=original();expect(()=>migrate(p)).toThrow();expect(original()).toEqual(before);expect(svc().get('xv')).toBeUndefined();expect(db.prepare('SELECT count(*) n FROM coordinator_held_history').get()).toEqual({n:0});db.exec('ROLLBACK TO trial');db.exec('RELEASE trial');db.prepare("DELETE FROM queue_transitions WHERE qitem_id IN ('authorization','recovery')").run();db.prepare("DELETE FROM queue_items WHERE qitem_id IN ('authorization','recovery')").run();
 }
});
it('custody mapping is exact and resource overlap rolls back adoption and preserves original claims',async()=>{
 await repo.create({qitemId:'other-work',sourceSession:'lead@xv',destinationSession:'reviewer@xv',body:'review',nudge:false});const p=await packet();p.obligations=p.obligations.map(o=>o.queueId==='other-work'?{queueId:o.queueId,kind:'work',evidenceRef:'review',packageKey:'p2',resourceScope:'exclusive',contract:{inputDigest:digest('i2'),bodyHash:digest('review'),destination:'reviewer@xv',resources:['source/a'],returnContract:{destination:'lead@xv',evidenceRequired:['review']}}}:o);await authorize(p);const before=original();expect(()=>migrate(p)).toThrow('overlaps');expect(original()).toEqual(before);for(const t of ['coordinator_held_history','coordinator_authority','coordinator_resources','coordinator_assignments'])expect(db.prepare(`SELECT count(*) n FROM ${t}`).get()).toEqual({n:0});
});
it('restart retains non-executable immutable held debt and supports existing guarded retirement order',async()=>{
 const p=await packet();await authorize(p);migrate(p);const guard=new SeatDeliveryGuard(db,n=>resolveGuardTarget(db,n));const freshSvc=new CoordinatorAuthorityService(db),freshOutbox=new OutboxHandler(db);expect(freshSvc.get('xv')?.state).toBe('reconciling');expect(freshOutbox.listPending('wake-intent-')).toEqual([]);expect(freshOutbox.claimForDelivery('wake-intent-old')).toBe(false);
 for(const sql of ["DELETE FROM outbox_historical_quarantines","UPDATE outbox_historical_quarantines SET state='disposed'","UPDATE outbox_entries SET delivery_state='sending'","UPDATE outbox_entries SET body='new'","DELETE FROM outbox_entries","DELETE FROM coordinator_held_history","UPDATE outbox_historical_operations SET receipt='{}'","DELETE FROM outbox_historical_operations"]){expect(()=>db.exec(sql)).toThrow(/protected|immutable/);}
 // Existing supported service retirement order must remain possible, not a trigger-only raw state rewrite.
 const ref=history.inspect('xv',['wake-intent-old'])[0]!;const d:HistoricalDisposition={rigId:'xv',leadBatonId:'baton',leadGeneration:'lead-g1',operatorGeneration:gen,operationId:'withdraw',authorizationId:'dispose-auth',expiresAt:Date.now()+600000,quarantineOperationId:'hold',effect:ref,action:'withdraw-obsolete-wake',reason:'Current work retained; withdraw only exact old intention',evidenceRef:'current-custodian-decision'};
 const body=JSON.stringify({kind:'outbox-historical-disposition-authorization',requestDigest:historicalDigest({actor,generation:gen,input:d})});
 svc().acknowledge('lead@xv',token,{obligationsDigest:svc().reconciliationDigest('xv'),operationId:'ack'});
 await repo.create({qitemId:'dispose-auth',sourceSession:'lead@xv',destinationSession:actor,body,nudge:false,identityProvenance:'transport:v1'});repo.claim({qitemId:'dispose-auth',destinationSession:actor});
 expect(d.effect.custodyHash).not.toBe(p.inventory.heldHistory![0]!.custodyHash);expect(await history.dispose(actor,gen,d,guard)).toMatchObject({deliveryConclusion:'unknown',queueMutations:0});expect(outbox.getById('wake-intent-old')?.deliveryState).toBe('retired');expect(db.prepare('SELECT count(*) n FROM coordinator_held_history').get()).toEqual({n:1});
});
it('other rig continues while only exactly adopted held debt permits genuine unavailable-owner transfer',async()=>{
 const p=await packet();await authorize(p);migrate(p);const q=await repo.create({qitemId:'other-ready',sourceSession:'worker@other',destinationSession:actor,body:'independent result',nudge:false});expect(q.qitemId).toBe('other-ready');expect(svc().legacyInventory('other','none',true).heldHistory).toEqual([]);
 svc().acknowledge('lead@xv',token,{obligationsDigest:svc().reconciliationDigest('xv'),operationId:'ack'});
 let clock=Date.now();
 const sample=(session:string):CoordinationActivity=>({generation:svc().generation(session)!,identityVerified:true,state:{seatNodeId:session,activity:'idle-at-prompt',needsInput:{count:0,reason:null},decidedBy:'window-sampling',seq:1,changedAt:new Date(clock).toISOString(),rungs:[],lastSwap:null},witness:{seatNodeId:session,sessionName:session,rung:'window-sampling',sourceId:'tmux',seq:1,observedAt:new Date(clock).toISOString(),activity:'idle-at-prompt'}});
 const recovery=new CoordinationRecoveryService(repo,s=>sample(s),()=>clock);svc().coordinationRecovery=recovery;
 const tasks=['reviewer@xv','architect@xv'].map((owner,i)=>({key:'task'+i,packageKey:'task'+i,owner,action:'Bounded review/recovery',body:'task'+i,deadline:clock+60000,predecessors:[],...(i?{recoveryFor:'task0'}:{}),admission:{generation:svc().generation(owner)!,configurationDigest:recovery.configurationDigest(owner)!,qualificationRef:'independent-current',capacityRef:'current',effortRef:'current',validUntil:clock+60000}}));
 for(const t of tasks)svc().admit(actor,gen,'xv',t.packageKey,{inputDigest:digest(t.key),destination:t.owner,bodyHash:digest(t.body),resources:[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});
 recovery.configure(actor,gen,{rigId:'xv',revision:'current',operatorGeneration:gen,stallMs:10000,allowIdlePeerTransfer:false,allowUnavailablePeerTransfer:true,tasks});
 db.prepare("INSERT INTO watchdog_jobs(job_id,target_session,policy,interval_seconds,spec_yaml,state,registered_by_session,registered_at,registered_by_generation_uuid) VALUES ('j',?,'coordinator-continuity',1,'context: {}','active',?,?,?)").run(actor,actor,new Date(clock).toISOString(),gen);
 svc().renew('lead@xv',token,1000,'short');clock+=1001;vi.setSystemTime(clock);svc().setRuntimeObserver(async session=>({session,generation:svc().generation(session)!,state:session==='lead@xv'?'absent':'present',observedAt:clock,fingerprint:'actual-fixture-native-census'}));await svc().refreshRuntimeAvailability('xv');
 const input={rigId:'xv',expectedEpoch:1,expectedOwner:'lead@xv',expectedOwnerGeneration:'lead-g1',planRevision:'current',recipient:'peer@xv',recipientGeneration:'peer-g1',leaseMs:60000};
 outbox.record({outboxId:'fresh-uncertain',senderSession:'lead@xv',destinationSession:'builder@xv',body:'not adopted'});expect(()=>svc().transferObservedUnavailable('j',input)).toThrow('Uncertain effects');expect(svc().get('xv')?.epoch).toBe(1);
 // Supported exact unrelated effect state resolution is fixture setup only; adopted held original stays unchanged.
 outbox.markFailed('fresh-uncertain');
 // Terminal or expired accountability is a takeover hold, not global dispatch suspension.
 for(const sql of ["UPDATE queue_items SET state='done' WHERE qitem_id='recovery'","UPDATE queue_items SET expires_at='2000-01-01T00:00:00Z' WHERE qitem_id='recovery'"]){db.exec('SAVEPOINT accountability');db.exec(sql);expect(()=>svc().transferObservedUnavailable('j',input)).toThrow('held-history-recovery-bind');expect(svc().get('xv')?.epoch).toBe(1);db.exec('ROLLBACK TO accountability');db.exec('RELEASE accountability');}
 db.prepare("UPDATE queue_items SET state='done' WHERE qitem_id='recovery'").run();
 const refs=svc().legacyInventory('xv','new-auth',true).heldHistory!;const deadline=clock+600000;
 const body=JSON.stringify({kind:'coordinator-held-history-recovery.v1',rigId:'xv',operationId:'rebind',owner:actor,generation:gen,lead:'lead@xv',leadGeneration:'lead-g1',effects:refs.map(h=>h.outboxId),action:'reconcile-preserved-unknown-history',deadline,returnPath:{session:'lead@xv',queueId:'recovery-new'}});
 await repo.create({qitemId:'recovery-new',sourceSession:'lead@xv',destinationSession:actor,body,expiresAt:new Date(deadline).toISOString(),nudge:false,identityProvenance:'transport:v1'});
 const bind=()=>({rigId:'xv',operationId:'rebind',effects:refs,recovery:{queueId:'recovery-new',rowHash:historicalDigest(db.prepare('SELECT * FROM queue_items WHERE qitem_id=?').get('recovery-new'))}});
 expect(()=>svc().bindHeldHistoryRecovery(actor,gen,bind())).toThrow('actual Operator claimed');repo.claim({qitemId:'recovery-new',destinationSession:actor});const bound=bind();expect(svc().bindHeldHistoryRecovery(actor,gen,bound)).toMatchObject({originalMutations:0});expect(svc().bindHeldHistoryRecovery(actor,gen,bound)).toMatchObject({originalMutations:0});
 db.exec('SAVEPOINT expiredReplay');db.prepare("UPDATE queue_items SET state='done' WHERE qitem_id='recovery-new'").run();expect(()=>svc().bindHeldHistoryRecovery(actor,gen,bound)).toThrow();db.exec('ROLLBACK TO expiredReplay');db.exec('RELEASE expiredReplay');
 expect(db.prepare("SELECT count(*) n FROM coordinator_operations WHERE kind='held-history-recovery-binding'").get()).toEqual({n:1});
 const before=original();expect(svc().transferObservedUnavailable('j',input)).toMatchObject({epoch:2,state:'reconciling',owner_session:'peer@xv'});expect(repo.getById('work')).toEqual(before.work);expect(outbox.getById('wake-intent-old')?.deliveryState).toBe('pending');expect(repo.getById('baton')?.state).toBe('pending');repo.claim({qitemId:'baton',destinationSession:'peer@xv',identityProvenance:'transport:v1'});svc().acknowledge('peer@xv',{...token,epoch:2,generation:'peer-g1'},{obligationsDigest:svc().reconciliationDigest('xv'),operationId:'peer-ack'});expect(svc().get('xv')?.state).toBe('active');
});

it('expired history recovery is renewed only from genuine unavailable-owner supervise provenance and actual Operator pickup',async()=>{
 const p=await packet();await authorize(p);migrate(p);const q=await repo.create({qitemId:'other-ready',sourceSession:'worker@other',destinationSession:actor,body:'independent result',nudge:false});expect(q.qitemId).toBe('other-ready');expect(svc().legacyInventory('other','none',true).heldHistory).toEqual([]);
 svc().acknowledge('lead@xv',token,{obligationsDigest:svc().reconciliationDigest('xv'),operationId:'ack'});
 let clock=Date.now();
 const sample=(session:string):CoordinationActivity=>({generation:svc().generation(session)!,identityVerified:true,state:{seatNodeId:session,activity:'idle-at-prompt',needsInput:{count:0,reason:null},decidedBy:'window-sampling',seq:1,changedAt:new Date(clock).toISOString(),rungs:[],lastSwap:null},witness:{seatNodeId:session,sessionName:session,rung:'window-sampling',sourceId:'tmux',seq:1,observedAt:new Date(clock).toISOString(),activity:'idle-at-prompt'}});
 const recovery=new CoordinationRecoveryService(repo,s=>sample(s),()=>clock);svc().coordinationRecovery=recovery;
 const tasks=['reviewer@xv','architect@xv'].map((owner,i)=>({key:'task'+i,packageKey:'task'+i,owner,action:'Bounded review/recovery',body:'task'+i,deadline:clock+60000,predecessors:[],...(i?{recoveryFor:'task0'}:{}),admission:{generation:svc().generation(owner)!,configurationDigest:recovery.configurationDigest(owner)!,qualificationRef:'independent-current',capacityRef:'current',effortRef:'current',validUntil:clock+60000}}));
 for(const t of tasks)svc().admit(actor,gen,'xv',t.packageKey,{inputDigest:digest(t.key),destination:t.owner,bodyHash:digest(t.body),resources:[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});
 recovery.configure(actor,gen,{rigId:'xv',revision:'current',operatorGeneration:gen,stallMs:10000,allowIdlePeerTransfer:false,allowUnavailablePeerTransfer:true,tasks});
 db.prepare("INSERT INTO watchdog_jobs(job_id,target_session,policy,interval_seconds,spec_yaml,state,registered_by_session,registered_at,registered_by_generation_uuid) VALUES ('j',?,'coordinator-continuity',1,'context: {}','active',?,?,?)").run(actor,actor,new Date(clock).toISOString(),gen);
 svc().renew('lead@xv',token,1000,'short');clock+=1001;vi.setSystemTime(clock);svc().setRuntimeObserver(async session=>({session,generation:svc().generation(session)!,state:session==='lead@xv'?'absent':'present',observedAt:clock,fingerprint:'actual-fixture-native-census'}));await svc().refreshRuntimeAvailability('xv');
 const input={rigId:'xv',expectedEpoch:1,expectedOwner:'lead@xv',expectedOwnerGeneration:'lead-g1',planRevision:'current',recipient:'peer@xv',recipientGeneration:'peer-g1',leaseMs:60000};
 db.prepare("UPDATE queue_items SET expires_at='2000-01-01T00:00:00Z' WHERE qitem_id='recovery'").run();
 const originalBefore=original();const held=recovery.supervise('xv','j')!;expect(held[0]).toMatchObject({state:'held',reason:'coordinator_held_history_recovery_required'});
 const id=held[0]!.queueId!;const task=repo.getById(id)!;expect(task.state).toBe('pending');expect(JSON.parse(task.body).heldHistoryAdmission).toMatchObject({jobId:'j',epoch:1,owner:'lead@xv',ownerGeneration:'lead-g1',planRevision:'current'});
 const bind=()=>({rigId:'xv',operationId:'observer-renewal',effects:svc().legacyInventory('xv','none',true).heldHistory!,recovery:{queueId:id,rowHash:historicalDigest(db.prepare('SELECT * FROM queue_items WHERE qitem_id=?').get(id))}});
 expect(()=>svc().bindHeldHistoryRecovery(actor,gen,bind())).toThrow('Actual current Operator claim');
 // Supported committed transport delivery precedes the actual recipient claim.
 repo.attachTransport({send:async()=>({ok:true,verified:true})});await recovery.deliverCommitted();repo.claim({qitemId:id,destinationSession:actor,identityProvenance:'transport:v1'});
 const bound=bind();
 for(const kind of ['owner-present','plan','job','operator','expiry','claimed','receipt','held-ref']){db.exec('SAVEPOINT refused');
   if(kind==='owner-present'){svc().setRuntimeObserver(async session=>({session,generation:svc().generation(session)!,state:'present',observedAt:clock,fingerprint:'live-returning-owner'}));await svc().refreshRuntimeAvailability('xv');}
   if(kind==='plan')db.prepare("UPDATE coordinator_operations SET receipt=json_set(receipt,'$.revision','changed') WHERE rig_id='xv' AND kind='coordination-plan'").run();
   if(kind==='job')db.prepare("UPDATE watchdog_jobs SET state='stopped' WHERE job_id='j'").run();
   if(kind==='operator')db.prepare("UPDATE occupant_tenures SET generation_uuid='retired' WHERE node_id=?").run(actor);
   if(kind==='expiry')db.prepare("UPDATE queue_items SET expires_at='2000-01-01T00:00:00Z' WHERE qitem_id=?").run(id);
   if(kind==='claimed')db.prepare("UPDATE queue_items SET claimed_by_generation_uuid='retired' WHERE qitem_id=?").run(id);
   if(kind==='receipt')db.prepare("UPDATE coordinator_operations SET receipt='{}' WHERE kind='held-history-recovery-notice'").run();
   const request=kind==='held-ref'?{...bound,effects:[]}:['expiry','claimed'].includes(kind)?{...bound,recovery:bind().recovery}:bound;expect(()=>svc().bindHeldHistoryRecovery(actor,gen,request)).toThrow();expect(svc().get('xv')?.epoch).toBe(1);db.exec('ROLLBACK TO refused');db.exec('RELEASE refused');
   svc().setRuntimeObserver(async session=>({session,generation:svc().generation(session)!,state:session==='lead@xv'?'absent':'present',observedAt:clock,fingerprint:'actual-fixture-native-census'}));await svc().refreshRuntimeAvailability('xv');
 }
 expect(svc().bindHeldHistoryRecovery(actor,gen,bound)).toMatchObject({originalMutations:0});expect(svc().bindHeldHistoryRecovery(actor,gen,bound)).toMatchObject({originalMutations:0});
 db.exec('SAVEPOINT staleReplay');db.prepare("UPDATE queue_items SET state='done' WHERE qitem_id=?").run(id);expect(()=>svc().bindHeldHistoryRecovery(actor,gen,bound)).toThrow();db.exec('ROLLBACK TO staleReplay');db.exec('RELEASE staleReplay');
 const after=recovery.supervise('xv','j')!;expect(after[0]).toMatchObject({state:'pending-peer-acknowledgment',reason:'fresh-native-unavailable-owner'});expect(svc().get('xv')?.epoch).toBe(2);expect(repo.getById('work')).toEqual(originalBefore.work);expect(outbox.getById('wake-intent-old')).toMatchObject({deliveryState:'pending'});
 expect(svc().bindHeldHistoryRecovery.bind(svc(),actor,gen,bound)).toThrow();
 expect(repo.getById('baton')?.state).toBe('pending');repo.claim({qitemId:'baton',destinationSession:'peer@xv',identityProvenance:'transport:v1'});svc().acknowledge('peer@xv',{...token,epoch:2,generation:'peer-g1'},{obligationsDigest:svc().reconciliationDigest('xv'),operationId:'peer-ack'});expect(svc().get('xv')?.state).toBe('active');
});
