import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {resolve} from 'node:path';
import { describe,it,expect,beforeEach,afterEach,vi } from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import type Database from 'better-sqlite3';
import {createDb} from '../src/db/connection.js';import {EventBus} from '../src/domain/event-bus.js';
import {QueueRepository} from '../src/domain/queue-repository.js';import {OutboxHandler} from '../src/domain/outbox-handler.js';
import {CoordinationRecoveryService,coordinationIdle,type CoordinationActivity,type CoordinationTask,type CoordinationPlan} from '../src/domain/coordination-recovery-service.js';
import {SeatActivityService} from '../src/domain/seat-activity-service.js';
import {digest} from '../src/domain/coordinator-authority-service.js';import {seed,token} from './helpers/coordinator-fixture.js';
describe('sustained committed assignment wake',()=>{
 let dir:string,db:Database.Database,repo:QueueRepository,svc:CoordinationRecoveryService,clock:number,samples:Map<string,CoordinationActivity>;
 const task=(key:string,owner='builder@xv',more:Partial<CoordinationTask>={}):CoordinationTask=>({key,packageKey:key,owner,action:'Perform '+key+' and return bounded evidence',deadline:clock+20000,body:key,predecessors:[],admission:{generation:repo.coordinatorAuthority.generation(owner)!,configurationDigest:svc.configurationDigest(owner)!,qualificationRef:'approved/non-subject/'+key,capacityRef:'current/provider/'+key,effortRef:'current/effort/'+key,validUntil:clock+60000},...more});
 const plan=(tasks:CoordinationTask[]):CoordinationPlan=>({rigId:'xv',revision:'r1',operatorGeneration:'operator-agent-g1',stallMs:10000,allowIdlePeerTransfer:true,tasks});
 function sample(session:string):CoordinationActivity {const generation=repo.coordinatorAuthority.generation(session)!;return {generation,identityVerified:true,state:{seatNodeId:session,activity:'idle-at-prompt',needsInput:{count:0,reason:null},decidedBy:'window-sampling',seq:1,changedAt:new Date(clock).toISOString(),rungs:[],lastSwap:{generation,at:new Date(clock).toISOString()}},witness:{seatNodeId:session,sessionName:session,rung:'window-sampling',sourceId:'tmux',seq:1,observedAt:new Date(clock).toISOString(),activity:'idle-at-prompt'}};}
 function configure(tasks:CoordinationTask[],resources:Record<string,string[]>={}){for(const t of tasks)repo.coordinatorAuthority.admit('operator-agent@kernel','operator-agent-g1','xv',t.packageKey,{inputDigest:digest(t.key),destination:t.owner,bodyHash:digest(t.body),resources:resources[t.key]??[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});return svc.configure('operator-agent@kernel','operator-agent-g1',plan(tasks));}
 function refresh(){for(const s of ['lead@xv','peer@xv','builder@xv','reviewer@xv','architect@xv'])samples.set(s,sample(s));}
 function job(){db.prepare(`INSERT INTO watchdog_jobs(job_id,target_session,policy,interval_seconds,spec_yaml,state,registered_by_session,registered_at,registered_by_generation_uuid) VALUES ('j','operator-agent@kernel','coordinator-continuity',1,'context: {}','active','operator-agent@kernel',?,'operator-agent-g1')`).run(new Date(clock).toISOString());}
 beforeEach(async()=>{vi.useFakeTimers({toFake:['Date']});clock=Date.now();dir=mkdtempSync(join(tmpdir(),'coordination-'));db=createDb(join(dir,'db'));seed(db);for(const session of ['lead@xv','peer@xv','builder@xv'])db.prepare("INSERT INTO bindings(node_id,tmux_session) VALUES (?,?)").run(session,session);db.prepare("INSERT INTO self_host_identity VALUES(1,'fixture-host',?,?)").run(new Date(clock).toISOString(),new Date(clock).toISOString());const bus=new EventBus(db);repo=new QueueRepository(db,bus,{resolveOccupantGeneration:s=>repo.coordinatorAuthority.generation(s)});repo.attachOutbox(new OutboxHandler(db));await repo.create({qitemId:'baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'coordinate',nudge:false});repo.coordinatorAuthority.enable('operator-agent@kernel','operator-agent-g1',{rigId:'xv',batonId:'baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:60000,operationId:'enable'});repo.coordinatorAuthority.acknowledge('lead@xv',token,{operationId:'ack',obligationsDigest:repo.coordinatorAuthority.reconciliationDigest('xv')});samples=new Map();refresh();svc=new CoordinationRecoveryService(repo,s=>samples.get(s)??null,()=>clock);repo.coordinatorAuthority.coordinationRecovery=svc;});
 afterEach(()=>{db.close();rmSync(dir,{recursive:true,force:true});vi.useRealTimers();});

 const normal=()=>[task('product'),task('repair','architect@xv',{recoveryFor:'product'})];
 function resolved(q:string,state='delivered'){db.prepare('UPDATE outbox_entries SET delivery_state=? WHERE audit_pointer=?').run(state,q);}
 it('after real authority transfer and ACK, restaged same assignment is delivered through fenced transport and actually picked up',async()=>{
  configure(normal());const q=svc.reconcile('lead@xv','lead-g1','xv')[0].queueId!;resolved(q);job();clock+=11000;vi.setSystemTime(clock);refresh();expect(svc.supervise('xv','j')?.[0].state).toBe('pending-peer-acknowledgment');expect(()=>svc.reconcile('peer@xv','peer-g1','xv')).toThrow();repo.coordinatorAuthority.acknowledge('peer@xv',{rigId:'xv',epoch:2,generation:'peer-g1'},{operationId:'peer-ack',obligationsDigest:repo.coordinatorAuthority.reconciliationDigest('xv')});
  const sent:string[]=[];repo.attachTransport({send:async(destination,text,opts)=>{repo.coordinatorAuthority.assertManagedSend(opts?.actorSession,destination,opts?.queueAssignmentId);sent.push(text);if(destination==='builder@xv')repo.claim({qitemId:q,destinationSession:destination,identityProvenance:'transport:v1'});return {ok:true,verified:true};}});
  expect(svc.reconcile('peer@xv','peer-g1','xv')[0].queueId).toBe(q);await svc.deliverCommitted();expect(repo.getById(q)?.state).toBe('in-progress');expect(svc.reconcile('peer@xv','peer-g1','xv')[0].state).toBe('picked-up');expect(db.prepare("SELECT count(*) n FROM coordinator_assignments WHERE package_key='product'").get()).toEqual({n:1});expect(sent.join()).toContain('Resume the existing pending assignment');expect(()=>repo.coordinatorAuthority.assertRawSend('peer@xv','builder@xv')).toThrow('Raw managed');
 });
 it('periodic deduplication has minimum 30-second cadence and sending/ambiguous/retained debt refuses retries',()=>{
  configure(normal());const q=svc.reconcile('lead@xv','lead-g1','xv')[0].queueId!;resolved(q);svc.reconcile('lead@xv','lead-g1','xv');const count=()=>db.prepare("SELECT count(*) n FROM outbox_entries WHERE tags LIKE '%queue:coordinator-resume%'").get();expect(count()).toEqual({n:1});resolved(q);svc.reconcile('lead@xv','lead-g1','xv');expect(count()).toEqual({n:1});clock+=29999;vi.setSystemTime(clock);refresh();svc.reconcile('lead@xv','lead-g1','xv');expect(count()).toEqual({n:1});clock+=1;vi.setSystemTime(clock);refresh();svc.reconcile('lead@xv','lead-g1','xv');expect(count()).toEqual({n:2});for(const state of ['sending','indeterminate','retained']){resolved(q,state);clock+=30000;vi.setSystemTime(clock);refresh();db.prepare('UPDATE coordinator_authority SET lease_until=?').run(clock+60000);svc.reconcile('lead@xv','lead-g1','xv');expect(count()).toEqual({n:2});}
 });
 it('new generation, changed configuration, unknown activity or existing claim never gets restaged',()=>{configure(normal());const q=svc.reconcile('lead@xv','lead-g1','xv')[0].queueId!;resolved(q);samples.delete('builder@xv');svc.reconcile('lead@xv','lead-g1','xv');expect(db.prepare("SELECT 1 FROM outbox_entries WHERE tags LIKE '%queue:coordinator-resume%'").get()).toBeUndefined();refresh();db.prepare("UPDATE nodes SET model='changed' WHERE id='builder@xv'").run();svc.reconcile('lead@xv','lead-g1','xv');expect(db.prepare("SELECT 1 FROM outbox_entries WHERE tags LIKE '%queue:coordinator-resume%'").get()).toBeUndefined();});
 it('late delivery after generation or authority drift is superseded without send',async()=>{configure(normal());const q=svc.reconcile('lead@xv','lead-g1','xv')[0].queueId!;resolved(q);svc.reconcile('lead@xv','lead-g1','xv');db.prepare("UPDATE occupant_tenures SET generation_uuid='builder-g2' WHERE node_id='builder@xv'").run();const send=vi.fn(async()=>({ok:true,verified:true}));repo.attachTransport({send});await svc.deliverCommitted();expect(send).not.toHaveBeenCalled();expect(db.prepare("SELECT delivery_state FROM outbox_entries WHERE tags LIKE '%queue:coordinator-resume%'").get()).toEqual({delivery_state:'failed'});});
 it('concurrent transactions cannot stage duplicate effect or create a new assignment',()=>{configure(normal());const q=svc.reconcile('lead@xv','lead-g1','xv')[0].queueId!;resolved(q);const input={rigId:'xv',epoch:1,generation:'lead-g1',actor:'lead@xv',queueId:q,recipient:'builder@xv',recipientGeneration:'builder-g1',now:clock};expect(repo.stageCoordinatorAssignmentWake(input)).toBe(true);expect(repo.stageCoordinatorAssignmentWake(input)).toBe(false);expect(db.prepare("SELECT count(*) n FROM coordinator_assignments WHERE package_key='product'").get()).toEqual({n:1});repo.claim({qitemId:q,destinationSession:'builder@xv'});expect(repo.stageCoordinatorAssignmentWake({...input,now:clock+60000})).toBe(false);});
 it('two actual independent processes stage only one durable resume effect',async()=>{configure(normal());const q=svc.reconcile('lead@xv','lead-g1','xv')[0].queueId!;resolved(q);const input={rigId:'xv',epoch:1,generation:'lead-g1',actor:'lead@xv',queueId:q,recipient:'builder@xv',recipientGeneration:'builder-g1',now:clock};const code=`import D from 'better-sqlite3';import {QueueRepository} from './dist/domain/queue-repository.js';import {EventBus} from './dist/domain/event-bus.js';import {OutboxHandler} from './dist/domain/outbox-handler.js';const db=new D(process.argv[1]);const r=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>r.coordinatorAuthority.generation(s)});r.attachOutbox(new OutboxHandler(db));try{console.log(r.stageCoordinatorAssignmentWake(JSON.parse(process.argv[2])));}catch(e){console.error(e);process.exitCode=7;}finally{db.close();}`;const run=async()=>{const child=spawn(process.execPath,['--input-type=module','-e',code,join(dir,'db'),JSON.stringify(input)],{cwd:resolve('.'),stdio:['ignore','pipe','pipe']});let out='';child.stdout.on('data',b=>out+=b);child.stderr.on('data',b=>out+=b);const [exit]=await once(child,'exit');return {exit,out:out.trim()};};const results=await Promise.all([run(),run()]);expect(results.map(x=>x.exit)).toEqual([0,0]);expect(results.filter(x=>x.out==='true')).toHaveLength(1);expect(results.filter(x=>x.out==='false')).toHaveLength(1);expect(db.prepare("SELECT count(*) n FROM outbox_entries WHERE tags LIKE '%queue:coordinator-resume%'").get()).toEqual({n:1});});
 it('expired current authority and protected seat reservation cannot authorize resume',()=>{configure(normal());const q=svc.reconcile('lead@xv','lead-g1','xv')[0].queueId!;resolved(q);db.prepare("INSERT INTO seat_dispatch_reservations(reservation_id,operation_id,node_id,session_name,predecessor_generation,predecessor_native_id,actor_session,actor_generation,request_hash,expected_json,frozen_snapshot,state,created_at,updated_at) VALUES('r','rotation','builder@xv','builder@xv','builder-g1','native','operator-agent@kernel','operator-agent-g1','h','{}','{}','reserved',?,?)").run(new Date(clock).toISOString(),new Date(clock).toISOString());svc.reconcile('lead@xv','lead-g1','xv');expect(db.prepare("SELECT 1 FROM outbox_entries WHERE tags LIKE '%queue:coordinator-resume%'").get()).toBeUndefined();db.prepare('UPDATE coordinator_authority SET lease_until=?').run(clock-1);expect(()=>svc.reconcile('lead@xv','lead-g1','xv')).toThrow('Only reconciled');});

 it.each([null,[], 'text',{}, {rigId:'xv',epoch:'1',generation:'lead-g1',recipientGeneration:'builder-g1'}, {rigId:'xv',epoch:1,generation:null,recipientGeneration:'builder-g1'}, {rigId:'xv',epoch:1,generation:'lead-g1',recipientGeneration:'builder-g1',extra:true}])('malformed resume proof %j is a local hold while independent frontier commits',async(proof)=>{configure([...normal(),task('independent','reviewer@xv'),task('independent-repair','architect@xv',{recoveryFor:'independent'})]);const q=svc.reconcile('lead@xv','lead-g1','xv')[0].queueId!;resolved(q);db.prepare("UPDATE outbox_entries SET tags=? WHERE audit_pointer=?").run(JSON.stringify(['queue:coordinator-resume',JSON.stringify(proof)]),q);db.prepare("DELETE FROM outbox_entries WHERE audit_pointer IN(SELECT queue_id FROM coordinator_assignments WHERE package_key='independent')").run();db.prepare("DELETE FROM queue_items WHERE qitem_id IN(SELECT queue_id FROM coordinator_assignments WHERE package_key='independent')").run();db.prepare("DELETE FROM coordinator_assignments WHERE package_key='independent'").run();const next=svc.reconcile('lead@xv','lead-g1','xv').find(t=>t.key==='independent')!;expect(next.state).toBe('pending-pickup');repo.claim({qitemId:next.queueId!,destinationSession:'reviewer@xv'});expect(repo.getById(next.queueId!)?.state).toBe('in-progress');expect(db.prepare("SELECT count(*) n FROM outbox_entries WHERE tags LIKE '%queue:coordinator-resume%'").get()).toEqual({n:1});});
 it.each([null,[], 'text',{}, {rigId:'xv',epoch:'1',generation:'lead-g1',recipientGeneration:'builder-g1'}])('malformed proof %j at drain is rejected without transport effect',async(proof)=>{configure(normal());const q=svc.reconcile('lead@xv','lead-g1','xv')[0].queueId!;db.prepare("UPDATE outbox_entries SET tags=? WHERE audit_pointer=?").run(JSON.stringify(['queue:coordinator-resume',JSON.stringify(proof)]),q);const send=vi.fn(async()=>({ok:true,verified:true}));repo.attachTransport({send});await svc.deliverCommitted();expect(send).not.toHaveBeenCalled();expect(repo.getById(q)?.state).toBe('pending');});

});
