import {beforeEach,afterEach,it,expect} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createDb} from '../src/db/connection.js';import {EventBus} from '../src/domain/event-bus.js';import {QueueRepository} from '../src/domain/queue-repository.js';import {OutboxHandler} from '../src/domain/outbox-handler.js';
import {digest,legacyProposalDigest,type LegacyEnrollment} from '../src/domain/coordinator-authority-service.js';
import {seed,token} from './helpers/coordinator-fixture.js';
let dir:string,db:ReturnType<typeof createDb>,repo:QueueRepository;
beforeEach(async()=>{dir=mkdtempSync(join(tmpdir(),'legacy-r07-'));db=createDb(join(dir,'db'));seed(db);repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>repo.coordinatorAuthority.generation(s)});repo.attachOutbox(new OutboxHandler(db));
 await repo.create({qitemId:'baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'coordinate',nudge:false});repo.claim({qitemId:'baton',destinationSession:'lead@xv'});
 await repo.create({qitemId:'work',sourceSession:'lead@xv',destinationSession:'builder@xv',body:'valuable ongoing work',nudge:false});repo.claim({qitemId:'work',destinationSession:'builder@xv'});
});afterEach(()=>{db.close();rmSync(dir,{recursive:true,force:true});});
function packet():LegacyEnrollment{return {rigId:'xv',batonId:'baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:60000,operationId:'migrate',authorizationId:'authorization',inventory:repo.coordinatorAuthority.legacyInventory('xv','authorization'),obligations:[{queueId:'baton',kind:'coordination',evidenceRef:'baton-receipt'},{queueId:'work',kind:'work',evidenceRef:'owner-contract',resourceScope:'exclusive',packageKey:'p1',contract:{inputDigest:digest('inputs'),destination:'builder@xv',bodyHash:digest('valuable ongoing work'),resources:['source/a'],returnContract:{destination:'lead@xv',evidenceRequired:['tests']}}}]};}
async function authorize(p:LegacyEnrollment){await repo.create({qitemId:'authorization',sourceSession:'lead@xv',destinationSession:'operator-agent@kernel',body:JSON.stringify({kind:'coordinator-legacy-enrollment',proposalDigest:legacyProposalDigest(p)}),nudge:false});repo.claim({qitemId:'authorization',destinationSession:'operator-agent@kernel'});}
const svc=()=>repo.coordinatorAuthority;const migrate=(p:LegacyEnrollment)=>svc().migrateLegacy('operator-agent@kernel','operator-agent-g1',p);
it('preserves work and returns; acknowledgment fences new work and replay prevents duplicate',async()=>{const p=packet();await authorize(p);const before=repo.getById('work');expect(migrate(p).state).toBe('reconciling');expect(repo.getById('work')).toEqual(before);expect(migrate(p).epoch).toBe(1);
 await expect(repo.create({sourceSession:'lead@xv',destinationSession:'builder@xv',body:'valuable ongoing work',dispatch:{token,packageKey:'p1'},nudge:false})).rejects.toThrow('not reconciled');
 svc().acknowledge('lead@xv',token,{obligationsDigest:svc().reconciliationDigest('xv'),operationId:'ack'});
 const replay=await repo.create({sourceSession:'lead@xv',destinationSession:'builder@xv',body:'valuable ongoing work',dispatch:{token,packageKey:'p1'},nudge:false});expect(replay.qitemId).toBe('work');
 const result=await repo.create({qitemId:'result',sourceSession:'builder@xv',destinationSession:'lead@xv',body:JSON.stringify({packageKey:'p1',inputDigest:digest('inputs'),evidence:[{kind:'tests',ref:'actual-result'}]}),nudge:false});
 repo.update({qitemId:'work',actorSession:'builder@xv',state:'done',closureReason:'no-follow-on'});svc().dispose('builder@xv','builder-g1','xv','p1',result.qitemId);expect(db.prepare('SELECT count(*) n FROM coordinator_resources').get()).toEqual({n:0});});
it('rejects snapshot drift atomically without closing work',async()=>{const p=packet();await authorize(p);db.prepare("UPDATE queue_items SET body='changed' WHERE qitem_id='work'").run();expect(()=>migrate(p)).toThrow('inventory changed');expect(svc().get('xv')).toBeUndefined();expect(repo.getById('work')?.state).toBe('in-progress');});
it('rejects incomplete classification',async()=>{const p=packet();p.obligations.pop();await authorize(p);expect(()=>migrate(p)).toThrow('Every exact');expect(svc().get('xv')).toBeUndefined();});
it('requires current Lead authorization',async()=>{const p=packet();await authorize(p);db.prepare("UPDATE queue_items SET minting_generation_uuid='retired' WHERE qitem_id='authorization'").run();expect(()=>migrate(p)).toThrow('Lead durable exact');});
it('refuses unknown resources atomically',async()=>{const p=packet();p.obligations[1]!.contract!.resources=[];await authorize(p);expect(()=>migrate(p)).toThrow('known exclusive');expect(svc().get('xv')).toBeUndefined();expect(db.prepare('SELECT count(*) n FROM coordinator_packages').get()).toEqual({n:0});});
it('cannot disguise worker as coordination',async()=>{const p=packet();p.obligations[1]={queueId:'work',kind:'coordination',evidenceRef:'fake'};await authorize(p);expect(()=>migrate(p)).toThrow('disguised');expect(svc().get('xv')).toBeUndefined();});
it('rejects retired claim',async()=>{db.prepare("UPDATE queue_items SET claimed_by_generation_uuid='retired' WHERE qitem_id='work'").run();const p=packet();await authorize(p);expect(()=>migrate(p)).toThrow('another occupant');expect(svc().get('xv')).toBeUndefined();});
it('changed replay cannot reset epoch',async()=>{const p=packet();await authorize(p);migrate(p);expect(()=>migrate({...p,leaseMs:10000})).toThrow('changed contract');});
it('rejects unresolved outbox effects',async()=>{await repo.create({qitemId:'uncertain',sourceSession:'lead@xv',destinationSession:'builder@xv',body:'uncertain',nudge:true});db.prepare("INSERT INTO outbox_entries(outbox_id,sender_session,destination_session,body,ts_dispatched,delivery_state) VALUES ('effect','lead@xv','builder@xv','uncertain','now','pending')").run();const p=packet();p.obligations.push({queueId:'uncertain',kind:'coordination',evidenceRef:'unknown'});await authorize(p);expect(p.inventory.uncertainEffects.length).toBeGreaterThan(0);expect(()=>migrate(p)).toThrow('Uncertain delivery');expect(svc().get('xv')).toBeUndefined();});
it('overlapping imported scopes roll back every authority/package/resource write',async()=>{await repo.create({qitemId:'other-work',sourceSession:'lead@xv',destinationSession:'reviewer@xv',body:'review',nudge:false});const p=packet();p.obligations.push({queueId:'other-work',kind:'work',evidenceRef:'review-contract',resourceScope:'exclusive',packageKey:'p2',contract:{inputDigest:digest('other-input'),destination:'reviewer@xv',bodyHash:digest('review'),resources:['source/a'],returnContract:{destination:'lead@xv',evidenceRequired:['review']}}});await authorize(p);expect(()=>migrate(p)).toThrow('overlaps');for(const table of ['coordinator_authority','coordinator_packages','coordinator_assignments','coordinator_resources'])expect(db.prepare(`SELECT count(*) n FROM ${table}`).get()).toEqual({n:0});expect(repo.getById('work')?.state).toBe('in-progress');});
it('explicit attributed read-only work imports without invented exclusive scopes',async()=>{const p=packet();p.obligations[1]!.resourceScope='read-only';p.obligations[1]!.contract!.resources=[];await authorize(p);migrate(p);expect(db.prepare('SELECT count(*) n FROM coordinator_resources').get()).toEqual({n:0});});
it('new queue work after authorization invalidates full snapshot',async()=>{const p=packet();await authorize(p);await repo.create({sourceSession:'builder@xv',destinationSession:'lead@xv',body:'actual result',nudge:false});expect(()=>migrate(p)).toThrow('inventory changed');expect(svc().get('xv')).toBeUndefined();});
it('unknown host-qualified rig debt remains in snapshot and cannot be omitted',async()=>{await repo.create({qitemId:'unknown',sourceSession:'unknown@xv@remote',destinationSession:'operator-agent@kernel',body:'debt',nudge:false});const p=packet();await authorize(p);expect(p.inventory.rows.some(r=>r.queueId==='unknown')).toBe(true);expect(()=>migrate(p)).toThrow('Every exact');});
it('current Operator and Lead generations cannot be replaced by proposal',async()=>{const p=packet();await authorize(p);expect(()=>svc().migrateLegacy('operator-agent@kernel','retired',p)).toThrow('retired');db.prepare("UPDATE occupant_tenures SET generation_uuid='lead-g2' WHERE node_id='lead@xv'").run();expect(()=>migrate(p)).toThrow('retired');});
it('ongoing worker retains admitted exact review handoff after enrollment',async()=>{const p=packet();p.obligations[1]!.contract!.returnContract.transitions=[{source:'builder@xv',destination:'reviewer@xv',bodyHash:digest('review result')}];await authorize(p);migrate(p);svc().acknowledge('lead@xv',token,{obligationsDigest:svc().reconciliationDigest('xv'),operationId:'ack'});const handoff=await repo.handoff({qitemId:'work',fromSession:'builder@xv',toSession:'reviewer@xv',body:'review result',dispatch:{token:{...token,generation:'builder-g1'},packageKey:'p1'},nudge:false});expect(repo.getById('work')?.state).toBe('handed-off');expect(repo.getById(handoff.created.qitemId)?.destinationSession).toBe('reviewer@xv');expect(db.prepare('SELECT count(*) n FROM coordinator_resources').get()).toEqual({n:1});});
it('authorization must be claimed by current Operator',async()=>{const p=packet();await authorize(p);db.prepare("UPDATE queue_items SET claimed_by_generation_uuid='retired' WHERE qitem_id='authorization'").run();expect(()=>migrate(p)).toThrow('Lead durable exact');expect(svc().get('xv')).toBeUndefined();});

it('same-generation replay survives terminal authorization but new Operator cannot inherit operation',async()=>{const p=packet();await authorize(p);const original=migrate(p);repo.update({qitemId:'authorization',actorSession:'operator-agent@kernel',state:'done',closureReason:'no-follow-on'});expect(migrate(p)).toEqual(original);db.prepare("UPDATE occupant_tenures SET generation_uuid='operator-agent-g2' WHERE node_id='operator-agent@kernel'").run();expect(()=>migrate(p)).toThrow('retired');expect(()=>svc().migrateLegacy('operator-agent@kernel','operator-agent-g2',p)).toThrow('Operation ID reused');expect(svc().get('xv')).toEqual(original);});
