import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {createHash} from 'node:crypto';
import {createFullTestDb} from './helpers/test-app.js';
import {seed} from './helpers/coordinator-fixture.js';
import {OutboxHandler} from '../src/domain/outbox-handler.js';
import {SeatDeliveryGuard,resolveGuardTarget} from '../src/domain/seat-delivery-guard.js';
import {SessionRegistry} from '../src/domain/session-registry.js';
import {QueueRepository} from '../src/domain/queue-repository.js';
import {EventBus} from '../src/domain/event-bus.js';
import {Hono} from 'hono';
import {queueRoutes} from '../src/routes/queue.js';
let db:ReturnType<typeof createFullTestDb>,outbox:OutboxHandler,guard:SeatDeliveryGuard,repo:QueueRepository;
beforeEach(()=>{db=createFullTestDb();seed(db);db.exec('CREATE TABLE IF NOT EXISTS seat_delivery_guards(node_id TEXT PRIMARY KEY,desired INTEGER NOT NULL,effective INTEGER NOT NULL)');outbox=new OutboxHandler(db);guard=new SeatDeliveryGuard(db,name=>resolveGuardTarget(db,name));const sessions=new SessionRegistry(db);repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>sessions.currentOccupantGenerationForSession(s)});});afterEach(()=>{vi.restoreAllMocks();db.close();});
function packet(outboxId?:string){const e=outbox.record({outboxId,senderSession:'builder@xv',destinationSession:'lead@xv',body:'valuable original message',auditPointer:'existing-immutable-pointer'});return {outboxId:e.outboxId,bodySha256:createHash('sha256').update(e.body).digest('hex'),expectedState:'pending' as const,operationId:'abandon-1',authorizationId:'auth',reason:'preserve unknown delivery and withdraw obsolete effect',evidenceRef:'native-history-inspection-1',actor:'builder@xv',generation:'builder-g1'};}
async function authorize(p:ReturnType<typeof packet>,provenance='transport:v1'){const body={kind:'outbox-abandon-authorization',outboxId:p.outboxId,bodySha256:p.bodySha256,expectedState:p.expectedState,operationId:p.operationId,senderGeneration:p.generation,reason:p.reason,evidenceRef:p.evidenceRef};await repo.create({qitemId:p.authorizationId,sourceSession:'operator-agent@kernel',destinationSession:p.actor,body:JSON.stringify(body),identityProvenance:provenance,nudge:false});repo.claim({qitemId:p.authorizationId,destinationSession:p.actor});}
it('explicit abandonment retains original payload/audit/custody and records uncertainty, never delivery',async()=>{const p=packet();await authorize(p);const before=outbox.getById(p.outboxId)!;const queue=db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all(),sessions=db.prepare('SELECT * FROM sessions').all(),tenures=db.prepare('SELECT * FROM occupant_tenures').all();const result=await outbox.abandonUncertain(p,guard);expect(result).toMatchObject({...before,deliveryState:'retired',retiredAt:expect.any(String),retiredBy:p.actor,retirementReason:`Uncertain effect explicitly abandoned: ${p.reason}`});expect(result.retiredAt).toBeTruthy();expect(result.deliveredAt).toBeNull();expect(db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all()).toEqual(queue);expect(db.prepare('SELECT * FROM sessions').all()).toEqual(sessions);expect(db.prepare('SELECT * FROM occupant_tenures').all()).toEqual(tenures);const audit=JSON.parse((db.prepare("SELECT payload FROM events WHERE type='outbox.uncertain_abandoned'").get() as {payload:string}).payload);expect(audit).toMatchObject({originalState:'pending',deliveryConclusion:'unknown',originalAuditPointer:before.auditPointer,evidenceRef:p.evidenceRef});repo.update({qitemId:'auth',actorSession:p.actor,state:'done',closureReason:'no-follow-on'});expect(await outbox.abandonUncertain(p,guard)).toEqual(result);expect(db.prepare("SELECT count(*) n FROM events WHERE type='outbox.uncertain_abandoned'").get()).toEqual({n:1});});
it('requires current exact Operator transport authorization claimed by sender',async()=>{const p=packet();await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('Kernel Operator');await authorize(p,'claimed:v1');await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('Kernel Operator');expect(outbox.getById(p.outboxId)?.deliveryState).toBe('pending');});
it('refuses unknown or retired sender generation and stale Operator authorization',async()=>{const p=packet();await authorize(p);await expect(outbox.abandonUncertain({...p,generation:'retired'},guard)).rejects.toThrow('Current local');db.prepare("UPDATE occupant_tenures SET generation_uuid='operator-g2' WHERE node_id='operator-agent@kernel'").run();await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('Kernel Operator');expect(outbox.getById(p.outboxId)?.deliveryState).toBe('pending');});
it('waits under lifecycle and refuses concurrent effect drift',async()=>{const p=packet();await authorize(p);let release!:()=>void,entered!:()=>void;const ready=new Promise<void>(r=>entered=r);const held=guard.lifecycle(['builder@xv'],async()=>{entered();await new Promise<void>(r=>release=r);});await ready;let settled=false;const selection=outbox.abandonUncertain(p,guard).finally(()=>settled=true);await new Promise(r=>setTimeout(r,10));expect(settled).toBe(false);outbox.markFailed(p.outboxId);release();await held;await expect(selection).rejects.toThrow('Frozen effect');expect(outbox.getById(p.outboxId)?.deliveryState).toBe('failed');});
it('rejects changed replay and new sender occupant',async()=>{const p=packet();await authorize(p);await outbox.abandonUncertain(p,guard);await expect(outbox.abandonUncertain({...p,reason:'changed'},guard)).rejects.toThrow('changed contract');db.prepare("UPDATE occupant_tenures SET generation_uuid='builder-g2' WHERE node_id='builder@xv'").run();await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('Current local');await expect(outbox.abandonUncertain({...p,generation:'builder-g2'},guard)).rejects.toThrow('changed contract');});
it('refuses executable wakes, wrong body, missing guards and preexisting terminal outcomes',async()=>{const wake=packet('wake-intent-preserve');await expect(outbox.abandonUncertain(wake,guard)).rejects.toThrow('non-executable');const p=packet();await authorize(p);await expect(outbox.abandonUncertain(p,undefined)).rejects.toThrow('lifecycle');await expect(outbox.abandonUncertain({...p,bodySha256:'0'.repeat(64)},guard)).rejects.toThrow('Frozen effect');outbox.markDelivered(p.outboxId);await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('Frozen effect');expect(outbox.getById(p.outboxId)?.deliveryState).toBe('delivered');});
it('API derives sender and generation and returns the explicit uncertainty disposition',async()=>{const p=packet();await authorize(p);const app=new Hono();app.use('*',async(c,next)=>{c.set('outboxHandler' as never,outbox as never);c.set('tmuxAdapter' as never,{deliveryGuard:guard} as never);await next();});app.route('/queue',queueRoutes());const send=(headers:Record<string,string>)=>app.request('/queue/outbox/abandon-uncertain',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({...p,actor:'forged'})});expect((await send({})).status).toBe(400);const valid=await send({'X-OpenRig-Session':p.actor,'X-OpenRig-Occupant-Generation':p.generation});expect(valid.status).toBe(200);expect(await valid.json()).toMatchObject({deliveryState:'retired',retiredBy:p.actor,deliveredAt:null});});

it('audit failure rolls back disposition atomically',async()=>{const p=packet();await authorize(p);const before=outbox.getById(p.outboxId);vi.spyOn(EventBus.prototype,'persistWithinTransaction').mockImplementationOnce(()=>{throw new Error('audit unavailable')});await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('audit unavailable');expect(outbox.getById(p.outboxId)).toEqual(before);});
it('indeterminate effect preserves its original uncertain outcome and guard/foreign effects refuse',async()=>{const p=packet();outbox.markIndeterminate(p.outboxId);const selected={...p,expectedState:'indeterminate' as const};await authorize(selected as ReturnType<typeof packet>);expect((await outbox.abandonUncertain(selected,guard)).deliveryState).toBe('retired');const proof=JSON.parse((db.prepare("SELECT payload FROM events WHERE type='outbox.uncertain_abandoned'").get() as {payload:string}).payload);expect(proof).toMatchObject({originalState:'indeterminate',deliveryConclusion:'unknown'});const q=packet();db.prepare("UPDATE outbox_entries SET guard_binding=? WHERE outbox_id=?").run(JSON.stringify({nodeId:'builder@xv',session:'builder@xv',occupant:'builder-g1',pane:'%9'}),q.outboxId);await expect(outbox.abandonUncertain(q,guard)).rejects.toThrow('unguarded');});
