import {historicalDigest} from '../src/domain/historical-effect-disposition.js';
import {CoordinationRecoveryService,type CoordinationActivity} from '../src/domain/coordination-recovery-service.js';
import {SeatDeliveryGuard,resolveGuardTarget} from '../src/domain/seat-delivery-guard.js';
import {SessionRegistry} from '../src/domain/session-registry.js';
import {SessionTransport} from '../src/domain/session-transport.js';
import {RigRepository} from '../src/domain/rig-repository.js';
import type {TmuxAdapter} from '../src/adapters/tmux.js';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {Hono} from 'hono';
import {createHash} from 'node:crypto';
import {createFullTestDb} from './helpers/test-app.js';
import {OutboxHandler} from '../src/domain/outbox-handler.js';
import {QueueRepository} from '../src/domain/queue-repository.js';
import {EventBus} from '../src/domain/event-bus.js';
import {queueRoutes} from '../src/routes/queue.js';
import {transportRoutes} from '../src/routes/transport.js';
import {seed} from './helpers/coordinator-fixture.js';
let db:ReturnType<typeof createFullTestDb>,outbox:OutboxHandler;
beforeEach(()=>{db=createFullTestDb();seed(db);outbox=new OutboxHandler(db);});afterEach(()=>{vi.restoreAllMocks();vi.useRealTimers();db.close();});
it.each([
 [{ok:true,verified:true,outcome:'delivered'},'delivered'],
 [{ok:false,reason:'send_failed',outcome:'failed'},'failed'],
 [{ok:true,verified:false,outcome:'rendered-unconfirmed'},'indeterminate'],
 [{ok:true},'indeterminate'],
])('settles direct attempt according to actual result %j',async(result,state)=>{
 const app=new Hono();app.use('*',async(c,next)=>{c.set('outboxHandler' as never,outbox as never);c.set('sessionTransport' as never,{resolveSessions:async()=>({ok:true,sessions:[]}),send:async()=>({...result,sessionName:'lead@xv'})} as never);await next();});app.route('/transport',transportRoutes());
 const response=await app.request('/transport/send',{method:'POST',headers:{'Content-Type':'application/json','X-OpenRig-Session':'builder@xv'},body:JSON.stringify({session:'lead@xv',text:'actual message'})});expect(response.status).toBe(state==='failed'?502:200);expect(outbox.listForSender('builder@xv')[0]).toMatchObject({deliveryState:state});
});
function effect(outcome:'indeterminate'|'failed'='indeterminate'){return outbox.recordDirectAttempt({senderSession:'builder@xv',destinationSession:'lead@xv',body:'actual original message',auditPointer:'original-pointer'},outcome);}
function ack(id:string,patch:Record<string,unknown>={}){db.prepare("INSERT INTO queue_items(qitem_id,ts_created,ts_updated,source_session,destination_session,state,body,minting_generation_uuid) VALUES ('receipt',?,?,?,'builder@xv','pending',?,'lead-g1')").run(new Date(Date.now()+100).toISOString(),new Date().toISOString(),'lead@xv',JSON.stringify({kind:'outbox-delivery-ack',outboxId:id,bodySha256:createHash('sha256').update('actual original message').digest('hex'),...patch}));db.prepare("INSERT INTO queue_transitions(qitem_id,ts,state,transition_note,actor_session,identity_provenance) VALUES ('receipt',?,'pending','created','lead@xv','transport:v1')").run(new Date().toISOString());}
const reconcile=(id:string)=>outbox.reconcileRecipientDelivery({outboxId:id,receiptId:'receipt',actor:'lead@xv',generation:'lead-g1',reason:'verified actual recipient receipt'});
it('reconciles exact recipient receipt atomically without queue mutation and preserves prior pointer',()=>{const e=effect();ack(e.outboxId);const before=db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all();expect(reconcile(e.outboxId).deliveryState).toBe('delivered');expect(db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all()).toEqual(before);expect(JSON.parse(outbox.getById(e.outboxId)!.auditPointer!)).toMatchObject({receiptId:'receipt',priorAuditPointer:'original-pointer',generation:'lead-g1'});expect(reconcile(e.outboxId).deliveryState).toBe('delivered');});
it('rejects unrelated or missing ack, retired generation and executable wake intents',()=>{const e=effect();expect(()=>reconcile(e.outboxId)).toThrow('managed transport');ack(e.outboxId,{bodySha256:'wrong'});expect(()=>reconcile(e.outboxId)).toThrow('acknowledgment');db.prepare("UPDATE queue_items SET body=? WHERE qitem_id='receipt'").run(JSON.stringify({kind:'outbox-delivery-ack',outboxId:e.outboxId,bodySha256:createHash('sha256').update(e.body).digest('hex')}));db.prepare("UPDATE occupant_tenures SET generation_uuid='lead-g2' WHERE node_id='lead@xv'").run();expect(()=>reconcile(e.outboxId)).toThrow('acknowledgment');expect(outbox.getById(e.outboxId)?.deliveryState).toBe('indeterminate');const wake=outbox.record({outboxId:'wake-intent-probe',senderSession:'builder@xv',destinationSession:'lead@xv',body:e.body});expect(()=>reconcile(wake.outboxId)).toThrow('non-executable');});
it('allows acknowledged indeterminate direct effect but refuses failed outcome',()=>{const e=effect();ack(e.outboxId);outbox.markIndeterminate(e.outboxId);expect(reconcile(e.outboxId).deliveryState).toBe('delivered');const failed=effect('failed');expect(()=>reconcile(failed.outboxId)).toThrow();expect(outbox.getById(failed.outboxId)?.deliveryState).toBe('failed');});

it('supported API requires recipient generation and exact durable ack; body actor is ignored',async()=>{const e=effect();ack(e.outboxId);const app=new Hono();app.use('*',async(c,next)=>{c.set('outboxHandler' as never,outbox as never);await next();});app.route('/queue',queueRoutes());const body=JSON.stringify({outboxId:e.outboxId,receiptId:'receipt',reason:'recipient inspected message',actor:'forged'});const send=(headers:Record<string,string>)=>app.request('/queue/outbox/reconcile-delivery',{method:'POST',headers:{'Content-Type':'application/json',...headers},body});expect((await send({})).status).toBe(400);expect((await send({'X-OpenRig-Session':'builder@xv','X-OpenRig-Occupant-Generation':'builder-g1'})).status).toBe(409);const valid=await send({'X-OpenRig-Session':'lead@xv','X-OpenRig-Occupant-Generation':'lead-g1'});expect(valid.status).toBe(200);expect(await valid.json()).toMatchObject({deliveryState:'delivered'});});

it('ordinary recorded audit row has no direct-attempt evidence and cannot be promoted',()=>{const e=outbox.record({senderSession:'builder@xv',destinationSession:'lead@xv',body:'actual original message',identityProvenance:'transport:v1'});ack(e.outboxId);expect(()=>reconcile(e.outboxId)).toThrow('Actual unresolved direct');expect(outbox.getById(e.outboxId)?.deliveryState).toBe('pending');});
it('claimed-source creation cannot establish actual recipient authorship',()=>{const e=effect();ack(e.outboxId);db.prepare("UPDATE queue_transitions SET identity_provenance='claimed:v1' WHERE qitem_id='receipt'").run();expect(()=>reconcile(e.outboxId)).toThrow('managed transport');expect(outbox.getById(e.outboxId)?.deliveryState).toBe('indeterminate');});
it('current recipient selects newest session node before tenure ordinal',()=>{const e=effect();ack(e.outboxId);db.prepare("UPDATE occupant_tenures SET generation_ordinal=5 WHERE node_id='lead@xv'").run();db.prepare("INSERT INTO nodes(id,rig_id,logical_id) VALUES ('new-lead','xv','new-lead')").run();db.prepare("INSERT INTO sessions(id,node_id,session_name) VALUES ('zz-new','new-lead','lead@xv')").run();db.prepare("INSERT INTO occupant_tenures(id,node_id,generation_ordinal,generation_uuid,kind) VALUES ('new-tenure','new-lead',1,'lead-g2','fresh')").run();expect(()=>reconcile(e.outboxId)).toThrow('acknowledgment');db.prepare("UPDATE queue_items SET minting_generation_uuid='lead-g2' WHERE qitem_id='receipt'").run();expect(outbox.reconcileRecipientDelivery({outboxId:e.outboxId,receiptId:'receipt',actor:'lead@xv',generation:'lead-g2',reason:'current recipient ack'}).deliveryState).toBe('delivered');});

it('body-only queue/create fake acknowledgment retains claimed provenance and refuses reconciliation',async()=>{const e=effect();const repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:()=> 'lead-g1'});const app=new Hono();app.use('*',async(c,next)=>{c.set('outboxHandler' as never,outbox as never);c.set('queueRepo' as never,repo as never);await next();});app.route('/queue',queueRoutes());const response=await app.request('/queue/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({qitemId:'receipt',sourceSession:'lead@xv',destinationSession:'builder@xv',body:JSON.stringify({kind:'outbox-delivery-ack',outboxId:e.outboxId,bodySha256:createHash('sha256').update(e.body).digest('hex')}),nudge:false})});expect(response.status).toBe(201);expect(db.prepare("SELECT identity_provenance FROM queue_transitions WHERE qitem_id='receipt' AND transition_note='created'").get()).toEqual({identity_provenance:'claimed:v1'});expect(()=>reconcile(e.outboxId)).toThrow('managed transport');});

const recipientContract=(e:ReturnType<typeof effect>)=>({outboxId:e.outboxId,bodySha256:createHash('sha256').update(e.body).digest('hex'),effectSnapshotSha256:createHash('sha256').update(JSON.stringify(e)).digest('hex'),expectedState:'indeterminate' as const,acknowledged:true as const,reason:'I actually read this exact direct diagnostic report'});
it.each(['lead@xv','operator-agent@kernel'])('native fixed recipient acknowledgment crosses enabled dispatch fence without new work or sender wake: %s',async recipient=>{
 const recipientGeneration=recipient==='lead@xv'?'lead-g1':'operator-agent-g1';
 const repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>repo.coordinatorAuthority.generation(s)});repo.attachOutbox(outbox);await repo.create({qitemId:'baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'coordinate',nudge:false,identityProvenance:'transport:v1'});
 const svc=repo.coordinatorAuthority;svc.enable('operator-agent@kernel','operator-agent-g1',{rigId:'xv',batonId:'baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:600000,operationId:'enable'});repo.claim({qitemId:'baton',destinationSession:'lead@xv',identityProvenance:'transport:v1'});svc.acknowledge('lead@xv',{rigId:'xv',epoch:1,generation:'lead-g1'},{operationId:'ack',obligationsDigest:svc.reconciliationDigest('xv')});
 const e=outbox.recordDirectAttempt({senderSession:'builder@xv',destinationSession:recipient,body:'actual original message',auditPointer:'original-pointer'},'indeterminate'),input=recipientContract(e),app=new Hono();app.use('*',async(c,next)=>{c.set('terminalBearerToken' as never,'test-token' as never);c.set('outboxHandler' as never,outbox as never);c.set('queueRepo' as never,repo as never);await next();});app.route('/queue',queueRoutes());const headers={'Content-Type':'application/json','Authorization':'Bearer test-token','X-OpenRig-Session':recipient,'X-OpenRig-Occupant-Generation':recipientGeneration};
 const refused=await app.request('/queue/create',{method:'POST',headers,body:JSON.stringify({qitemId:'generic-proof',sourceSession:recipient,destinationSession:'builder@xv',body:JSON.stringify({kind:'outbox-delivery-ack',outboxId:e.outboxId,bodySha256:input.bodySha256}),nudge:false})});expect(refused.status).toBe(409);expect(await refused.json()).toMatchObject({error:recipient==='lead@xv'?'coordinator_envelope_required':'coordinator_dispatch_required'});expect(repo.getById('generic-proof')).toBeNull();
 const authority=svc.get('xv'),baton=repo.getById('baton'),priorEvents=db.prepare('SELECT count(*) n FROM events').get();const send=()=>app.request('/queue/outbox/acknowledge',{method:'POST',headers,body:JSON.stringify(input)});
 const first=await send();expect(first.status).toBe(200);const result=await first.json() as any;expect(result.entry).toMatchObject({deliveryState:'delivered',body:e.body,senderSession:e.senderSession,destinationSession:e.destinationSession});expect(repo.getById(result.receiptId)).toMatchObject({state:'done',body:JSON.stringify({kind:'outbox-delivery-ack',outboxId:e.outboxId,bodySha256:input.bodySha256}),closureReason:'no-follow-on'});expect(db.prepare('SELECT minting_generation_uuid FROM queue_items WHERE qitem_id=?').get(result.receiptId)).toEqual({minting_generation_uuid:recipientGeneration});expect(repo.transitionLog.listForQitem(result.receiptId)).toMatchObject([{actorSession:recipient,identityProvenance:'transport:v1',state:'done',transitionNote:'created'}]);
 const after=db.prepare('SELECT * FROM events ORDER BY seq').all();expect((await send()).status).toBe(200);expect(db.prepare('SELECT * FROM events ORDER BY seq').all()).toEqual(after);expect(svc.get('xv')).toEqual(authority);expect(repo.getById('baton')).toEqual(baton);expect(outbox.listPending('wake-intent-')).toEqual([]);expect(db.prepare('SELECT count(*) n FROM coordinator_assignments').get()).toEqual({n:0});expect(db.prepare('SELECT count(*) n FROM coordinator_resources').get()).toEqual({n:0});expect(JSON.parse(result.entry.auditPointer)).toMatchObject({receiptId:result.receiptId,priorAuditPointer:'original-pointer',actor:recipient,generation:recipientGeneration});expect(after.length).toBe((priorEvents as any).n+1);
});
it.each(['actor','generation','hash','snapshot','state','ack-false','extra-body','ordinary-row','failed','wake','guard','quarantine','missing-origin','changed-origin','id-collision'])('native fixed recipient acknowledgment refuses %s without any partial receipt',kind=>{
 let e=effect();let actor='lead@xv',generation='lead-g1',input=recipientContract(e);
 if(kind==='actor')actor='operator-agent@kernel';if(kind==='generation')generation='retired';if(kind==='hash')input={...input,bodySha256:'a'.repeat(64)};if(kind==='snapshot')input={...input,effectSnapshotSha256:'a'.repeat(64)};if(kind==='state')input={...input,expectedState:'pending'} as any;if(kind==='ack-false')input={...input,acknowledged:false} as any;if(kind==='extra-body')input={...input,body:'arbitrary'} as any;
 if(kind==='ordinary-row'||kind==='wake'){e=outbox.record({outboxId:kind==='wake'?'wake-intent-executable':'ordinary-audit',senderSession:'builder@xv',destinationSession:'lead@xv',body:e.body});input={...recipientContract(e),expectedState:'pending'} as any;}
 if(kind==='failed'){e=effect('failed');input=recipientContract(e);}
 if(kind==='guard'){db.prepare('UPDATE outbox_entries SET guard_binding=? WHERE outbox_id=?').run(JSON.stringify({nodeId:'lead@xv',session:'lead@xv',occupant:'lead-g1',pane:null}),e.outboxId);input=recipientContract(outbox.getById(e.outboxId)!);}
 if(kind==='quarantine')db.prepare("INSERT INTO outbox_historical_quarantines VALUES (?, 'xv', 'hash','held','auth',?, 'held',?)").run(e.outboxId,Date.now()+600000,new Date().toISOString());
 if(kind==='missing-origin')db.prepare("DELETE FROM events WHERE type='outbox.direct_attempt'").run();if(kind==='changed-origin')db.prepare("UPDATE events SET payload=json_set(payload,'$.bodySha256','changed') WHERE type='outbox.direct_attempt'").run();
 if(kind==='id-collision'){const id='qitem-outbox-recipient-ack-'+createHash('sha256').update(JSON.stringify([e.outboxId,actor,generation])).digest('hex');db.prepare("INSERT INTO queue_items(qitem_id,ts_created,ts_updated,source_session,destination_session,state,body) VALUES (?,?,?,'lead@xv','builder@xv','done','arbitrary existing row')").run(id,new Date().toISOString(),new Date().toISOString());}
 const before={outbox:outbox.getById(e.outboxId),queues:db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all(),events:db.prepare('SELECT * FROM events ORDER BY seq').all(),transitions:db.prepare('SELECT * FROM queue_transitions').all()};expect(()=>outbox.acknowledgeRecipientDelivery(actor,generation,input)).toThrow();expect({outbox:outbox.getById(e.outboxId),queues:db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all(),events:db.prepare('SELECT * FROM events ORDER BY seq').all(),transitions:db.prepare('SELECT * FROM queue_transitions').all()}).toEqual(before);
});
it('native fixed recipient acknowledgment exact replay conflicts with changed request stale occupant and receipt drift',()=>{
 const e=effect(),input=recipientContract(e),result=outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',input),before=outbox.getById(e.outboxId);expect(()=>outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',{...input,reason:'changed assertion'})).toThrow('replay');db.exec('SAVEPOINT stale');db.prepare("UPDATE occupant_tenures SET generation_uuid='lead-g2' WHERE node_id='lead@xv'").run();expect(()=>outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',input)).toThrow('native recipient');db.exec('ROLLBACK TO stale');db.exec('RELEASE stale');db.exec('SAVEPOINT uncertainReplay');db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run(e.outboxId);const uncertain=outbox.getById(e.outboxId);expect(()=>outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',input)).toThrow('replay');expect(outbox.getById(e.outboxId)).toEqual(uncertain);db.exec('ROLLBACK TO uncertainReplay');db.exec('RELEASE uncertainReplay');db.prepare("UPDATE queue_items SET body='changed proof' WHERE qitem_id=?").run(result.receiptId);expect(()=>outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',input)).toThrow('replay');expect(outbox.getById(e.outboxId)).toEqual(before);
});
it('native fixed recipient acknowledgment API refuses missing transport and body identity assertions',async()=>{
 const e=effect(),input=recipientContract(e),app=new Hono();app.use('*',async(c,next)=>{c.set('terminalBearerToken' as never,'test-token' as never);c.set('outboxHandler' as never,outbox as never);await next();});app.route('/queue',queueRoutes());const send=(headers:Record<string,string>,body:any=input)=>app.request('/queue/outbox/acknowledge',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer test-token',...headers},body:JSON.stringify(body)});expect((await send({})).status).toBe(403);expect((await send({'X-OpenRig-Session':'lead@xv'})).status).toBe(403);expect((await send({'X-OpenRig-Session':'lead@xv','X-OpenRig-Occupant-Generation':'lead-g1'},{...input,actor:'lead@xv'})).status).toBe(409);expect(db.prepare('SELECT count(*) n FROM queue_items').get()).toEqual({n:0});expect(outbox.getById(e.outboxId)).toEqual(e);
});

async function automaticAckFixture(verified=true){
 vi.useFakeTimers({toFake:['Date']});db.prepare("INSERT INTO self_host_identity(singleton,host_id,minted_at,reconciled_at) VALUES (1,'local',?,?)").run(new Date().toISOString(),new Date().toISOString());const clock=Date.now(),repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>repo.coordinatorAuthority.generation(s)});repo.attachOutbox(outbox);const svc=repo.coordinatorAuthority;
 await repo.create({qitemId:'auto-baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'coordinate',nudge:false,identityProvenance:'transport:v1'});svc.enable('operator-agent@kernel','operator-agent-g1',{rigId:'xv',batonId:'auto-baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:3600000,operationId:'enable-auto'});svc.acknowledge('lead@xv',{rigId:'xv',epoch:1,generation:'lead-g1'},{operationId:'ack-auto',obligationsDigest:svc.reconciliationDigest('xv')});if(repo.getById('auto-baton')?.state==='pending')repo.claim({qitemId:'auto-baton',destinationSession:'lead@xv',identityProvenance:'transport:v1'});
 const sample=(session:string):CoordinationActivity=>({generation:svc.generation(session)!,identityVerified:true,state:{seatNodeId:session,activity:'idle-at-prompt',needsInput:{count:0,reason:null},decidedBy:'window-sampling',seq:1,changedAt:new Date(Date.now()).toISOString(),rungs:[],lastSwap:null},witness:{seatNodeId:session,sessionName:session,rung:'window-sampling',sourceId:'tmux',seq:1,observedAt:new Date(Date.now()).toISOString(),activity:'idle-at-prompt'}});const recovery=new CoordinationRecoveryService(repo,sample);svc.coordinationRecovery=recovery;
 db.prepare("UPDATE nodes SET runtime='codex' WHERE id='reviewer@xv'").run();const tasks=['reviewer@xv','architect@xv'].map((owner,i)=>({key:'auto-task'+i,packageKey:'auto-task'+i,owner,action:'Ready bounded work',body:'bounded product'+i,deadline:clock+1800000,predecessors:[],...(i?{recoveryFor:'auto-task0'}:{}),admission:{generation:svc.generation(owner)!,configurationDigest:recovery.configurationDigest(owner)!,qualificationRef:'current-proof',capacityRef:'current',effortRef:'current',validUntil:clock+1800000}}));for(const t of tasks)svc.admit('operator-agent@kernel','operator-agent-g1','xv',t.packageKey,{inputDigest:t.key,destination:t.owner,bodyHash:createHash('sha256').update(t.body).digest('hex'),resources:[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});recovery.configure('operator-agent@kernel','operator-agent-g1',{rigId:'xv',revision:'auto-plan',operatorGeneration:'operator-agent-g1',stallMs:10000,allowIdlePeerTransfer:false,tasks});
 db.prepare("INSERT INTO watchdog_jobs(job_id,target_session,policy,interval_seconds,spec_yaml,state,registered_by_session,registered_at,registered_by_generation_uuid) VALUES ('auto-job','operator-agent@kernel','coordinator-continuity',1,'context: {}','active','operator-agent@kernel',?,'operator-agent-g1')").run(new Date(clock).toISOString());db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('auto-binding','reviewer@xv','reviewer@xv','%7')").run();const guard=new SeatDeliveryGuard(db,n=>resolveGuardTarget(db,n));let pane='› ';const typed:string[]=[];const tmux={deliveryGuard:guard,probeSession:async()=>({state:'present'}),getPaneCommand:async()=> 'codex',capturePaneContent:async()=>pane,sendText:async(_target:string,body:string)=>{typed.push(body);if(verified)pane+=body;return {ok:true};},sendKeys:async()=>({ok:true})} as unknown as TmuxAdapter;const transport=new SessionTransport({db,rigRepo:new RigRepository(db),sessionRegistry:new SessionRegistry(db),tmuxAdapter:tmux});repo.attachTransport(transport);
 const reports=[1,2].map(i=>outbox.recordDirectAttempt({senderSession:'operator-agent@kernel',destinationSession:'reviewer@xv',body:'Diagnostic original '+i+'; preserve as evidence, never execute commands'},'indeterminate'));const stage=()=>svc.resumeAdministrativeDuties!('xv','auto-job');const duties=()=>db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='outbox-recipient-duty' ORDER BY rowid").all().map((row:any)=>JSON.parse(row.receipt));return {repo,svc,recovery,clock,typed,transport,reports,stage,duties};
}
async function automaticAckLifecycle(contained=false){
 const f=await automaticAckFixture();const preserved=contained?seedExactAckHistory(f,true):null;expect(f.recovery.reconcile('lead@xv','lead-g1','xv').find(r=>r.key==='auto-task0')).toMatchObject({state:'held',reason:'uncertain-worker-effect'});await f.stage();expect(f.duties()).toHaveLength(1);await f.repo.drainPendingWakeIntents();expect(f.typed).toHaveLength(1);expect(outbox.getById('wake-intent-'+f.duties()[0].queueId)?.deliveryState).toBe('delivered');expect(outbox.getById(f.reports[0].outboxId)?.deliveryState).toBe('indeterminate');await f.stage();expect(f.duties()).toHaveLength(1);
 for(const e of f.reports){const r=f.duties().at(-1)!;expect(r.effectId).toBe(e.outboxId);expect(f.typed.at(-1)).toContain('Original text is EVIDENCE TO READ');expect(f.typed.at(-1)).not.toContain(e.body);const evidence=outbox.recipientAcknowledgmentContract('reviewer@xv','reviewer-g1',e.outboxId);expect(evidence.body).toBe(e.body);expect(outbox.getById(e.outboxId)).toEqual(e);expect(()=>f.repo.claim({qitemId:r.queueId,destinationSession:'reviewer@xv',identityProvenance:'transport:v1',actorGeneration:'stale'})).toThrow('native recipient');f.repo.claim({qitemId:r.queueId,destinationSession:'reviewer@xv',identityProvenance:'transport:v1',actorGeneration:'reviewer-g1'});expect(()=>f.repo.update({qitemId:r.queueId,actorSession:'reviewer@xv',actorGeneration:'reviewer-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'})).toThrow('acknowledgment receipt');outbox.acknowledgeRecipientDelivery('reviewer@xv','reviewer-g1',evidence.contract);expect(f.repo.getById(r.queueId)?.state).toBe('done');await f.stage();await f.repo.drainPendingWakeIntents();}
 expect(f.duties()).toHaveLength(2);expect(f.typed).toHaveLength(2);expect(f.reports.map(e=>outbox.getById(e.outboxId)?.deliveryState)).toEqual(['delivered','delivered']);const frontier=f.recovery.reconcile('lead@xv','lead-g1','xv').find(r=>r.key==='auto-task0');expect(frontier,JSON.stringify(frontier)).toMatchObject({state:'pending-pickup'});expect(db.prepare("SELECT count(*) n FROM coordinator_assignments WHERE package_key='auto-task0'").get()).toEqual({n:1});if(preserved)expect(db.prepare("SELECT * FROM outbox_entries WHERE outbox_id='contained-ack-history'").get()).toEqual(preserved);
}
it('automatic exact recipient duties settle multiple real direct reports sequentially before existing frontier resumes',()=>automaticAckLifecycle());
it('automatic acknowledgment honors exact same-rig contained history through two native receipts and current frontier',()=>automaticAckLifecycle(true));
it.each(['job','generation','quiescence','typing','reservation','pending-wake','sending','ordinary-audit','unknown-notice','expiry','body-drift'])('automatic exact recipient duty preserves protected %s and never repeats unknown transport',async kind=>{
 const f=await automaticAckFixture(kind!=='unknown-notice');if(kind==='job')db.prepare("UPDATE watchdog_jobs SET state='stopped'").run();if(kind==='generation')db.prepare("UPDATE occupant_tenures SET generation_uuid='new' WHERE node_id='operator-agent@kernel'").run();if(kind==='quiescence')db.prepare("UPDATE coordinator_operations SET receipt=json_set(receipt,'$.dispatchRestrictions',json('[{\"session\":\"reviewer@xv\",\"generation\":\"reviewer-g1\",\"validUntil\":9999999999999,\"packageKeys\":[]}]')) WHERE kind='coordination-plan'").run();if(kind==='typing')db.prepare("INSERT INTO seat_delivery_guards(node_id,desired,effective,actor,reason,changed_at) VALUES ('reviewer@xv',1,1,'test','typing',datetime('now'))").run();if(kind==='reservation')db.prepare("INSERT INTO seat_dispatch_reservations(reservation_id,operation_id,node_id,session_name,predecessor_generation,predecessor_native_id,actor_session,actor_generation,request_hash,expected_json,frozen_snapshot,state,created_at,updated_at) VALUES ('reserved','cutover','reviewer@xv','reviewer@xv','reviewer-g1','native-reviewer','operator-agent@kernel','operator-agent-g1','hash','{}','{}','reserved',?,datetime('now'))").run(new Date().toISOString());if(kind==='pending-wake'||kind==='ordinary-audit'||kind==='sending'){const e=outbox.record({outboxId:kind==='pending-wake'?'wake-intent-executable':'unproven-effect',senderSession:'reviewer@xv',destinationSession:'operator-agent@kernel',body:'do not retry'});if(kind==='sending')outbox.claimForDelivery(e.outboxId);}
 await f.stage();if(['expiry','body-drift','unknown-notice'].includes(kind)){expect(f.duties()).toHaveLength(1);const r=f.duties()[0];if(kind==='expiry')vi.setSystemTime(r.deadline+1);if(kind==='body-drift')db.prepare('UPDATE outbox_entries SET body=? WHERE outbox_id=?').run('changed evidence',r.effectId);await f.repo.drainPendingWakeIntents();const notice=outbox.getById('wake-intent-'+r.queueId)!;expect(notice.deliveryState).toBe(kind==='unknown-notice'?'indeterminate':'failed');const before=f.typed.length;await f.stage();await f.repo.drainPendingWakeIntents();expect(f.typed).toHaveLength(before);expect(f.duties()).toHaveLength(1);if(kind==='unknown-notice')expect(f.typed).toHaveLength(1);else expect(f.typed).toHaveLength(0);}else{expect(f.duties()).toHaveLength(0);expect(f.typed).toHaveLength(0);}expect(f.reports.map(e=>outbox.getById(e.outboxId)?.deliveryState)).toEqual(['indeterminate','indeterminate']);
});

it('automatic recipient scan reaches current real reports beyond 2000 historical notices without per-notice origin scans',async()=>{
 const f=await automaticAckFixture();
 const insert=db.prepare("INSERT INTO outbox_entries(outbox_id,sender_session,destination_session,body,ts_dispatched,delivery_state) VALUES (?,'operator-agent@kernel','lead@xv','old protected history','2020-01-01T00:00:00Z','indeterminate')");
 db.transaction(()=>{for(let i=0;i<2005;i++)insert.run('wake-intent-history-'+i);})();
 const originalPrepare=db.prepare.bind(db),originLookups:string[]=[],bulkLookups:string[]=[];
 vi.spyOn(db,'prepare').mockImplementation(((sql:string)=>{if(sql.includes("SELECT payload FROM events WHERE type='outbox.direct_attempt'"))originLookups.push(sql);if(sql.includes('WITH origins AS MATERIALIZED'))bulkLookups.push(sql);return originalPrepare(sql);}) as typeof db.prepare);
 expect(()=>outbox.recipientAcknowledgmentContract('lead@xv','lead-g1','wake-intent-history-0')).toThrow('non-executable');expect(originLookups).toHaveLength(0);
 await f.stage();expect(f.duties()).toHaveLength(1);expect(f.duties()[0].effectId).toBe(f.reports[0].outboxId);expect(bulkLookups).toHaveLength(1);expect(originLookups.length).toBeLessThan(20);
 expect(db.prepare("SELECT count(*) n FROM outbox_entries WHERE outbox_id LIKE 'wake-intent-history-%' AND delivery_state='indeterminate'").get()).toEqual({n:2005});expect(f.reports.map(e=>outbox.getById(e.outboxId)?.deliveryState)).toEqual(['indeterminate','indeterminate']);expect(f.typed).toHaveLength(0);
});

function seedExactAckHistory(f:Awaited<ReturnType<typeof automaticAckFixture>>,adopted:boolean){
 outbox.record({outboxId:'contained-ack-history',senderSession:'reviewer@xv',destinationSession:'operator-agent@kernel',body:'Immutable non-executable UNKNOWN history'});
 const row=db.prepare("SELECT * FROM outbox_entries WHERE outbox_id='contained-ack-history'").get() as any,custody={queue:null,assignment:[],resources:[]},rowHash=historicalDigest(row),expired=f.clock-1;
 db.prepare("INSERT INTO outbox_historical_quarantines VALUES ('contained-ack-history','xv',?,'ack-history-hold','ack-history-auth',?,'held',?)").run(rowHash,expired,new Date(f.clock).toISOString());
 const receipt={kind:'historical-quarantine',rigId:'xv',operationId:'ack-history-hold',actor:'operator-agent@kernel',generation:'operator-agent-g1',lead:'lead@xv',leadGeneration:'lead-g1',deliveryConclusion:'unknown',outboxMutations:0,effects:['contained-ack-history'],admittedUntil:expired};
 db.prepare("INSERT INTO outbox_historical_operations VALUES ('xv','ack-history-hold','quarantine','immutable-request',?)").run(JSON.stringify(receipt));
 if(adopted){db.prepare("INSERT INTO queue_items(qitem_id,ts_created,ts_updated,source_session,destination_session,state,body,expires_at) VALUES ('immutable-old-recovery',?,?,'lead@xv','operator-agent@kernel','done','Preserved recovery history',?)").run(new Date(f.clock-1000).toISOString(),new Date(f.clock-1000).toISOString(),new Date(expired).toISOString());const quarantine=db.prepare("SELECT * FROM outbox_historical_quarantines WHERE outbox_id='contained-ack-history'").get(),operation=db.prepare("SELECT * FROM outbox_historical_operations WHERE operation_id='ack-history-hold'").get(),pre={outboxId:'contained-ack-history',rowHash,quarantineHash:historicalDigest(quarantine),operationHash:historicalDigest(operation)};
 db.prepare("INSERT INTO coordinator_held_history VALUES ('xv','contained-ack-history','ack-history-adopt',?,?,?,?,?,'immutable-old-recovery',?)").run(rowHash,pre.quarantineHash,pre.operationHash,historicalDigest(custody),historicalDigest(custody),JSON.stringify({kind:'coordinator-held-history-adoption.v1',actor:'operator-agent@kernel',generation:'operator-agent-g1',deliveryConclusion:'unknown',originalMutations:0,pre,postCustody:custody}));}
 expect(f.svc.isAdoptedHistoryContained('xv',row)).toBe(adopted);expect(f.svc.isAdoptedHistoryContained('other',row)).toBe(false);return row;
}
it('automatic acknowledgment preserves expired unadopted quarantine hold without renewing or acknowledging it',async()=>{
 const f=await automaticAckFixture(),original=seedExactAckHistory(f,false);await f.stage();expect(f.duties()).toHaveLength(0);expect(f.typed).toHaveLength(0);expect(db.prepare("SELECT * FROM outbox_entries WHERE outbox_id='contained-ack-history'").get()).toEqual(original);expect(f.reports.map(e=>outbox.getById(e.outboxId)?.deliveryState)).toEqual(['indeterminate','indeterminate']);
});
