import {administrativeCliEvidence} from '../src/domain/administrative-cli-evidence.js';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {createHash} from 'node:crypto';
import {createFullTestDb} from './helpers/test-app.js';
import {seed,token} from './helpers/coordinator-fixture.js';
import {digest} from '../src/domain/coordinator-authority-service.js';
import {coordinatorRoutes} from '../src/routes/coordinator.js';
import {OutboxHandler} from '../src/domain/outbox-handler.js';
import {SeatDeliveryGuard,resolveGuardTarget} from '../src/domain/seat-delivery-guard.js';
import {SessionRegistry} from '../src/domain/session-registry.js';
import {CoordinationRecoveryService} from '../src/domain/coordination-recovery-service.js';
import {SessionTransport} from '../src/domain/session-transport.js';
import {RigRepository} from '../src/domain/rig-repository.js';
import type {TmuxAdapter} from '../src/adapters/tmux.js';
import {QueueRepository} from '../src/domain/queue-repository.js';
import {EventBus} from '../src/domain/event-bus.js';
import {Hono} from 'hono';
import {queueRoutes} from '../src/routes/queue.js';
let db:ReturnType<typeof createFullTestDb>,outbox:OutboxHandler,guard:SeatDeliveryGuard,repo:QueueRepository;
beforeEach(()=>{db=createFullTestDb();seed(db);db.exec('CREATE TABLE IF NOT EXISTS seat_delivery_guards(node_id TEXT PRIMARY KEY,desired INTEGER NOT NULL,effective INTEGER NOT NULL)');outbox=new OutboxHandler(db);guard=new SeatDeliveryGuard(db,name=>resolveGuardTarget(db,name));const sessions=new SessionRegistry(db);repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>sessions.currentOccupantGenerationForSession(s)});repo.attachOutbox(outbox);});afterEach(()=>{vi.restoreAllMocks();vi.useRealTimers();db.close();});
function packet(outboxId?:string){const e=outbox.record({outboxId,senderSession:'builder@xv',destinationSession:'lead@xv',body:'valuable original message',auditPointer:'existing-immutable-pointer'});return {outboxId:e.outboxId,bodySha256:createHash('sha256').update(e.body).digest('hex'),expectedState:'pending' as const,operationId:'abandon-1',authorizationId:'auth',reason:'preserve unknown delivery and withdraw obsolete effect',evidenceRef:'native-history-inspection-1',actor:'builder@xv',generation:'builder-g1'};}
async function authorize(p:ReturnType<typeof packet>,provenance='transport:v1'){const body={kind:'outbox-abandon-authorization',outboxId:p.outboxId,bodySha256:p.bodySha256,expectedState:p.expectedState,operationId:p.operationId,senderGeneration:p.generation,reason:p.reason,evidenceRef:p.evidenceRef};await repo.create({qitemId:p.authorizationId,sourceSession:'operator-agent@kernel',destinationSession:p.actor,body:JSON.stringify(body),identityProvenance:provenance,expiresAt:new Date(Date.now()+60000).toISOString(),nudge:false});repo.claim({qitemId:p.authorizationId,destinationSession:p.actor});}
async function enableRig(){await repo.create({qitemId:'baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'coordinate',nudge:false});repo.coordinatorAuthority.enable('operator-agent@kernel','operator-agent-g1',{rigId:'xv',batonId:'baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:60000,operationId:'enable'});repo.coordinatorAuthority.acknowledge('lead@xv',token,{operationId:'ack',obligationsDigest:repo.coordinatorAuthority.reconciliationDigest('xv')});}
function issuance(p:ReturnType<typeof packet>){return {authorizationId:p.authorizationId,deadline:Date.now()+20000,contract:{kind:'outbox-abandon-authorization' as const,outboxId:p.outboxId,bodySha256:p.bodySha256,expectedState:p.expectedState,operationId:p.operationId,senderGeneration:p.generation,reason:p.reason,evidenceRef:p.evidenceRef}};}
it('native Operator issues finite administrative abandonment authorization in an enabled rig without product dispatch',async()=>{
 await enableRig();repo.coordinatorAuthority.admit('operator-agent@kernel','operator-agent-g1','xv','retained-product',{inputDigest:'input',destination:'builder@xv',bodyHash:digest('retained work'),resources:['retained-source.ts'],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});await repo.create({qitemId:'retained-product',sourceSession:'lead@xv',destinationSession:'builder@xv',body:'retained work',dispatch:{token,packageKey:'retained-product'},nudge:false});repo.claim({qitemId:'retained-product',destinationSession:'builder@xv'});
 const p=packet(),input=issuance(p),effect=outbox.getById(p.outboxId),assignments=db.prepare('SELECT * FROM coordinator_assignments').all(),resources=db.prepare('SELECT * FROM coordinator_resources').all(),original=repo.getById('retained-product');
 await expect(repo.create({qitemId:p.authorizationId,sourceSession:'operator-agent@kernel',destinationSession:p.actor,body:JSON.stringify(input.contract),expiresAt:new Date(input.deadline).toISOString(),identityProvenance:'transport:v1',nudge:false})).rejects.toThrow('Fresh worker assignments');expect(repo.getById(p.authorizationId)).toBeNull();
 const result=await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard);expect(result).toEqual({authorizationId:p.authorizationId,sender:p.actor,deadline:input.deadline});expect(await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard)).toEqual(result);expect(outbox.getById(p.outboxId)).toEqual(effect);expect(db.prepare('SELECT * FROM coordinator_assignments').all()).toEqual(assignments);expect(db.prepare('SELECT * FROM coordinator_resources').all()).toEqual(resources);expect(repo.getById('retained-product')).toEqual(original);
 await expect(repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',{...input,contract:{...input.contract,reason:'changed'}},guard)).rejects.toThrow('replay differs');
 repo.claim({qitemId:p.authorizationId,destinationSession:p.actor});expect((await outbox.abandonUncertain(p,guard)).deliveryState).toBe('retired');expect(repo.getById('retained-product')).toEqual(original);expect(db.prepare('SELECT * FROM coordinator_resources').all()).toEqual(resources);expect(db.prepare("SELECT count(*) n FROM outbox_entries WHERE outbox_id LIKE 'wake-intent-%'").get()).toEqual({n:1});
 vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(input.deadline+1);expect((await outbox.abandonUncertain(p,guard)).deliveryState).toBe('retired');expect(await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard)).toEqual(result);
});
it.each(['actor','operator-generation','sender-generation','body','extra-field','effect','wake','guarded','expiry'] as const)('native abandonment issuance refuses %s without changing effect or custody',async(kind)=>{
 await enableRig();const p=packet(kind==='wake'?'wake-intent-not-abandonable':undefined),input=issuance(p);
 if(kind==='sender-generation')input.contract.senderGeneration='old-builder';if(kind==='body')input.contract.bodySha256='0'.repeat(64);if(kind==='extra-field')(input.contract as any).grantsAuthority=true;if(kind==='effect')outbox.markDelivered(p.outboxId);if(kind==='guarded')db.prepare('UPDATE outbox_entries SET guard_binding=? WHERE outbox_id=?').run('{"nodeId":"builder@xv"}',p.outboxId);if(kind==='expiry')input.deadline=Date.now()-1;
 const before=outbox.getById(p.outboxId),queues=db.prepare('SELECT * FROM queue_items').all();await expect(repo.issueOutboxAbandonAuthorization(kind==='actor'?'lead@xv':'operator-agent@kernel',kind==='actor'?'lead-g1':kind==='operator-generation'?'old-operator':'operator-agent-g1',input,guard)).rejects.toThrow();expect(outbox.getById(p.outboxId)).toEqual(before);expect(db.prepare('SELECT * FROM queue_items').all()).toEqual(queues);expect(db.prepare("SELECT 1 FROM coordinator_operations WHERE kind='outbox-abandon-authorization'").get()).toBeUndefined();
});
it('native abandonment authorization expiry is enforced after genuine sender claim and before first disposition',async()=>{
 await enableRig();const p=packet(),input=issuance(p);await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard);repo.claim({qitemId:p.authorizationId,destinationSession:p.actor});vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(input.deadline+1);const before=outbox.getById(p.outboxId);await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('Kernel Operator');expect(outbox.getById(p.outboxId)).toEqual(before);expect(db.prepare("SELECT 1 FROM events WHERE type='outbox.uncertain_abandoned'").get()).toBeUndefined();
});
it('native issued abandonment authorization refuses a changed recipient incarnation at consumption',async()=>{
 await enableRig();const p=packet(),input=issuance(p);await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard);repo.claim({qitemId:p.authorizationId,destinationSession:p.actor});db.prepare("UPDATE occupant_tenures SET generation_uuid='lead-g2' WHERE node_id='lead@xv'").run();const before=outbox.getById(p.outboxId);await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('current native identities');expect(outbox.getById(p.outboxId)).toEqual(before);expect(db.prepare("SELECT 1 FROM events WHERE type='outbox.uncertain_abandoned'").get()).toBeUndefined();
});
function attachNativeNotificationTransport(){db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('admin-binding','builder@xv','builder@xv','%7')").run();const sent:string[]=[];repo.attachTransport({send:async(session,body,opts)=>{repo.coordinatorAuthority.assertManagedSend(opts?.actorSession,session,opts?.queueAssignmentId,{body,ids:opts?.committedOutboxIds});sent.push(body);return {ok:true,verified:true};}});return sent;}
it('fixed administrative notification reaches an existing unnotified current authorization exactly once across restart before finite expiry',async()=>{
 await enableRig();const p=packet(),input=issuance(p);const oldVersion=vi.spyOn(repo as any,'stageAbandonmentNotification').mockImplementationOnce(()=>({authorizationId:p.authorizationId,outboxId:'not-staged',deadline:input.deadline}));await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard);oldVersion.mockRestore();expect(db.prepare("SELECT 1 FROM outbox_entries WHERE outbox_id LIKE 'wake-intent-%'").get()).toBeUndefined();
 const original=outbox.getById(p.outboxId),sessions=new SessionRegistry(db);repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>sessions.currentOccupantGenerationForSession(s)});repo.attachOutbox(outbox);const sent=attachNativeNotificationTransport();
 expect(repo.waitingView(p.authorizationId)?.nextBackstop.dueAt).toBe(new Date(input.deadline).toISOString());expect(repo.waitingView(p.authorizationId)?.nextBackstop.mechanism).toContain('not-staged');const notice=await repo.notifyOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',{authorizationId:p.authorizationId},guard);expect(sent).toHaveLength(1);expect(sent[0]).toContain(p.authorizationId);expect(sent[0]).toContain('abandonContract');expect(sent[0]).toContain('rig queue outbox-abandon-uncertain');expect(sent[0]).toContain('POST /api/queue/outbox/abandon-uncertain');expect(sent[0]).toContain('handoff-and-complete this freshly claimed authorization');expect(sent[0]).toContain('--no-nudge');expect(sent[0]).not.toContain('already-owned confirmation obligation');expect(outbox.getById(notice.outboxId)?.deliveryState).toBe('delivered');expect(outbox.getById(p.outboxId)).toEqual(original);expect(repo.getById(p.authorizationId)?.state).toBe('pending');
 await repo.notifyOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',{authorizationId:p.authorizationId},guard);await repo.drainPendingWakeIntents();expect(sent).toHaveLength(1);expect(repo.waitingView(p.authorizationId)?.nextBackstop.mechanism).toContain('delivered');expect(repo.observeOutboxAbandonNotifications('xv','operator-agent-g1')[0].state).toBe('delivered-awaiting-pickup');
 repo.claim({qitemId:p.authorizationId,destinationSession:p.actor});const retirement=await outbox.abandonUncertain(p,guard);expect(retirement.deliveryState).toBe('retired');const returned=await repo.handoffAndComplete({qitemId:p.authorizationId,fromSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',toSession:'lead@xv',body:JSON.stringify(retirement),nudge:false});expect(returned.closed.state).toBe('done');expect(returned.created.body).toBe(JSON.stringify(retirement));expect(repo.observeOutboxAbandonNotifications('xv','operator-agent-g1')[0].state).toBe('abandoned-unknown-preserved');expect(db.prepare('SELECT 1 FROM coordinator_assignments').get()).toBeUndefined();expect(db.prepare('SELECT 1 FROM coordinator_resources').get()).toBeUndefined();
});
it('future native issuance automatically delivers its fixed administrative notice with exact target UNKNOWN preserved',async()=>{
 await enableRig();const p=packet(),before=outbox.getById(p.outboxId),sent=attachNativeNotificationTransport();await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',issuance(p),guard);expect(sent).toHaveLength(1);expect(outbox.getById(p.outboxId)).toEqual(before);expect(repo.getById(p.authorizationId)?.state).toBe('pending');expect(repo.waitingView(p.authorizationId)?.nextBackstop.mechanism).toContain('delivered');
});
it.each([true,false])('real SessionTransport shares registered administrative proof with guard and preserves terminal notice, successful=%s',async(successful)=>{
 await enableRig();db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('admin-real-binding','builder@xv','builder@xv','%7')").run();db.prepare("UPDATE nodes SET runtime='codex' WHERE id='builder@xv'").run();const p=packet(),input=issuance(p),before=outbox.getById(p.outboxId),typed:string[]=[],keys:string[][]=[];let pane='› ';
 const tmux={deliveryGuard:guard,probeSession:async()=>({state:'present'}),getPaneCommand:async()=> 'codex',capturePaneContent:async()=>pane,sendText:async(_target:string,body:string)=>{typed.push(body);if(successful)pane+=body;return {ok:successful};},sendKeys:async(_target:string,k:string[])=>{keys.push(k);return {ok:true};}} as unknown as TmuxAdapter;
 const transport=new SessionTransport({db,rigRepo:new RigRepository(db),sessionRegistry:new SessionRegistry(db),tmuxAdapter:tmux});repo.attachTransport(transport);await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard);const noticeId='wake-intent-outbox-abandon-notification:'+p.authorizationId;expect(typed).toHaveLength(1);expect(typed[0]).toContain('claim-exact-outbox-abandon-authorization');expect(outbox.getById(noticeId)?.deliveryState).toBe(successful?'delivered':'failed');expect(keys).toHaveLength(successful?1:0);expect(outbox.getById(p.outboxId)).toEqual(before);expect(repo.getById(p.authorizationId)?.state).toBe('pending');
 await repo.notifyOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',{authorizationId:p.authorizationId},guard);await repo.drainPendingWakeIntents();expect(typed).toHaveLength(1);expect(outbox.getById(noticeId)?.deliveryState).toBe(successful?'delivered':'failed');const raw=await transport.send('builder@xv','arbitrary text',{actorSession:'operator-agent@kernel',queueAssignmentId:p.authorizationId,committedOutboxIds:[noticeId]});expect(raw.ok).toBe(false);expect(typed).toHaveLength(1);expect(outbox.getById(p.outboxId)).toEqual(before);
});
it('administrative recovery notification preserves multiple direct audits and terminal wake uncertainty without granting product dispatch',async()=>{
 await enableRig();const p=packet(),input=issuance(p),target=outbox.getById(p.outboxId),history:string[]=[];
 for(const session of ['builder@xv','lead@xv','operator-agent@kernel'])for(let i=0;i<3;i++){
 const audit=outbox.record({outboxId:'history-direct-'+session+'-'+i,senderSession:session,destinationSession:'builder@xv',body:'preserved direct audit'});history.push(audit.outboxId);
 const terminal=outbox.record({outboxId:'wake-intent-history-'+session+'-'+i,senderSession:session,destinationSession:'builder@xv',body:'preserved unknown wake'});outbox.markIndeterminate(terminal.outboxId);history.push(terminal.outboxId);expect(outbox.claimForDelivery(terminal.outboxId)).toBe(false);
 }
 const retained=outbox.record({outboxId:'wake-intent-retained-history',senderSession:'lead@xv',destinationSession:'builder@xv',body:'preserved held input'});db.prepare("UPDATE outbox_entries SET delivery_state='retained',guard_binding=? WHERE outbox_id=?").run(JSON.stringify({nodeId:'builder@xv',session:'builder@xv',occupant:null,pane:null}),retained.outboxId);history.push(retained.outboxId);expect(outbox.claimForDelivery(retained.outboxId)).toBe(false);
 const quarantine=outbox.record({outboxId:'wake-intent-quarantined-history',senderSession:'operator-agent@kernel',destinationSession:'builder@xv',body:'preserved quarantined pending'});db.prepare("INSERT INTO outbox_historical_quarantines VALUES (?,'xv','original','history','history-auth',?,'held',datetime('now'))").run(quarantine.outboxId,Date.now()-1);history.push(quarantine.outboxId);expect(outbox.claimForDelivery(quarantine.outboxId)).toBe(false);
 expect(outbox.listPending('wake-intent-').filter(row=>history.includes(row.outboxId))).toEqual([]);const snapshots=history.map(id=>outbox.getById(id));const sent=attachNativeNotificationTransport();await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard);expect(sent).toHaveLength(1);expect(history.map(id=>outbox.getById(id))).toEqual(snapshots);expect(outbox.getById(p.outboxId)).toEqual(target);
 await expect(repo.create({sourceSession:'operator-agent@kernel',destinationSession:'builder@xv',body:'arbitrary product work',nudge:false})).rejects.toThrow('Fresh worker assignments');expect(db.prepare('SELECT 1 FROM coordinator_assignments').get()).toBeUndefined();expect(db.prepare('SELECT 1 FROM coordinator_resources').get()).toBeUndefined();repo.claim({qitemId:p.authorizationId,destinationSession:p.actor});expect((await outbox.abandonUncertain(p,guard)).deliveryState).toBe('retired');expect(history.map(id=>outbox.getById(id))).toEqual(snapshots);
});
it.each(['id','generation','expiry','effect','unrelated-pending-wake','unrelated-sending','unrelated-guarded','typing','notice-unknown','notice-sending','notice-body','recipient-generation','operator-generation'] as const)('fixed administrative notification refuses %s at staging or drain without replaying uncertainty',async(kind)=>{
 await enableRig();const p=packet(),input=issuance(p);await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard);const notificationId='wake-intent-outbox-abandon-notification:'+p.authorizationId,before=outbox.getById(p.outboxId),sent=attachNativeNotificationTransport();
 expect(()=>repo.coordinatorAuthority.assertManagedSend('operator-agent@kernel','builder@xv',p.authorizationId)).toThrow();expect(()=>repo.coordinatorAuthority.assertManagedSend('operator-agent@kernel','builder@xv',p.authorizationId,{body:'arbitrary text',ids:[notificationId]})).toThrow();expect(()=>repo.coordinatorAuthority.assertManagedSend('operator-agent@kernel','builder@xv',p.authorizationId,{body:outbox.getById(notificationId)!.body,ids:['wrong-notice']})).toThrow();
 if(kind==='id')await expect(repo.notifyOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',{authorizationId:'not-the-issued-id'},guard)).rejects.toThrow();else if(kind==='generation')db.prepare("UPDATE occupant_tenures SET generation_uuid='builder-g2' WHERE node_id='builder@xv'").run();else if(kind==='expiry'){vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(input.deadline+1);}else if(kind==='effect')outbox.markIndeterminate(p.outboxId);else if(kind.startsWith('unrelated-')){const debt=outbox.record({outboxId:kind==='unrelated-pending-wake'?'wake-intent-active-other':'active-other',senderSession:'builder@xv',destinationSession:'lead@xv',body:'other active transport'});if(kind==='unrelated-sending')db.prepare("UPDATE outbox_entries SET delivery_state='sending' WHERE outbox_id=?").run(debt.outboxId);if(kind==='unrelated-guarded')db.prepare('UPDATE outbox_entries SET guard_binding=? WHERE outbox_id=?').run(JSON.stringify({nodeId:'lead@xv',session:'lead@xv',occupant:null,pane:null}),debt.outboxId);}else if(kind==='typing')db.prepare("INSERT INTO seat_delivery_guards(node_id,desired,effective,actor,reason,changed_at) VALUES ('builder@xv',1,1,'test','typing',datetime('now'))").run();else if(kind==='notice-sending')db.prepare("UPDATE outbox_entries SET delivery_state='sending' WHERE outbox_id=?").run(notificationId);else if(kind==='notice-body')db.prepare('UPDATE outbox_entries SET body=? WHERE outbox_id=?').run('arbitrary text',notificationId);else if(kind==='recipient-generation')db.prepare("UPDATE occupant_tenures SET generation_uuid='lead-g2' WHERE node_id='lead@xv'").run();else if(kind==='operator-generation')db.prepare("UPDATE occupant_tenures SET generation_uuid='operator-agent-g2' WHERE node_id='operator-agent@kernel'").run();else outbox.markIndeterminate(notificationId);
 if(kind!=='id'){if(kind!=='notice-sending')expect(repo.validOutboxAbandonAuthorizationWake('operator-agent@kernel','builder@xv',p.authorizationId)).toBe(false);await repo.drainPendingWakeIntents();expect(sent).toHaveLength(0);expect(repo.getById(p.authorizationId)?.state).toBe('pending');if(kind!=='effect')expect(outbox.getById(p.outboxId)).toEqual(before);if(kind==='expiry'){await expect(repo.notifyOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',{authorizationId:p.authorizationId},guard)).rejects.toThrow('unexpired');expect(repo.observeOutboxAbandonNotifications('xv','operator-agent-g1')[0].reason).toBe('administrative-authorization-expired');}if(kind==='notice-sending'){expect(outbox.getById(notificationId)?.deliveryState).toBe('sending');expect(repo.observeOutboxAbandonNotifications('xv','operator-agent-g1')[0].reason).toBe('administrative-notification-sending');}if(kind==='notice-unknown'){await repo.notifyOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',{authorizationId:p.authorizationId},guard);expect(outbox.getById(notificationId)?.deliveryState).toBe('indeterminate');expect(repo.observeOutboxAbandonNotifications('xv','operator-agent-g1')[0].reason).toBe('administrative-notification-indeterminate');}}
});
it('claimed blocked administrative custody resumes through native API or closes failed after expiry before fresh authorization',async()=>{
 await enableRig();attachNativeNotificationTransport();const p=packet(),input=issuance(p),before=outbox.getById(p.outboxId);await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard);repo.claim({qitemId:p.authorizationId,destinationSession:p.actor});repo.update({qitemId:p.authorizationId,actorSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',state:'blocked',blockedOn:'exact-api-discovery'});
 const app=new Hono();app.use('*',async(c,next)=>{c.set('queueRepo' as never,repo as never);c.set('outboxHandler' as never,outbox as never);c.set('tmuxAdapter' as never,{deliveryGuard:guard} as never);await next();});app.route('/queue',queueRoutes());const headers={'Content-Type':'application/json','X-OpenRig-Session':p.actor,'X-OpenRig-Occupant-Generation':p.generation};const update=(body:unknown)=>app.request('/queue/'+p.authorizationId+'/update',{method:'POST',headers,body:JSON.stringify(body)});
 expect((await update({state:'in-progress'})).status).toBe(200);expect(repo.getById(p.authorizationId)?.state).toBe('in-progress');await expect(repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',{...input,authorizationId:'fresh-before-custody'},guard)).rejects.toThrow('still-claimed');vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(input.deadline+1);const expired=await app.request('/queue/outbox/abandon-uncertain',{method:'POST',headers,body:JSON.stringify({outboxId:p.outboxId,bodySha256:p.bodySha256,expectedState:p.expectedState,operationId:p.operationId,authorizationId:p.authorizationId,reason:p.reason,evidenceRef:p.evidenceRef})});expect(expired.status).toBe(409);expect(outbox.getById(p.outboxId)).toEqual(before);expect((await update({state:'failed',transitionNote:'Finite authorization expired; UNKNOWN remains preserved'})).status).toBe(200);const fresh={...input,authorizationId:'fresh-after-own-failure',deadline:Date.now()+20000};await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',fresh,guard);expect(repo.getById(p.authorizationId)?.state).toBe('failed');expect(repo.getById(fresh.authorizationId)?.state).toBe('pending');expect(outbox.getById(p.outboxId)).toEqual(before);
});
it('native abandonment issuance waits under lifecycle and rejects identity or effect drift',async()=>{
 await enableRig();const p=packet(),input=issuance(p);let release!:()=>void,entered!:()=>void;const ready=new Promise<void>(r=>entered=r),held=guard.lifecycle(['builder@xv'],async()=>{entered();await new Promise<void>(r=>release=r);});await ready;const pending=repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard);outbox.markFailed(p.outboxId);release();await held;await expect(pending).rejects.toThrow('effect body/state changed');expect(repo.getById(p.authorizationId)).toBeNull();
});
it('native abandonment issuance API derives current Operator identity and rejects caller-forged body identity',async()=>{
 await enableRig();const p=packet(),input=issuance(p),app=new Hono();app.use('*',async(c,next)=>{c.set('queueRepo' as never,repo as never);c.set('tmuxAdapter' as never,{deliveryGuard:guard} as never);await next();});app.route('/coordinator',coordinatorRoutes({bearerToken:'native-test-token'}));
 const call=(actor:string,generation:string,body:unknown,authorized=true)=>app.request('/coordinator/outbox-abandon-authorize',{method:'POST',headers:{'Content-Type':'application/json','X-OpenRig-Session':actor,'X-OpenRig-Occupant-Generation':generation,...(authorized?{Authorization:'Bearer native-test-token'}:{})},body:JSON.stringify(body)});
 expect((await call('operator-agent@kernel','operator-agent-g1',input,false)).status).toBe(401);expect((await call('builder@xv','builder-g1',input)).status).toBe(409);expect((await call('operator-agent@kernel','operator-agent-g1',{...input,actor:'forged'})).status).toBe(409);const valid=await call('operator-agent@kernel','operator-agent-g1',input);expect(valid.status).toBe(200);expect(await valid.json()).toMatchObject({authorizationId:p.authorizationId,sender:p.actor});
});
it('explicit abandonment retains original payload/audit/custody and records uncertainty, never delivery',async()=>{const p=packet();await authorize(p);const before=outbox.getById(p.outboxId)!;const queue=db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all(),sessions=db.prepare('SELECT * FROM sessions').all(),tenures=db.prepare('SELECT * FROM occupant_tenures').all();const result=await outbox.abandonUncertain(p,guard);expect(result).toMatchObject({...before,deliveryState:'retired',retiredAt:expect.any(String),retiredBy:p.actor,retirementReason:`Uncertain effect explicitly abandoned: ${p.reason}`});expect(result.retiredAt).toBeTruthy();expect(result.deliveredAt).toBeNull();expect(db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all()).toEqual(queue);expect(db.prepare('SELECT * FROM sessions').all()).toEqual(sessions);expect(db.prepare('SELECT * FROM occupant_tenures').all()).toEqual(tenures);const audit=JSON.parse((db.prepare("SELECT payload FROM events WHERE type='outbox.uncertain_abandoned'").get() as {payload:string}).payload);expect(audit).toMatchObject({originalState:'pending',deliveryConclusion:'unknown',originalAuditPointer:before.auditPointer,evidenceRef:p.evidenceRef});repo.update({qitemId:'auth',actorSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'});expect(await outbox.abandonUncertain(p,guard)).toEqual(result);expect(db.prepare("SELECT count(*) n FROM events WHERE type='outbox.uncertain_abandoned'").get()).toEqual({n:1});});
it('requires current exact Operator transport authorization claimed by sender',async()=>{const p=packet();await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('Kernel Operator');await authorize(p,'claimed:v1');await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('Kernel Operator');expect(outbox.getById(p.outboxId)?.deliveryState).toBe('pending');});
it('refuses unknown or retired sender generation and stale Operator authorization',async()=>{const p=packet();await authorize(p);await expect(outbox.abandonUncertain({...p,generation:'retired'},guard)).rejects.toThrow('Current local');db.prepare("UPDATE occupant_tenures SET generation_uuid='operator-g2' WHERE node_id='operator-agent@kernel'").run();await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('Kernel Operator');expect(outbox.getById(p.outboxId)?.deliveryState).toBe('pending');});
it('waits under lifecycle and refuses concurrent effect drift',async()=>{const p=packet();await authorize(p);let release!:()=>void,entered!:()=>void;const ready=new Promise<void>(r=>entered=r);const held=guard.lifecycle(['builder@xv'],async()=>{entered();await new Promise<void>(r=>release=r);});await ready;let settled=false;const selection=outbox.abandonUncertain(p,guard).finally(()=>settled=true);await new Promise(r=>setTimeout(r,10));expect(settled).toBe(false);outbox.markFailed(p.outboxId);release();await held;await expect(selection).rejects.toThrow('Frozen effect');expect(outbox.getById(p.outboxId)?.deliveryState).toBe('failed');});
it('rejects changed replay and new sender occupant',async()=>{const p=packet();await authorize(p);await outbox.abandonUncertain(p,guard);await expect(outbox.abandonUncertain({...p,reason:'changed'},guard)).rejects.toThrow('changed contract');db.prepare("UPDATE occupant_tenures SET generation_uuid='builder-g2' WHERE node_id='builder@xv'").run();await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('Current local');await expect(outbox.abandonUncertain({...p,generation:'builder-g2'},guard)).rejects.toThrow('changed contract');});
it('refuses executable wakes, wrong body, missing guards and preexisting terminal outcomes',async()=>{const wake=packet('wake-intent-preserve');await expect(outbox.abandonUncertain(wake,guard)).rejects.toThrow('non-executable');const p=packet();await authorize(p);await expect(outbox.abandonUncertain(p,undefined)).rejects.toThrow('lifecycle');await expect(outbox.abandonUncertain({...p,bodySha256:'0'.repeat(64)},guard)).rejects.toThrow('Frozen effect');outbox.markDelivered(p.outboxId);await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('Frozen effect');expect(outbox.getById(p.outboxId)?.deliveryState).toBe('delivered');});
it('API derives sender and generation and returns the explicit uncertainty disposition',async()=>{const p=packet();await authorize(p);const app=new Hono();app.use('*',async(c,next)=>{c.set('outboxHandler' as never,outbox as never);c.set('tmuxAdapter' as never,{deliveryGuard:guard} as never);await next();});app.route('/queue',queueRoutes());const send=(headers:Record<string,string>)=>app.request('/queue/outbox/abandon-uncertain',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({...p,actor:'forged'})});expect((await send({})).status).toBe(400);const valid=await send({'X-OpenRig-Session':p.actor,'X-OpenRig-Occupant-Generation':p.generation});expect(valid.status).toBe(200);expect(await valid.json()).toMatchObject({deliveryState:'retired',retiredBy:p.actor,deliveredAt:null});});

it('audit failure rolls back disposition atomically',async()=>{const p=packet();await authorize(p);const before=outbox.getById(p.outboxId);vi.spyOn(EventBus.prototype,'persistWithinTransaction').mockImplementationOnce(()=>{throw new Error('audit unavailable')});await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('audit unavailable');expect(outbox.getById(p.outboxId)).toEqual(before);});
it('indeterminate effect preserves its original uncertain outcome and guard/foreign effects refuse',async()=>{const p=packet();outbox.markIndeterminate(p.outboxId);const selected={...p,expectedState:'indeterminate' as const};await authorize(selected as ReturnType<typeof packet>);expect((await outbox.abandonUncertain(selected,guard)).deliveryState).toBe('retired');const proof=JSON.parse((db.prepare("SELECT payload FROM events WHERE type='outbox.uncertain_abandoned'").get() as {payload:string}).payload);expect(proof).toMatchObject({originalState:'indeterminate',deliveryConclusion:'unknown'});const q=packet();db.prepare("UPDATE outbox_entries SET guard_binding=? WHERE outbox_id=?").run(JSON.stringify({nodeId:'builder@xv',session:'builder@xv',occupant:'builder-g1',pane:'%9'}),q.outboxId);await expect(outbox.abandonUncertain(q,guard)).rejects.toThrow('unguarded');});
it.each(['active','expired','observer-active','observer-expired','delivery-generation','proof-body','phase-pending','phase-sending','phase-unknown','unknown','generation','body','notice-expiry','sending'] as const)('real SessionTransport once-only administrative continuation preserves exact custody and UNKNOWN: %s',async(kind)=>{
 await enableRig();db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('continuation-binding','builder@xv','builder@xv','%7')").run();db.prepare("UPDATE nodes SET runtime='codex' WHERE id='builder@xv'").run();const typed:string[]=[];let pane='› ';
 const tmux={deliveryGuard:guard,probeSession:async()=>({state:'present'}),getPaneCommand:async()=> 'codex',capturePaneContent:async()=>pane,sendText:async(_target:string,body:string)=>{typed.push(body);pane+=body;return {ok:true};},sendKeys:async()=>({ok:true})} as unknown as TmuxAdapter;
 const transport=new SessionTransport({db,rigRepo:new RigRepository(db),sessionRegistry:new SessionRegistry(db),tmuxAdapter:tmux});repo.attachTransport(transport);const p=packet(),input=issuance(p),target=outbox.getById(p.outboxId);await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard);repo.claim({qitemId:p.authorizationId,destinationSession:p.actor});repo.update({qitemId:p.authorizationId,actorSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',state:'blocked',blockedOn:'consumer-cli-discovery'});expect(()=>repo.update({qitemId:p.authorizationId,actorSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'})).toThrow('UNKNOWN retirement receipt');await expect(repo.handoffAndComplete({qitemId:p.authorizationId,fromSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',toSession:'lead@xv',body:'prose complete',nudge:false})).rejects.toThrow('UNKNOWN retirement receipt');const originalNotice=outbox.getById('wake-intent-outbox-abandon-notification:'+p.authorizationId),originalBody=repo.getById(p.authorizationId)!.body;
 if(kind.endsWith('expired')&&kind!=='notice-expiry'){vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(input.deadline+1);}
 if(kind==='generation')db.prepare("UPDATE occupant_tenures SET generation_uuid='builder-g2' WHERE node_id='builder@xv'").run();
 if(kind==='body')db.prepare("UPDATE queue_items SET body='changed' WHERE qitem_id=?").run(p.authorizationId);
 if(kind==='sending'){const debt=outbox.record({outboxId:'wake-intent-active-unrelated',senderSession:p.actor,destinationSession:'lead@xv',body:'active'});outbox.claimForDelivery(debt.outboxId);}
 const c={authorizationId:p.authorizationId,deadline:kind.endsWith('expired')?Date.now()+20000:input.deadline};
 if(['generation','body','sending'].includes(kind)){await expect(repo.continueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',c,guard)).rejects.toThrow('protected');expect(typed).toHaveLength(1);expect(outbox.getById(p.outboxId)).toEqual(target);return;}
 const drain=['unknown','notice-expiry','delivery-generation','proof-body','phase-pending','phase-sending','phase-unknown'].includes(kind)?vi.spyOn(repo,'drainPendingWakeIntents').mockResolvedValueOnce(undefined):null;
 let proof:{proofId:string;outboxId:string;deadline:number;mode:string};
 if(kind.startsWith('observer')){const svc=new CoordinationRecoveryService(repo,()=>null);repo.coordinatorAuthority.coordinationRecovery=svc;const tasks=['observer-task','observer-backup'].map((key,i)=>({key,packageKey:key,owner:i?'architect@xv':'reviewer@xv',action:'Finite independent work',body:key,deadline:Date.now()+60000,predecessors:[],...(i?{recoveryFor:'observer-task'}:{}),admission:{generation:i?'architect-g1':'reviewer-g1',configurationDigest:svc.configurationDigest(i?'architect@xv':'reviewer@xv')!,qualificationRef:'actual-fixture-qualification',capacityRef:'actual-fixture-capacity',effortRef:'actual-fixture-effort',validUntil:Date.now()+60000}}));for(const t of tasks)repo.coordinatorAuthority.admit('operator-agent@kernel','operator-agent-g1','xv',t.packageKey,{inputDigest:digest(t.key),destination:t.owner,bodyHash:digest(t.body),resources:[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});svc.configure('operator-agent@kernel','operator-agent-g1',{rigId:'xv',revision:'observer-plan',operatorGeneration:'operator-agent-g1',stallMs:10000,allowIdlePeerTransfer:true,tasks});db.prepare("INSERT INTO watchdog_jobs(job_id,target_session,policy,interval_seconds,spec_yaml,state,registered_by_session,registered_at,registered_by_generation_uuid) VALUES ('actual-observer','operator-agent@kernel','coordinator-continuity',1,'context: {}','active','operator-agent@kernel',?,'operator-agent-g1')").run(new Date().toISOString());await repo.coordinatorAuthority.resumeAdministrativeDuties!('xv','wrong-job');expect(typed).toHaveLength(1);await repo.coordinatorAuthority.resumeAdministrativeDuties!('xv','actual-observer');const row=db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='outbox-abandon-continuation'").get() as {receipt:string};const saved=JSON.parse(row.receipt);proof={proofId:saved.proofId,outboxId:saved.outboxId,deadline:saved.deadline,mode:saved.mode};c.deadline=proof.deadline;await repo.coordinatorAuthority.resumeAdministrativeDuties!('xv','actual-observer');}
 else proof=await repo.continueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',c,guard);drain?.mockRestore();expect(outbox.getById(p.outboxId)).toEqual(target);expect(outbox.getById(originalNotice!.outboxId)).toEqual(originalNotice);expect(repo.getById(p.authorizationId)!.body).toBe(originalBody);
 if(kind.startsWith('phase-')){if(kind==='phase-sending')outbox.claimForDelivery(proof.outboxId);if(kind==='phase-unknown')outbox.markIndeterminate(proof.outboxId);vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(input.deadline+1);const old=outbox.getById(proof.outboxId),failure={authorizationId:p.authorizationId,deadline:Date.now()+20000};await expect(repo.continueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',failure,guard)).rejects.toThrow('protected');expect(outbox.getById(proof.outboxId)).toEqual(old);expect(typed).toHaveLength(1);await repo.drainPendingWakeIntents();if(kind==='phase-pending'){expect(outbox.getById(proof.outboxId)?.deliveryState).toBe('failed');const failureProof=await repo.continueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',failure,guard);expect(failureProof.mode).toBe('failure-only');expect(typed).toHaveLength(2);expect(typed[1]).toContain('fail-expired-exact');}else {await expect(repo.continueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',failure,guard)).rejects.toThrow('protected');expect(outbox.getById(proof.outboxId)).toEqual(old);expect(typed).toHaveLength(1);}expect(outbox.getById(p.outboxId)).toEqual(target);return;}
 if(kind==='proof-body'){expect((await transport.send(p.actor,'arbitrary text',{actorSession:'operator-agent@kernel',queueAssignmentId:proof.proofId,committedOutboxIds:[proof.outboxId]})).ok).toBe(false);expect(typed).toHaveLength(1);await repo.drainPendingWakeIntents();}
 if(kind==='delivery-generation')db.prepare("UPDATE occupant_tenures SET generation_uuid='builder-g2' WHERE node_id='builder@xv'").run();
 if(kind==='unknown')outbox.markIndeterminate(proof.outboxId);if(kind==='notice-expiry'){vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(c.deadline+1);}
 if(['unknown','notice-expiry','delivery-generation'].includes(kind)){await repo.drainPendingWakeIntents();expect(typed).toHaveLength(1);expect(outbox.getById(proof.outboxId)?.deliveryState).toBe(kind==='unknown'?'indeterminate':'failed');return;}
 expect(repo.waitingView(p.authorizationId)?.deadlineAt).toBe(new Date(input.deadline).toISOString());expect(repo.waitingView(p.authorizationId)?.nextBackstop.dueAt).toBe(new Date(proof.deadline).toISOString());expect(repo.observeOutboxAbandonNotifications('xv','operator-agent-g1')[0].state).toBe(kind.endsWith('expired')?'awaiting-own-expiry-failure':'blocked-current-claim');
 expect(typed).toHaveLength(2);expect(outbox.getById(proof.outboxId)?.deliveryState).toBe('delivered');expect(await repo.continueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',c,guard)).toEqual(proof);await repo.drainPendingWakeIntents();expect(typed).toHaveLength(2);
 expect((await transport.send(p.actor,'arbitrary text',{actorSession:'operator-agent@kernel',queueAssignmentId:proof.proofId,committedOutboxIds:[proof.outboxId]})).ok).toBe(false);
 if(kind.endsWith('expired')){expect(typed[1]).toContain('fail-expired-exact');expect(typed[1]).not.toContain('abandonContract');await expect(outbox.abandonUncertain(p,guard)).rejects.toThrow('Kernel Operator');repo.update({qitemId:p.authorizationId,actorSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',state:'failed',transitionNote:'Expired administrative authority; UNKNOWN preserved'});expect(outbox.getById(p.outboxId)).toEqual(target);}
 else {expect(typed[1]).toContain('rig queue outbox-abandon-uncertain');repo.update({qitemId:p.authorizationId,actorSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',state:'in-progress'});const retirement=await outbox.abandonUncertain(p,guard);const returned=await repo.handoffAndComplete({qitemId:p.authorizationId,fromSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',toSession:'lead@xv',body:JSON.stringify(retirement),nudge:false});expect(returned.closed.state).toBe('done');expect(retirement.deliveryState).toBe('retired');}
});

it.each(['operator','wrong-seat','replacement','stale-header','missing-native','missing-generation'] as const)('administrative custody closure refuses %s before updates/handoff and only authentic claimant failure permits fresh issuance',async(kind)=>{
 await enableRig();attachNativeNotificationTransport();const p=packet(),input=issuance(p);await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard);repo.claim({qitemId:p.authorizationId,destinationSession:p.actor});vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(input.deadline+1);const original=repo.getById(p.authorizationId),target=outbox.getById(p.outboxId),queues=db.prepare('SELECT * FROM queue_items').all();
 const actor=kind==='operator'?'operator-agent@kernel':kind==='wrong-seat'?'lead@xv':p.actor,generation=kind==='operator'?'operator-agent-g1':kind==='wrong-seat'?'lead-g1':kind==='replacement'?'builder-g2':kind==='stale-header'?'builder-stale':kind==='missing-generation'?undefined:p.generation,provenance=kind==='missing-native'?undefined:'transport:v1';if(kind==='replacement')db.prepare("UPDATE occupant_tenures SET generation_uuid='builder-g2' WHERE node_id='builder@xv'").run();
 for(const state of ['failed','canceled','done'] as const)expect(()=>repo.update({qitemId:p.authorizationId,actorSession:actor,actorGeneration:generation,identityProvenance:provenance,state,closureReason:'no-follow-on'})).toThrow('original claimed sender');
 for(const method of ['handoff','handoffAndComplete'] as const)await expect(repo[method]({qitemId:p.authorizationId,fromSession:actor,actorGeneration:generation,identityProvenance:provenance,toSession:'lead@xv',body:'prose',nudge:false})).rejects.toThrow('original claimed sender');
 expect(()=>repo.closeCrossHostHandoffSource({qitemId:p.authorizationId,fromSession:actor,actorGeneration:generation,identityProvenance:provenance,toSession:'lead@xv',closureTarget:'remote-receipt@remote',terminalState:'done'})).toThrow('original claimed sender');
 expect(()=>repo.unclaim(p.authorizationId,actor,'manual',provenance)).toThrow('cannot be unclaimed');expect(db.prepare('SELECT * FROM queue_items').all()).toEqual(queues);expect(repo.getById(p.authorizationId)).toEqual(original);expect(outbox.getById(p.outboxId)).toEqual(target);
 const app=new Hono();app.use('*',async(c,next)=>{c.set('queueRepo' as never,repo as never);await next();});app.route('/queue',queueRoutes());const response=await app.request('/queue/'+p.authorizationId+'/update',{method:'POST',headers:{'Content-Type':'application/json',...(kind==='missing-native'?{}:{'X-OpenRig-Session':actor}),...(generation?{'X-OpenRig-Occupant-Generation':generation}:{})},body:JSON.stringify({actorSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',state:'failed'})});expect(response.status).not.toBe(200);expect(repo.getById(p.authorizationId)).toEqual(original);
 if(kind==='replacement')return;await expect(repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',{...input,authorizationId:'new-custody',deadline:Date.now()+20000},guard)).rejects.toThrow('still-claimed');const native=await app.request('/queue/'+p.authorizationId+'/update',{method:'POST',headers:{'Content-Type':'application/json','X-OpenRig-Session':p.actor,'X-OpenRig-Occupant-Generation':p.generation},body:JSON.stringify({state:'failed',transitionNote:'Exact claimant expiry; original UNKNOWN retained'})});expect(native.status).toBe(200);expect(repo.getById(p.authorizationId)?.state).toBe('failed');expect(outbox.getById(p.outboxId)).toEqual(target);await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',{...input,authorizationId:'new-custody',deadline:Date.now()+20000},guard);expect(repo.getById('new-custody')?.state).toBe('pending');
});
it.each(['native','observer','wrong-actor','generation','stale-cli','wrong-cli','collision','expiry','no-ack','unknown-prior','sending-prior','retained-prior','unknown-new','cas-generation','notice-expiry'] as const)('current evidence refresh uses actual SessionTransport and original finite custody: %s',async(kind)=>{
 await enableRig();vi.useFakeTimers({toFake:['Date']});let clock=Date.now();db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('evidence-binding','builder@xv','builder@xv','%7')").run();db.prepare("UPDATE nodes SET runtime='codex' WHERE id='builder@xv'").run();let pane='› ';const typed:string[]=[];const tmux={deliveryGuard:guard,probeSession:async()=>({state:'present'}),getPaneCommand:async()=> 'codex',capturePaneContent:async()=>pane,sendText:async(_target:string,body:string)=>{typed.push(body);pane+=body;return {ok:true};},sendKeys:async()=>({ok:true})} as unknown as TmuxAdapter;const transport=new SessionTransport({db,rigRepo:new RigRepository(db),sessionRegistry:new SessionRegistry(db),tmuxAdapter:tmux});repo.attachTransport(transport);
 const p=packet(),input={...issuance(p),deadline:clock+600000},target=outbox.getById(p.outboxId);await repo.issueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',input,guard);repo.claim({qitemId:p.authorizationId,destinationSession:p.actor});repo.update({qitemId:p.authorizationId,actorSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',state:'blocked',blockedOn:'stale-predeployment-cli-inventory'});const prior=await repo.continueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',{authorizationId:p.authorizationId,deadline:input.deadline},guard);expect(typed).toHaveLength(2);const priorNotice=outbox.getById(prior.outboxId),auth=repo.getById(p.authorizationId)!;
 clock+=1000;vi.setSystemTime(clock);if(kind!=='no-ack')repo.update({qitemId:p.authorizationId,actorSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',transitionNote:'Consume continuation read; actual CLI inventory remains unresolved'});if(kind==='observer')repo.update({qitemId:p.authorizationId,actorSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',state:'in-progress',transitionNote:'Same claim resumed; no actual target API action'});
 const cli=administrativeCliEvidence();repo.update({qitemId:p.authorizationId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',transitionNote:cli.cliPath+' queue outbox-abandon-uncertain --help: verified deployed bytes; predeployment inventory invalid'});const correction=(db.prepare('SELECT transition_id FROM queue_transitions WHERE qitem_id=? ORDER BY transition_id DESC LIMIT 1').get(p.authorizationId) as {transition_id:number}).transition_id,c={authorizationId:p.authorizationId,evidenceTransitionId:correction,...cli};
 if(kind==='generation')db.prepare("UPDATE occupant_tenures SET generation_uuid='builder-g2' WHERE node_id='builder@xv'").run();if(kind==='stale-cli')c.cliSha256='0'.repeat(64);if(kind==='expiry')vi.setSystemTime(input.deadline+1);if(['unknown-prior','sending-prior','retained-prior'].includes(kind))db.prepare('UPDATE outbox_entries SET delivery_state=? WHERE outbox_id=?').run(kind==='unknown-prior'?'indeterminate':kind==='sending-prior'?'sending':'retained',prior.outboxId);if(kind==='wrong-cli')c.cliPath=process.execPath;if(kind==='collision'){const proofId='outbox-abandon-continuation:'+p.authorizationId+':current-evidence:'+createHash('sha256').update(JSON.stringify(cli)).digest('hex');outbox.record({outboxId:'wake-intent-'+proofId,senderSession:'operator-agent@kernel',destinationSession:p.actor,body:'arbitrary collision text',auditPointer:p.authorizationId,tags:['queue:outbox-abandon-continuation',proofId,'queue:recipient-generation:'+p.generation],identityProvenance:'transport:v1'});}
 if(['wrong-actor','generation','stale-cli','wrong-cli','collision','expiry','no-ack','unknown-prior','sending-prior','retained-prior'].includes(kind)){await expect(repo.registerOutboxAbandonEvidence(kind==='wrong-actor'?'lead@xv':'operator-agent@kernel',kind==='wrong-actor'?'lead-g1':'operator-agent-g1',c,guard)).rejects.toThrow();expect(typed).toHaveLength(2);expect(outbox.getById(p.outboxId)).toEqual(target);expect(db.prepare("SELECT 1 FROM coordinator_operations WHERE kind='outbox-abandon-current-evidence'").get()).toBeUndefined();return;}
 const drain=['unknown-new','cas-generation','notice-expiry'].includes(kind)?vi.spyOn(repo,'drainPendingWakeIntents').mockResolvedValueOnce(undefined):null;const registered=await repo.registerOutboxAbandonEvidence('operator-agent@kernel','operator-agent-g1',c,guard);drain?.mockRestore();const noticeId='wake-intent-'+registered.proofId;
 if(kind==='observer'){expect(registered.noticeState).toBe('not-staged');expect(typed).toHaveLength(2);clock+=181000;vi.setSystemTime(clock);expect(repo.getById(p.authorizationId)?.pickup?.state).toBe('stalled-after-claim');const svc=new CoordinationRecoveryService(repo,()=>null);repo.coordinatorAuthority.coordinationRecovery=svc;const tasks=['evidence-task','evidence-backup'].map((key,i)=>({key,packageKey:key,owner:i?'architect@xv':'reviewer@xv',action:'Finite independent scope',body:key,deadline:clock+60000,predecessors:[],...(i?{recoveryFor:'evidence-task'}:{}),admission:{generation:i?'architect-g1':'reviewer-g1',configurationDigest:svc.configurationDigest(i?'architect@xv':'reviewer@xv')!,qualificationRef:'actual-fixture',capacityRef:'actual-fixture',effortRef:'actual-fixture',validUntil:clock+60000}}));for(const t of tasks)repo.coordinatorAuthority.admit('operator-agent@kernel','operator-agent-g1','xv',t.packageKey,{inputDigest:digest(t.key),destination:t.owner,bodyHash:digest(t.body),resources:[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});svc.configure('operator-agent@kernel','operator-agent-g1',{rigId:'xv',revision:'evidence-plan',operatorGeneration:'operator-agent-g1',stallMs:10000,allowIdlePeerTransfer:true,tasks});db.prepare("INSERT INTO watchdog_jobs(job_id,target_session,policy,interval_seconds,spec_yaml,state,registered_by_session,registered_at,registered_by_generation_uuid) VALUES ('evidence-observer','operator-agent@kernel','coordinator-continuity',1,'context: {}','active','operator-agent@kernel',?,'operator-agent-g1')").run(new Date().toISOString());await repo.coordinatorAuthority.resumeAdministrativeDuties!('xv','wrong-observer');expect(outbox.getById(noticeId)).toBeNull();await repo.coordinatorAuthority.resumeAdministrativeDuties!('xv','evidence-observer');await repo.drainPendingWakeIntents();await repo.coordinatorAuthority.resumeAdministrativeDuties!('xv','evidence-observer');}
 if(kind==='unknown-new'||kind==='cas-generation'||kind==='notice-expiry'){const raw=await transport.send(p.actor,'arbitrary refreshed text',{actorSession:'operator-agent@kernel',queueAssignmentId:registered.proofId,committedOutboxIds:[noticeId]});expect(raw.ok).toBe(false);if(kind==='unknown-new')outbox.markIndeterminate(noticeId);else if(kind==='cas-generation')db.prepare("UPDATE occupant_tenures SET generation_uuid='builder-g2' WHERE node_id='builder@xv'").run();else vi.setSystemTime(input.deadline+1);await repo.drainPendingWakeIntents();await repo.registerOutboxAbandonEvidence('operator-agent@kernel','operator-agent-g1',c,guard);expect(typed).toHaveLength(2);expect(outbox.getById(noticeId)?.deliveryState).toBe(kind==='unknown-new'?'indeterminate':'failed');if(kind==='unknown-new'){vi.setSystemTime(input.deadline+1);await expect(repo.continueOutboxAbandonAuthorization('operator-agent@kernel','operator-agent-g1',{authorizationId:p.authorizationId,deadline:Date.now()+20000},guard)).rejects.toThrow('protected');}expect(outbox.getById(p.outboxId)).toEqual(target);return;}
 expect(typed).toHaveLength(3);expect(typed[2]).toContain('predeployment CLI inventory');expect(typed[2]).toContain(cli.cliPath);expect(typed[2]).toContain('/api/queue/outbox/abandon-uncertain');expect(outbox.getById(noticeId)?.deliveryState).toBe('delivered');expect(outbox.getById(prior.outboxId)).toEqual(priorNotice);expect(repo.getById(p.authorizationId)!.expiresAt).toBe(auth.expiresAt);expect(repo.getById(p.authorizationId)!.body).toBe(auth.body);expect(outbox.getById(p.outboxId)).toEqual(target);await repo.registerOutboxAbandonEvidence('operator-agent@kernel','operator-agent-g1',c,guard);await repo.drainPendingWakeIntents();expect(typed).toHaveLength(3);await expect(repo.registerOutboxAbandonEvidence('operator-agent@kernel','operator-agent-g1',{...c,evidenceTransitionId:correction+1},guard)).rejects.toThrow('immutable revision');repo.update({qitemId:p.authorizationId,actorSession:p.actor,actorGeneration:p.generation,identityProvenance:'transport:v1',state:'in-progress'});const actual=await outbox.abandonUncertain(p,guard);expect(actual.deliveryState).toBe('retired');
});
