import {beforeEach,afterEach,it,expect} from 'vitest';
import {Hono} from 'hono';
import {createHash} from 'node:crypto';
import {createFullTestDb} from './helpers/test-app.js';
import {OutboxHandler} from '../src/domain/outbox-handler.js';
import {QueueRepository} from '../src/domain/queue-repository.js';
import {EventBus} from '../src/domain/event-bus.js';
import {queueRoutes} from '../src/routes/queue.js';
import {transportRoutes} from '../src/routes/transport.js';
import {seed} from './helpers/coordinator-fixture.js';
let db:ReturnType<typeof createFullTestDb>,outbox:OutboxHandler;
beforeEach(()=>{db=createFullTestDb();seed(db);outbox=new OutboxHandler(db);});afterEach(()=>db.close());
it.each([
 [{ok:true,verified:true,outcome:'delivered'},'delivered'],
 [{ok:false,reason:'send_failed',outcome:'failed'},'failed'],
 [{ok:true,verified:false,outcome:'rendered-unconfirmed'},'indeterminate'],
 [{ok:true},'indeterminate'],
])('settles direct attempt according to actual result %j',async(result,state)=>{
 const app=new Hono();app.use('*',async(c,next)=>{c.set('outboxHandler' as never,outbox as never);c.set('sessionTransport' as never,{resolveSessions:async()=>({ok:true,sessions:[]}),send:async()=>({...result,sessionName:'lead@xv'})} as never);await next();});app.route('/transport',transportRoutes());
 const response=await app.request('/transport/send',{method:'POST',headers:{'Content-Type':'application/json','X-OpenRig-Session':'builder@xv'},body:JSON.stringify({session:'lead@xv',text:'actual message'})});expect(response.status).toBe(state==='failed'?502:200);expect(outbox.listForSender('builder@xv')[0]).toMatchObject({deliveryState:state});
});
function effect(outcome:'indeterminate'|'failed'='indeterminate'){return outbox.recordDirectAttempt({senderSession:'builder@xv',destinationSession:'lead@xv',body:'actual original message',auditPointer:'original-pointer'},outcome);}
function ack(id:string,patch:Record<string,unknown>={}){db.prepare("INSERT INTO queue_items(qitem_id,ts_created,ts_updated,source_session,destination_session,state,body,minting_generation_uuid) VALUES ('receipt',?,?,?,'builder@xv','pending',?,'lead-g1')").run(new Date(Date.now()+100).toISOString(),new Date().toISOString(),'lead@xv',JSON.stringify({kind:'outbox-delivery-ack',outboxId:id,bodySha256:createHash('sha256').update('actual original message').digest('hex'),...patch}));db.prepare("INSERT INTO queue_transitions(qitem_id,ts,state,transition_note,actor_session,identity_provenance) VALUES ('receipt',?,'pending','created','lead@xv','transport:v1')").run(new Date().toISOString());}
const reconcile=(id:string)=>outbox.reconcileRecipientDelivery({outboxId:id,receiptId:'receipt',actor:'lead@xv',generation:'lead-g1',reason:'verified actual recipient receipt'});
it('reconciles exact recipient receipt atomically without queue mutation and preserves prior pointer',()=>{const e=effect();ack(e.outboxId);const before=db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all();expect(reconcile(e.outboxId).deliveryState).toBe('delivered');expect(db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all()).toEqual(before);expect(JSON.parse(outbox.getById(e.outboxId)!.auditPointer!)).toMatchObject({receiptId:'receipt',priorAuditPointer:'original-pointer',generation:'lead-g1'});expect(reconcile(e.outboxId).deliveryState).toBe('delivered');});
it('rejects unrelated or missing ack, retired generation and executable wake intents',()=>{const e=effect();expect(()=>reconcile(e.outboxId)).toThrow('managed transport');ack(e.outboxId,{bodySha256:'wrong'});expect(()=>reconcile(e.outboxId)).toThrow('acknowledgment');db.prepare("UPDATE queue_items SET body=? WHERE qitem_id='receipt'").run(JSON.stringify({kind:'outbox-delivery-ack',outboxId:e.outboxId,bodySha256:createHash('sha256').update(e.body).digest('hex')}));db.prepare("UPDATE occupant_tenures SET generation_uuid='lead-g2' WHERE node_id='lead@xv'").run();expect(()=>reconcile(e.outboxId)).toThrow('acknowledgment');expect(outbox.getById(e.outboxId)?.deliveryState).toBe('indeterminate');const wake=outbox.record({outboxId:'wake-intent-probe',senderSession:'builder@xv',destinationSession:'lead@xv',body:e.body});expect(()=>reconcile(wake.outboxId)).toThrow('non-executable');});
it('allows acknowledged indeterminate direct effect but refuses failed outcome',()=>{const e=effect();ack(e.outboxId);outbox.markIndeterminate(e.outboxId);expect(reconcile(e.outboxId).deliveryState).toBe('delivered');const failed=effect('failed');expect(()=>reconcile(failed.outboxId)).toThrow();expect(outbox.getById(failed.outboxId)?.deliveryState).toBe('failed');});

it('supported API requires recipient generation and exact durable ack; body actor is ignored',async()=>{const e=effect();ack(e.outboxId);const app=new Hono();app.use('*',async(c,next)=>{c.set('outboxHandler' as never,outbox as never);await next();});app.route('/queue',queueRoutes());const body=JSON.stringify({outboxId:e.outboxId,receiptId:'receipt',reason:'recipient inspected message',actor:'forged'});const send=(headers:Record<string,string>)=>app.request('/queue/outbox/reconcile-delivery',{method:'POST',headers:{'Content-Type':'application/json',...headers},body});expect((await send({})).status).toBe(400);expect((await send({'X-OpenRig-Session':'builder@xv','X-OpenRig-Occupant-Generation':'builder-g1'})).status).toBe(409);const valid=await send({'X-OpenRig-Session':'lead@xv','X-OpenRig-Occupant-Generation':'lead-g1'});expect(valid.status).toBe(200);expect(await valid.json()).toMatchObject({deliveryState:'delivered'});});

it('ordinary recorded audit row has no direct-attempt evidence and cannot be promoted',()=>{const e=outbox.record({senderSession:'builder@xv',destinationSession:'lead@xv',body:'actual original message',identityProvenance:'transport:v1'});ack(e.outboxId);expect(()=>reconcile(e.outboxId)).toThrow('Actual unresolved direct');expect(outbox.getById(e.outboxId)?.deliveryState).toBe('pending');});
it('claimed-source creation cannot establish actual recipient authorship',()=>{const e=effect();ack(e.outboxId);db.prepare("UPDATE queue_transitions SET identity_provenance='claimed:v1' WHERE qitem_id='receipt'").run();expect(()=>reconcile(e.outboxId)).toThrow('managed transport');expect(outbox.getById(e.outboxId)?.deliveryState).toBe('indeterminate');});
it('current recipient selects newest session node before tenure ordinal',()=>{const e=effect();ack(e.outboxId);db.prepare("UPDATE occupant_tenures SET generation_ordinal=5 WHERE node_id='lead@xv'").run();db.prepare("INSERT INTO nodes(id,rig_id,logical_id) VALUES ('new-lead','xv','new-lead')").run();db.prepare("INSERT INTO sessions(id,node_id,session_name) VALUES ('zz-new','new-lead','lead@xv')").run();db.prepare("INSERT INTO occupant_tenures(id,node_id,generation_ordinal,generation_uuid,kind) VALUES ('new-tenure','new-lead',1,'lead-g2','fresh')").run();expect(()=>reconcile(e.outboxId)).toThrow('acknowledgment');db.prepare("UPDATE queue_items SET minting_generation_uuid='lead-g2' WHERE qitem_id='receipt'").run();expect(outbox.reconcileRecipientDelivery({outboxId:e.outboxId,receiptId:'receipt',actor:'lead@xv',generation:'lead-g2',reason:'current recipient ack'}).deliveryState).toBe('delivered');});

it('body-only queue/create fake acknowledgment retains claimed provenance and refuses reconciliation',async()=>{const e=effect();const repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:()=> 'lead-g1'});const app=new Hono();app.use('*',async(c,next)=>{c.set('outboxHandler' as never,outbox as never);c.set('queueRepo' as never,repo as never);await next();});app.route('/queue',queueRoutes());const response=await app.request('/queue/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({qitemId:'receipt',sourceSession:'lead@xv',destinationSession:'builder@xv',body:JSON.stringify({kind:'outbox-delivery-ack',outboxId:e.outboxId,bodySha256:createHash('sha256').update(e.body).digest('hex')}),nudge:false})});expect(response.status).toBe(201);expect(db.prepare("SELECT identity_provenance FROM queue_transitions WHERE qitem_id='receipt' AND transition_note='created'").get()).toEqual({identity_provenance:'claimed:v1'});expect(()=>reconcile(e.outboxId)).toThrow('managed transport');});

const recipientContract=(e:ReturnType<typeof effect>)=>({outboxId:e.outboxId,bodySha256:createHash('sha256').update(e.body).digest('hex'),effectSnapshotSha256:createHash('sha256').update(JSON.stringify(e)).digest('hex'),expectedState:'indeterminate' as const,acknowledged:true as const,reason:'I actually read this exact direct diagnostic report'});
it.each(['lead@xv','operator-agent@kernel'])('native fixed recipient acknowledgment crosses enabled dispatch fence without new work or sender wake: %s',async recipient=>{
 const recipientGeneration=recipient==='lead@xv'?'lead-g1':'operator-agent-g1';
 const repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>repo.coordinatorAuthority.generation(s)});repo.attachOutbox(outbox);await repo.create({qitemId:'baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'coordinate',nudge:false,identityProvenance:'transport:v1'});
 const svc=repo.coordinatorAuthority;svc.enable('operator-agent@kernel','operator-agent-g1',{rigId:'xv',batonId:'baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:600000,operationId:'enable'});repo.claim({qitemId:'baton',destinationSession:'lead@xv',identityProvenance:'transport:v1'});svc.acknowledge('lead@xv',{rigId:'xv',epoch:1,generation:'lead-g1'},{operationId:'ack',obligationsDigest:svc.reconciliationDigest('xv')});
 const e=outbox.recordDirectAttempt({senderSession:'builder@xv',destinationSession:recipient,body:'actual original message',auditPointer:'original-pointer'},'indeterminate'),input=recipientContract(e),app=new Hono();app.use('*',async(c,next)=>{c.set('terminalBearerToken' as never,'test-token' as never);c.set('outboxHandler' as never,outbox as never);c.set('queueRepo' as never,repo as never);await next();});app.route('/queue',queueRoutes());const headers={'Content-Type':'application/json','Authorization':'Bearer test-token','X-OpenRig-Session':recipient,'X-OpenRig-Occupant-Generation':recipientGeneration};
 const refused=await app.request('/queue/create',{method:'POST',headers,body:JSON.stringify({qitemId:'generic-proof',sourceSession:recipient,destinationSession:'builder@xv',body:JSON.stringify({kind:'outbox-delivery-ack',outboxId:e.outboxId,bodySha256:input.bodySha256}),nudge:false})});expect(refused.status).toBe(409);expect(await refused.json()).toMatchObject({error:recipient==='lead@xv'?'coordinator_envelope_required':'coordinator_dispatch_required'});expect(repo.getById('generic-proof')).toBeNull();
 const authority=svc.get('xv'),baton=repo.getById('baton'),priorEvents=db.prepare('SELECT count(*) n FROM events').get();const send=()=>app.request('/queue/outbox/acknowledge',{method:'POST',headers,body:JSON.stringify(input)});
 const first=await send();expect(first.status).toBe(200);const result=await first.json() as any;expect(result.entry).toMatchObject({deliveryState:'delivered',body:e.body,senderSession:e.senderSession,destinationSession:e.destinationSession});expect(repo.getById(result.receiptId)).toMatchObject({state:'done',body:JSON.stringify({kind:'outbox-delivery-ack',outboxId:e.outboxId,bodySha256:input.bodySha256}),closureReason:'no-follow-on'});expect(db.prepare('SELECT minting_generation_uuid FROM queue_items WHERE qitem_id=?').get(result.receiptId)).toEqual({minting_generation_uuid:recipientGeneration});expect(repo.transitionLog.listForQitem(result.receiptId)).toMatchObject([{actorSession:recipient,identityProvenance:'transport:v1',state:'done',transitionNote:'created'}]);
 const after=db.prepare('SELECT * FROM events ORDER BY seq').all();expect((await send()).status).toBe(200);expect(db.prepare('SELECT * FROM events ORDER BY seq').all()).toEqual(after);expect(svc.get('xv')).toEqual(authority);expect(repo.getById('baton')).toEqual(baton);expect(outbox.listPending('wake-intent-')).toEqual([]);expect(db.prepare('SELECT count(*) n FROM coordinator_assignments').get()).toEqual({n:0});expect(db.prepare('SELECT count(*) n FROM coordinator_resources').get()).toEqual({n:0});expect(JSON.parse(result.entry.auditPointer)).toMatchObject({receiptId:result.receiptId,priorAuditPointer:'original-pointer',actor:recipient,generation:recipientGeneration});expect(after.length).toBe((priorEvents as any).n+1);
});
it.each(['actor','generation','hash','snapshot','state','ack-false','extra-body','ordinary-row','failed','wake','guard','quarantine','missing-origin','changed-origin','id-collision'])('native fixed recipient acknowledgment refuses %s without any partial receipt',kind=>{
 let e=effect();let actor='lead@xv',generation='lead-g1',input=recipientContract(e);
 if(kind==='actor')actor='operator-agent@kernel';if(kind==='generation')generation='retired';if(kind==='hash')input={...input,bodySha256:'a'.repeat(64)};if(kind==='snapshot')input={...input,effectSnapshotSha256:'a'.repeat(64)};if(kind==='state')input={...input,expectedState:'pending'} as any;if(kind==='ack-false')input={...input,acknowledged:false} as any;if(kind==='extra-body')input={...input,body:'arbitrary'} as any;
 if(kind==='ordinary-row'||kind==='wake'){e=outbox.record({outboxId:kind==='wake'?'wake-intent-executable':'ordinary-audit',senderSession:'builder@xv',destinationSession:'lead@xv',body:e.body});input={...recipientContract(e),expectedState:'pending'} as any;}
 if(kind==='failed'){e=effect('failed');input=recipientContract(e);}
 if(kind==='guard'){db.prepare('UPDATE outbox_entries SET guard_binding=? WHERE outbox_id=?').run(JSON.stringify({nodeId:'lead@xv',session:'lead@xv',occupant:'lead-g1',pane:null}),e.outboxId);input=recipientContract(outbox.getById(e.outboxId)!);}
 if(kind==='quarantine')db.prepare("INSERT INTO outbox_historical_quarantines VALUES (?, 'xv', 'hash','held','auth',?, 'held',?)").run(e.outboxId,Date.now()+600000,new Date().toISOString());
 if(kind==='missing-origin')db.prepare("DELETE FROM events WHERE type='outbox.direct_attempt'").run();if(kind==='changed-origin')db.prepare("UPDATE events SET payload=json_set(payload,'$.bodySha256','changed') WHERE type='outbox.direct_attempt'").run();
 if(kind==='id-collision'){const id='qitem-outbox-recipient-ack-'+createHash('sha256').update(JSON.stringify([e.outboxId,actor,generation])).digest('hex');db.prepare("INSERT INTO queue_items(qitem_id,ts_created,ts_updated,source_session,destination_session,state,body) VALUES (?,?,?,'lead@xv','builder@xv','done','arbitrary existing row')").run(id,new Date().toISOString(),new Date().toISOString());}
 const before={outbox:outbox.getById(e.outboxId),queues:db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all(),events:db.prepare('SELECT * FROM events ORDER BY seq').all(),transitions:db.prepare('SELECT * FROM queue_transitions').all()};expect(()=>outbox.acknowledgeRecipientDelivery(actor,generation,input)).toThrow();expect({outbox:outbox.getById(e.outboxId),queues:db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all(),events:db.prepare('SELECT * FROM events ORDER BY seq').all(),transitions:db.prepare('SELECT * FROM queue_transitions').all()}).toEqual(before);
});
it('native fixed recipient acknowledgment exact replay conflicts with changed request stale occupant and receipt drift',()=>{
 const e=effect(),input=recipientContract(e),result=outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',input),before=outbox.getById(e.outboxId);expect(()=>outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',{...input,reason:'changed assertion'})).toThrow('replay');db.exec('SAVEPOINT stale');db.prepare("UPDATE occupant_tenures SET generation_uuid='lead-g2' WHERE node_id='lead@xv'").run();expect(()=>outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',input)).toThrow('native recipient');db.exec('ROLLBACK TO stale');db.exec('RELEASE stale');db.exec('SAVEPOINT uncertainReplay');db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run(e.outboxId);const uncertain=outbox.getById(e.outboxId);expect(()=>outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',input)).toThrow('replay');expect(outbox.getById(e.outboxId)).toEqual(uncertain);db.exec('ROLLBACK TO uncertainReplay');db.exec('RELEASE uncertainReplay');db.prepare("UPDATE queue_items SET body='changed proof' WHERE qitem_id=?").run(result.receiptId);expect(()=>outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',input)).toThrow('replay');expect(outbox.getById(e.outboxId)).toEqual(before);
});
it('native fixed recipient acknowledgment API refuses missing transport and body identity assertions',async()=>{
 const e=effect(),input=recipientContract(e),app=new Hono();app.use('*',async(c,next)=>{c.set('terminalBearerToken' as never,'test-token' as never);c.set('outboxHandler' as never,outbox as never);await next();});app.route('/queue',queueRoutes());const send=(headers:Record<string,string>,body:any=input)=>app.request('/queue/outbox/acknowledge',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer test-token',...headers},body:JSON.stringify(body)});expect((await send({})).status).toBe(403);expect((await send({'X-OpenRig-Session':'lead@xv'})).status).toBe(403);expect((await send({'X-OpenRig-Session':'lead@xv','X-OpenRig-Occupant-Generation':'lead-g1'},{...input,actor:'lead@xv'})).status).toBe(409);expect(db.prepare('SELECT count(*) n FROM queue_items').get()).toEqual({n:0});expect(outbox.getById(e.outboxId)).toEqual(e);
});
