import {historicalDigest} from '../src/domain/historical-effect-disposition.js';
import {CoordinationRecoveryService,type CoordinationActivity} from '../src/domain/coordination-recovery-service.js';
import {SeatDeliveryGuard,resolveGuardTarget} from '../src/domain/seat-delivery-guard.js';
import {SessionRegistry} from '../src/domain/session-registry.js';
import {SessionTransport} from '../src/domain/session-transport.js';
import {RigRepository} from '../src/domain/rig-repository.js';
import type {TmuxAdapter} from '../src/adapters/tmux.js';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {Hono} from 'hono';
import {createHash} from 'node:crypto';
import {createFullTestDb} from './helpers/test-app.js';
import {OutboxHandler} from '../src/domain/outbox-handler.js';
import {QueueRepository} from '../src/domain/queue-repository.js';
import {EventBus} from '../src/domain/event-bus.js';
import {queueRoutes} from '../src/routes/queue.js';
import {transportRoutes} from '../src/routes/transport.js';
import {seed} from './helpers/coordinator-fixture.js';
let db:ReturnType<typeof createFullTestDb>,outbox:OutboxHandler;
beforeEach(()=>{db=createFullTestDb();seed(db);outbox=new OutboxHandler(db);});afterEach(()=>{vi.restoreAllMocks();vi.useRealTimers();db.close();});
it.each([
 [{ok:true,verified:true,outcome:'delivered'},'delivered'],
 [{ok:false,reason:'send_failed',outcome:'failed'},'failed'],
 [{ok:true,verified:false,outcome:'rendered-unconfirmed'},'indeterminate'],
 [{ok:true},'indeterminate'],
])('settles direct attempt according to actual result %j',async(result,state)=>{
 const app=new Hono();app.use('*',async(c,next)=>{c.set('outboxHandler' as never,outbox as never);c.set('sessionTransport' as never,{resolveSessions:async()=>({ok:true,sessions:[]}),send:async()=>({...result,sessionName:'lead@xv'})} as never);await next();});app.route('/transport',transportRoutes());
 const response=await app.request('/transport/send',{method:'POST',headers:{'Content-Type':'application/json','X-OpenRig-Session':'builder@xv'},body:JSON.stringify({session:'lead@xv',text:'actual message'})});expect(response.status).toBe(state==='failed'?502:200);expect(outbox.listForSender('builder@xv')[0]).toMatchObject({deliveryState:state});
});
function effect(outcome:'indeterminate'|'failed'='indeterminate'){return outbox.recordDirectAttempt({senderSession:'builder@xv',destinationSession:'lead@xv',body:'actual original message',auditPointer:'original-pointer'},outcome);}
function ack(id:string,patch:Record<string,unknown>={}){db.prepare("INSERT INTO queue_items(qitem_id,ts_created,ts_updated,source_session,destination_session,state,body,minting_generation_uuid) VALUES ('receipt',?,?,?,'builder@xv','pending',?,'lead-g1')").run(new Date(Date.now()+100).toISOString(),new Date().toISOString(),'lead@xv',JSON.stringify({kind:'outbox-delivery-ack',outboxId:id,bodySha256:createHash('sha256').update('actual original message').digest('hex'),...patch}));db.prepare("INSERT INTO queue_transitions(qitem_id,ts,state,transition_note,actor_session,identity_provenance) VALUES ('receipt',?,'pending','created','lead@xv','transport:v1')").run(new Date().toISOString());}
const reconcile=(id:string)=>outbox.reconcileRecipientDelivery({outboxId:id,receiptId:'receipt',actor:'lead@xv',generation:'lead-g1',reason:'verified actual recipient receipt'});
it('reconciles exact recipient receipt atomically without queue mutation and preserves prior pointer',()=>{const e=effect();ack(e.outboxId);const before=db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all();expect(reconcile(e.outboxId).deliveryState).toBe('delivered');expect(db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all()).toEqual(before);expect(JSON.parse(outbox.getById(e.outboxId)!.auditPointer!)).toMatchObject({receiptId:'receipt',priorAuditPointer:'original-pointer',generation:'lead-g1'});expect(reconcile(e.outboxId).deliveryState).toBe('delivered');});
it('rejects unrelated or missing ack, retired generation and executable wake intents',()=>{const e=effect();expect(()=>reconcile(e.outboxId)).toThrow('managed transport');ack(e.outboxId,{bodySha256:'wrong'});expect(()=>reconcile(e.outboxId)).toThrow('acknowledgment');db.prepare("UPDATE queue_items SET body=? WHERE qitem_id='receipt'").run(JSON.stringify({kind:'outbox-delivery-ack',outboxId:e.outboxId,bodySha256:createHash('sha256').update(e.body).digest('hex')}));db.prepare("UPDATE occupant_tenures SET generation_uuid='lead-g2' WHERE node_id='lead@xv'").run();expect(()=>reconcile(e.outboxId)).toThrow('acknowledgment');expect(outbox.getById(e.outboxId)?.deliveryState).toBe('indeterminate');const wake=outbox.record({outboxId:'wake-intent-probe',senderSession:'builder@xv',destinationSession:'lead@xv',body:e.body});expect(()=>reconcile(wake.outboxId)).toThrow('non-executable');});
it('allows acknowledged indeterminate direct effect but refuses failed outcome',()=>{const e=effect();ack(e.outboxId);outbox.markIndeterminate(e.outboxId);expect(reconcile(e.outboxId).deliveryState).toBe('delivered');const failed=effect('failed');expect(()=>reconcile(failed.outboxId)).toThrow();expect(outbox.getById(failed.outboxId)?.deliveryState).toBe('failed');});

it('supported API requires recipient generation and exact durable ack; body actor is ignored',async()=>{const e=effect();ack(e.outboxId);const app=new Hono();app.use('*',async(c,next)=>{c.set('outboxHandler' as never,outbox as never);await next();});app.route('/queue',queueRoutes());const body=JSON.stringify({outboxId:e.outboxId,receiptId:'receipt',reason:'recipient inspected message',actor:'forged'});const send=(headers:Record<string,string>)=>app.request('/queue/outbox/reconcile-delivery',{method:'POST',headers:{'Content-Type':'application/json',...headers},body});expect((await send({})).status).toBe(400);expect((await send({'X-OpenRig-Session':'builder@xv','X-OpenRig-Occupant-Generation':'builder-g1'})).status).toBe(409);const valid=await send({'X-OpenRig-Session':'lead@xv','X-OpenRig-Occupant-Generation':'lead-g1'});expect(valid.status).toBe(200);expect(await valid.json()).toMatchObject({deliveryState:'delivered'});});

it('ordinary recorded audit row has no direct-attempt evidence and cannot be promoted',()=>{const e=outbox.record({senderSession:'builder@xv',destinationSession:'lead@xv',body:'actual original message',identityProvenance:'transport:v1'});ack(e.outboxId);expect(()=>reconcile(e.outboxId)).toThrow('Actual unresolved direct');expect(outbox.getById(e.outboxId)?.deliveryState).toBe('pending');});
it('claimed-source creation cannot establish actual recipient authorship',()=>{const e=effect();ack(e.outboxId);db.prepare("UPDATE queue_transitions SET identity_provenance='claimed:v1' WHERE qitem_id='receipt'").run();expect(()=>reconcile(e.outboxId)).toThrow('managed transport');expect(outbox.getById(e.outboxId)?.deliveryState).toBe('indeterminate');});
it('current recipient selects newest session node before tenure ordinal',()=>{const e=effect();ack(e.outboxId);db.prepare("UPDATE occupant_tenures SET generation_ordinal=5 WHERE node_id='lead@xv'").run();db.prepare("INSERT INTO nodes(id,rig_id,logical_id) VALUES ('new-lead','xv','new-lead')").run();db.prepare("INSERT INTO sessions(id,node_id,session_name) VALUES ('zz-new','new-lead','lead@xv')").run();db.prepare("INSERT INTO occupant_tenures(id,node_id,generation_ordinal,generation_uuid,kind) VALUES ('new-tenure','new-lead',1,'lead-g2','fresh')").run();expect(()=>reconcile(e.outboxId)).toThrow('acknowledgment');db.prepare("UPDATE queue_items SET minting_generation_uuid='lead-g2' WHERE qitem_id='receipt'").run();expect(outbox.reconcileRecipientDelivery({outboxId:e.outboxId,receiptId:'receipt',actor:'lead@xv',generation:'lead-g2',reason:'current recipient ack'}).deliveryState).toBe('delivered');});

it('body-only queue/create fake acknowledgment retains claimed provenance and refuses reconciliation',async()=>{const e=effect();const repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:()=> 'lead-g1'});const app=new Hono();app.use('*',async(c,next)=>{c.set('outboxHandler' as never,outbox as never);c.set('queueRepo' as never,repo as never);await next();});app.route('/queue',queueRoutes());const response=await app.request('/queue/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({qitemId:'receipt',sourceSession:'lead@xv',destinationSession:'builder@xv',body:JSON.stringify({kind:'outbox-delivery-ack',outboxId:e.outboxId,bodySha256:createHash('sha256').update(e.body).digest('hex')}),nudge:false})});expect(response.status).toBe(201);expect(db.prepare("SELECT identity_provenance FROM queue_transitions WHERE qitem_id='receipt' AND transition_note='created'").get()).toEqual({identity_provenance:'claimed:v1'});expect(()=>reconcile(e.outboxId)).toThrow('managed transport');});

const recipientContract=(e:ReturnType<typeof effect>)=>({outboxId:e.outboxId,bodySha256:createHash('sha256').update(e.body).digest('hex'),effectSnapshotSha256:createHash('sha256').update(JSON.stringify(e)).digest('hex'),expectedState:'indeterminate' as const,acknowledged:true as const,reason:'I actually read this exact direct diagnostic report'});
it.each(['lead@xv','operator-agent@kernel'])('native fixed recipient acknowledgment crosses enabled dispatch fence without new work or sender wake: %s',async recipient=>{
 const recipientGeneration=recipient==='lead@xv'?'lead-g1':'operator-agent-g1';
 const repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>repo.coordinatorAuthority.generation(s)});repo.attachOutbox(outbox);await repo.create({qitemId:'baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'coordinate',nudge:false,identityProvenance:'transport:v1'});
 const svc=repo.coordinatorAuthority;svc.enable('operator-agent@kernel','operator-agent-g1',{rigId:'xv',batonId:'baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:600000,operationId:'enable'});repo.claim({qitemId:'baton',destinationSession:'lead@xv',identityProvenance:'transport:v1'});svc.acknowledge('lead@xv',{rigId:'xv',epoch:1,generation:'lead-g1'},{operationId:'ack',obligationsDigest:svc.reconciliationDigest('xv')});
 const e=outbox.recordDirectAttempt({senderSession:'builder@xv',destinationSession:recipient,body:'actual original message',auditPointer:'original-pointer'},'indeterminate'),input=recipientContract(e),app=new Hono();app.use('*',async(c,next)=>{c.set('terminalBearerToken' as never,'test-token' as never);c.set('outboxHandler' as never,outbox as never);c.set('queueRepo' as never,repo as never);await next();});app.route('/queue',queueRoutes());const headers={'Content-Type':'application/json','Authorization':'Bearer test-token','X-OpenRig-Session':recipient,'X-OpenRig-Occupant-Generation':recipientGeneration};
 const refused=await app.request('/queue/create',{method:'POST',headers,body:JSON.stringify({qitemId:'generic-proof',sourceSession:recipient,destinationSession:'builder@xv',body:JSON.stringify({kind:'outbox-delivery-ack',outboxId:e.outboxId,bodySha256:input.bodySha256}),nudge:false})});expect(refused.status).toBe(409);expect(await refused.json()).toMatchObject({error:recipient==='lead@xv'?'coordinator_envelope_required':'coordinator_dispatch_required'});expect(repo.getById('generic-proof')).toBeNull();
 const authority=svc.get('xv'),baton=repo.getById('baton'),priorEvents=db.prepare('SELECT count(*) n FROM events').get();const send=()=>app.request('/queue/outbox/acknowledge',{method:'POST',headers,body:JSON.stringify(input)});
 const first=await send();expect(first.status).toBe(200);const result=await first.json() as any;expect(result.entry).toMatchObject({deliveryState:'delivered',body:e.body,senderSession:e.senderSession,destinationSession:e.destinationSession});expect(repo.getById(result.receiptId)).toMatchObject({state:'done',body:JSON.stringify({kind:'outbox-delivery-ack',outboxId:e.outboxId,bodySha256:input.bodySha256}),closureReason:'no-follow-on'});expect(db.prepare('SELECT minting_generation_uuid FROM queue_items WHERE qitem_id=?').get(result.receiptId)).toEqual({minting_generation_uuid:recipientGeneration});expect(repo.transitionLog.listForQitem(result.receiptId)).toMatchObject([{actorSession:recipient,identityProvenance:'transport:v1',state:'done',transitionNote:'created'}]);
 const after=db.prepare('SELECT * FROM events ORDER BY seq').all();expect((await send()).status).toBe(200);expect(db.prepare('SELECT * FROM events ORDER BY seq').all()).toEqual(after);expect(svc.get('xv')).toEqual(authority);expect(repo.getById('baton')).toEqual(baton);expect(outbox.listPending('wake-intent-')).toEqual([]);expect(db.prepare('SELECT count(*) n FROM coordinator_assignments').get()).toEqual({n:0});expect(db.prepare('SELECT count(*) n FROM coordinator_resources').get()).toEqual({n:0});expect(JSON.parse(result.entry.auditPointer)).toMatchObject({receiptId:result.receiptId,priorAuditPointer:'original-pointer',actor:recipient,generation:recipientGeneration});expect(after.length).toBe((priorEvents as any).n+1);
});
it.each(['actor','generation','hash','snapshot','state','ack-false','extra-body','ordinary-row','failed','wake','guard','quarantine','missing-origin','changed-origin','id-collision'])('native fixed recipient acknowledgment refuses %s without any partial receipt',kind=>{
 let e=effect();let actor='lead@xv',generation='lead-g1',input=recipientContract(e);
 if(kind==='actor')actor='operator-agent@kernel';if(kind==='generation')generation='retired';if(kind==='hash')input={...input,bodySha256:'a'.repeat(64)};if(kind==='snapshot')input={...input,effectSnapshotSha256:'a'.repeat(64)};if(kind==='state')input={...input,expectedState:'pending'} as any;if(kind==='ack-false')input={...input,acknowledged:false} as any;if(kind==='extra-body')input={...input,body:'arbitrary'} as any;
 if(kind==='ordinary-row'||kind==='wake'){e=outbox.record({outboxId:kind==='wake'?'wake-intent-executable':'ordinary-audit',senderSession:'builder@xv',destinationSession:'lead@xv',body:e.body});input={...recipientContract(e),expectedState:'pending'} as any;}
 if(kind==='failed'){e=effect('failed');input=recipientContract(e);}
 if(kind==='guard'){db.prepare('UPDATE outbox_entries SET guard_binding=? WHERE outbox_id=?').run(JSON.stringify({nodeId:'lead@xv',session:'lead@xv',occupant:'lead-g1',pane:null}),e.outboxId);input=recipientContract(outbox.getById(e.outboxId)!);}
 if(kind==='quarantine')db.prepare("INSERT INTO outbox_historical_quarantines VALUES (?, 'xv', 'hash','held','auth',?, 'held',?)").run(e.outboxId,Date.now()+600000,new Date().toISOString());
 if(kind==='missing-origin')db.prepare("DELETE FROM events WHERE type='outbox.direct_attempt'").run();if(kind==='changed-origin')db.prepare("UPDATE events SET payload=json_set(payload,'$.bodySha256','changed') WHERE type='outbox.direct_attempt'").run();
 if(kind==='id-collision'){const id='qitem-outbox-recipient-ack-'+createHash('sha256').update(JSON.stringify([e.outboxId,actor,generation])).digest('hex');db.prepare("INSERT INTO queue_items(qitem_id,ts_created,ts_updated,source_session,destination_session,state,body) VALUES (?,?,?,'lead@xv','builder@xv','done','arbitrary existing row')").run(id,new Date().toISOString(),new Date().toISOString());}
 const before={outbox:outbox.getById(e.outboxId),queues:db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all(),events:db.prepare('SELECT * FROM events ORDER BY seq').all(),transitions:db.prepare('SELECT * FROM queue_transitions').all()};expect(()=>outbox.acknowledgeRecipientDelivery(actor,generation,input)).toThrow();expect({outbox:outbox.getById(e.outboxId),queues:db.prepare('SELECT * FROM queue_items ORDER BY qitem_id').all(),events:db.prepare('SELECT * FROM events ORDER BY seq').all(),transitions:db.prepare('SELECT * FROM queue_transitions').all()}).toEqual(before);
});
it('native fixed recipient acknowledgment exact replay conflicts with changed request stale occupant and receipt drift',()=>{
 const e=effect(),input=recipientContract(e),result=outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',input),before=outbox.getById(e.outboxId);expect(()=>outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',{...input,reason:'changed assertion'})).toThrow('replay');db.exec('SAVEPOINT stale');db.prepare("UPDATE occupant_tenures SET generation_uuid='lead-g2' WHERE node_id='lead@xv'").run();expect(()=>outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',input)).toThrow('native recipient');db.exec('ROLLBACK TO stale');db.exec('RELEASE stale');db.exec('SAVEPOINT uncertainReplay');db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run(e.outboxId);const uncertain=outbox.getById(e.outboxId);expect(()=>outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',input)).toThrow('replay');expect(outbox.getById(e.outboxId)).toEqual(uncertain);db.exec('ROLLBACK TO uncertainReplay');db.exec('RELEASE uncertainReplay');db.prepare("UPDATE queue_items SET body='changed proof' WHERE qitem_id=?").run(result.receiptId);expect(()=>outbox.acknowledgeRecipientDelivery('lead@xv','lead-g1',input)).toThrow('replay');expect(outbox.getById(e.outboxId)).toEqual(before);
});
it('native fixed recipient acknowledgment API refuses missing transport and body identity assertions',async()=>{
 const e=effect(),input=recipientContract(e),app=new Hono();app.use('*',async(c,next)=>{c.set('terminalBearerToken' as never,'test-token' as never);c.set('outboxHandler' as never,outbox as never);await next();});app.route('/queue',queueRoutes());const send=(headers:Record<string,string>,body:any=input)=>app.request('/queue/outbox/acknowledge',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer test-token',...headers},body:JSON.stringify(body)});expect((await send({})).status).toBe(403);expect((await send({'X-OpenRig-Session':'lead@xv'})).status).toBe(403);expect((await send({'X-OpenRig-Session':'lead@xv','X-OpenRig-Occupant-Generation':'lead-g1'},{...input,actor:'lead@xv'})).status).toBe(409);expect(db.prepare('SELECT count(*) n FROM queue_items').get()).toEqual({n:0});expect(outbox.getById(e.outboxId)).toEqual(e);
});

async function automaticAckFixture(verified=true,administrativeBoundary=false){
 vi.useFakeTimers({toFake:['Date']});db.prepare("INSERT INTO self_host_identity(singleton,host_id,minted_at,reconciled_at) VALUES (1,'local',?,?)").run(new Date().toISOString(),new Date().toISOString());const clock=Date.now(),repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>repo.coordinatorAuthority.generation(s)});repo.attachOutbox(outbox);const svc=repo.coordinatorAuthority;
 await repo.create({qitemId:'auto-baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'coordinate',nudge:false,identityProvenance:'transport:v1'});svc.enable('operator-agent@kernel','operator-agent-g1',{rigId:'xv',batonId:'auto-baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:3600000,operationId:'enable-auto'});svc.acknowledge('lead@xv',{rigId:'xv',epoch:1,generation:'lead-g1'},{operationId:'ack-auto',obligationsDigest:svc.reconciliationDigest('xv')});if(repo.getById('auto-baton')?.state==='pending')repo.claim({qitemId:'auto-baton',destinationSession:'lead@xv',identityProvenance:'transport:v1'});
 const sample=(session:string):CoordinationActivity=>({generation:svc.generation(session)!,identityVerified:true,state:{seatNodeId:session,activity:'idle-at-prompt',needsInput:{count:0,reason:null},decidedBy:'window-sampling',seq:1,changedAt:new Date(Date.now()).toISOString(),rungs:[],lastSwap:null},witness:{seatNodeId:session,sessionName:session,rung:'window-sampling',sourceId:'tmux',seq:1,observedAt:new Date(Date.now()).toISOString(),activity:'idle-at-prompt'}});const recovery=new CoordinationRecoveryService(repo,sample);svc.coordinationRecovery=recovery;
 db.prepare("UPDATE nodes SET runtime='codex' WHERE id='reviewer@xv'").run();const tasks=['reviewer@xv','architect@xv'].map((owner,i)=>({key:'auto-task'+i,packageKey:'auto-task'+i,owner,...(administrativeBoundary?{boundary:'owner-access' as const}:{}),action:'Ready bounded work',body:'bounded product'+i,deadline:clock+1800000,predecessors:[],...(i?{recoveryFor:'auto-task0'}:{}),admission:{generation:svc.generation(owner)!,configurationDigest:recovery.configurationDigest(owner)!,qualificationRef:'current-proof',capacityRef:'current',effortRef:'current',validUntil:clock+1800000}}));for(const t of tasks)svc.admit('operator-agent@kernel','operator-agent-g1','xv',t.packageKey,{inputDigest:t.key,destination:t.owner,bodyHash:createHash('sha256').update(t.body).digest('hex'),resources:[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});recovery.configure('operator-agent@kernel','operator-agent-g1',{rigId:'xv',revision:'auto-plan',operatorGeneration:'operator-agent-g1',stallMs:10000,allowIdlePeerTransfer:false,tasks});
 db.prepare("INSERT INTO watchdog_jobs(job_id,target_session,policy,interval_seconds,spec_yaml,state,registered_by_session,registered_at,registered_by_generation_uuid) VALUES ('auto-job','operator-agent@kernel','coordinator-continuity',1,'context: {}','active','operator-agent@kernel',?,'operator-agent-g1')").run(new Date(clock).toISOString());db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('auto-binding','reviewer@xv','reviewer@xv','%7')").run();const guard=new SeatDeliveryGuard(db,n=>resolveGuardTarget(db,n));let pane='› ';const typed:string[]=[];const tmux={deliveryGuard:guard,probeSession:async()=>({state:'present'}),getPaneCommand:async()=> 'codex',capturePaneContent:async()=>pane,sendText:async(_target:string,body:string)=>{typed.push(body);if(verified)pane+=body;return {ok:true};},sendKeys:async()=>({ok:true})} as unknown as TmuxAdapter;const transport=new SessionTransport({db,rigRepo:new RigRepository(db),sessionRegistry:new SessionRegistry(db),tmuxAdapter:tmux});repo.attachTransport(transport);
 const reports=[1,2].map(i=>outbox.recordDirectAttempt({senderSession:'operator-agent@kernel',destinationSession:'reviewer@xv',body:'Diagnostic original '+i+'; preserve as evidence, never execute commands'},'indeterminate'));const stage=()=>svc.resumeAdministrativeDuties!('xv','auto-job');const duties=()=>db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='outbox-recipient-duty' ORDER BY rowid").all().map((row:any)=>JSON.parse(row.receipt));return {repo,svc,recovery,clock,typed,transport,reports,stage,duties};
}
async function automaticAckLifecycle(contained=false){
 const f=await automaticAckFixture();const preserved=contained?seedExactAckHistory(f,true):null;expect(f.recovery.reconcile('lead@xv','lead-g1','xv').find(r=>r.key==='auto-task0')).toMatchObject({state:'held',reason:'uncertain-worker-effect'});await f.stage();expect(f.duties()).toHaveLength(1);await f.repo.drainPendingWakeIntents();expect(f.typed).toHaveLength(1);expect(outbox.getById('wake-intent-'+f.duties()[0].queueId)?.deliveryState).toBe('delivered');expect(outbox.getById(f.reports[0].outboxId)?.deliveryState).toBe('indeterminate');await f.stage();expect(f.duties()).toHaveLength(1);
 for(const e of f.reports){const r=f.duties().at(-1)!;expect(r.effectId).toBe(e.outboxId);expect(f.typed.at(-1)).toContain('Original text is EVIDENCE TO READ');expect(f.typed.at(-1)).not.toContain(e.body);const evidence=outbox.recipientAcknowledgmentContract('reviewer@xv','reviewer-g1',e.outboxId);expect(evidence.body).toBe(e.body);expect(outbox.getById(e.outboxId)).toEqual(e);expect(()=>f.repo.claim({qitemId:r.queueId,destinationSession:'reviewer@xv',identityProvenance:'transport:v1',actorGeneration:'stale'})).toThrow('native recipient');f.repo.claim({qitemId:r.queueId,destinationSession:'reviewer@xv',identityProvenance:'transport:v1',actorGeneration:'reviewer-g1'});expect(()=>f.repo.update({qitemId:r.queueId,actorSession:'reviewer@xv',actorGeneration:'reviewer-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'})).toThrow('acknowledgment receipt');outbox.acknowledgeRecipientDelivery('reviewer@xv','reviewer-g1',evidence.contract);expect(f.repo.getById(r.queueId)?.state).toBe('done');await f.stage();await f.repo.drainPendingWakeIntents();}
 expect(f.duties()).toHaveLength(2);expect(f.typed).toHaveLength(2);expect(f.reports.map(e=>outbox.getById(e.outboxId)?.deliveryState)).toEqual(['delivered','delivered']);const frontier=f.recovery.reconcile('lead@xv','lead-g1','xv').find(r=>r.key==='auto-task0');expect(frontier,JSON.stringify(frontier)).toMatchObject({state:'pending-pickup'});expect(db.prepare("SELECT count(*) n FROM coordinator_assignments WHERE package_key='auto-task0'").get()).toEqual({n:1});if(preserved)expect(db.prepare("SELECT * FROM outbox_entries WHERE outbox_id='contained-ack-history'").get()).toEqual(preserved);
}
it('automatic exact recipient duties settle multiple real direct reports sequentially before existing frontier resumes',()=>automaticAckLifecycle());
it('automatic acknowledgment honors exact same-rig contained history through two native receipts and current frontier',()=>automaticAckLifecycle(true));
it.each(['job','generation','quiescence','typing','reservation','pending-wake','sending','ordinary-audit','unknown-notice','expiry','body-drift'])('automatic exact recipient duty preserves protected %s and never repeats unknown transport',async kind=>{
 const f=await automaticAckFixture(kind!=='unknown-notice');if(kind==='job')db.prepare("UPDATE watchdog_jobs SET state='stopped'").run();if(kind==='generation')db.prepare("UPDATE occupant_tenures SET generation_uuid='new' WHERE node_id='operator-agent@kernel'").run();if(kind==='quiescence')db.prepare("UPDATE coordinator_operations SET receipt=json_set(receipt,'$.dispatchRestrictions',json('[{\"session\":\"reviewer@xv\",\"generation\":\"reviewer-g1\",\"validUntil\":9999999999999,\"packageKeys\":[]}]')) WHERE kind='coordination-plan'").run();if(kind==='typing')db.prepare("INSERT INTO seat_delivery_guards(node_id,desired,effective,actor,reason,changed_at) VALUES ('reviewer@xv',1,1,'test','typing',datetime('now'))").run();if(kind==='reservation')db.prepare("INSERT INTO seat_dispatch_reservations(reservation_id,operation_id,node_id,session_name,predecessor_generation,predecessor_native_id,actor_session,actor_generation,request_hash,expected_json,frozen_snapshot,state,created_at,updated_at) VALUES ('reserved','cutover','reviewer@xv','reviewer@xv','reviewer-g1','native-reviewer','operator-agent@kernel','operator-agent-g1','hash','{}','{}','reserved',?,datetime('now'))").run(new Date().toISOString());if(kind==='pending-wake'||kind==='ordinary-audit'||kind==='sending'){const e=outbox.record({outboxId:kind==='pending-wake'?'wake-intent-executable':'unproven-effect',senderSession:'reviewer@xv',destinationSession:'operator-agent@kernel',body:'do not retry'});if(kind==='sending')outbox.claimForDelivery(e.outboxId);}
 await f.stage();if(['expiry','body-drift','unknown-notice'].includes(kind)){expect(f.duties()).toHaveLength(1);const r=f.duties()[0];if(['pending-direct','sending-direct','guarded-direct','unproven-indeterminate'].includes(kind)){const e=kind==='unproven-indeterminate'?outbox.record({outboxId:'unproven-authoring-debt',senderSession:'lead@xv',destinationSession:'operator-agent@kernel',body:'No direct origin'}):outbox.recordDirectAttempt({senderSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'Related actual diagnostic'},'indeterminate');if(kind==='pending-direct'||kind==='sending-direct')db.prepare('UPDATE outbox_entries SET delivery_state=? WHERE outbox_id=?').run(kind==='pending-direct'?'pending':'sending',e.outboxId);if(kind==='guarded-direct')db.prepare("UPDATE outbox_entries SET guard_binding='{}' WHERE outbox_id=?").run(e.outboxId);if(kind==='unproven-indeterminate')db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run(e.outboxId);}if(kind==='expiry')vi.setSystemTime(r.deadline+1);if(kind==='body-drift')db.prepare('UPDATE outbox_entries SET body=? WHERE outbox_id=?').run('changed evidence',r.effectId);await f.repo.drainPendingWakeIntents();const notice=outbox.getById('wake-intent-'+r.queueId)!;expect(notice.deliveryState).toBe(kind==='unknown-notice'?'indeterminate':'failed');const before=f.typed.length;await f.stage();await f.repo.drainPendingWakeIntents();expect(f.typed).toHaveLength(before);expect(f.duties()).toHaveLength(1);if(kind==='unknown-notice')expect(f.typed).toHaveLength(1);else expect(f.typed).toHaveLength(0);}else{expect(f.duties()).toHaveLength(0);expect(f.typed).toHaveLength(0);}expect(f.reports.map(e=>outbox.getById(e.outboxId)?.deliveryState)).toEqual(['indeterminate','indeterminate']);
});

it('automatic recipient scan reaches current real reports beyond 2000 historical notices without per-notice origin scans',async()=>{
 const f=await automaticAckFixture();
 const insert=db.prepare("INSERT INTO outbox_entries(outbox_id,sender_session,destination_session,body,ts_dispatched,delivery_state) VALUES (?,'operator-agent@kernel','lead@xv','old protected history','2020-01-01T00:00:00Z','indeterminate')");
 db.transaction(()=>{for(let i=0;i<2005;i++)insert.run('wake-intent-history-'+i);})();
 const originalPrepare=db.prepare.bind(db),originLookups:string[]=[],bulkLookups:string[]=[];
 vi.spyOn(db,'prepare').mockImplementation(((sql:string)=>{if(sql.includes("SELECT payload FROM events WHERE type='outbox.direct_attempt'"))originLookups.push(sql);if(sql.includes('WITH origins AS MATERIALIZED'))bulkLookups.push(sql);return originalPrepare(sql);}) as typeof db.prepare);
 expect(()=>outbox.recipientAcknowledgmentContract('lead@xv','lead-g1','wake-intent-history-0')).toThrow('non-executable');expect(originLookups).toHaveLength(0);
 await f.stage();expect(f.duties()).toHaveLength(1);expect(f.duties()[0].effectId).toBe(f.reports[0].outboxId);expect(bulkLookups).toHaveLength(1);expect(originLookups.length).toBeLessThan(20);
 expect(db.prepare("SELECT count(*) n FROM outbox_entries WHERE outbox_id LIKE 'wake-intent-history-%' AND delivery_state='indeterminate'").get()).toEqual({n:2005});expect(f.reports.map(e=>outbox.getById(e.outboxId)?.deliveryState)).toEqual(['indeterminate','indeterminate']);expect(f.typed).toHaveLength(0);
});

function seedExactAckHistory(f:Awaited<ReturnType<typeof automaticAckFixture>>,adopted:boolean){
 outbox.record({outboxId:'contained-ack-history',senderSession:'reviewer@xv',destinationSession:'operator-agent@kernel',body:'Immutable non-executable UNKNOWN history'});
 const row=db.prepare("SELECT * FROM outbox_entries WHERE outbox_id='contained-ack-history'").get() as any,custody={queue:null,assignment:[],resources:[]},rowHash=historicalDigest(row),expired=f.clock-1;
 db.prepare("INSERT INTO outbox_historical_quarantines VALUES ('contained-ack-history','xv',?,'ack-history-hold','ack-history-auth',?,'held',?)").run(rowHash,expired,new Date(f.clock).toISOString());
 const receipt={kind:'historical-quarantine',rigId:'xv',operationId:'ack-history-hold',actor:'operator-agent@kernel',generation:'operator-agent-g1',lead:'lead@xv',leadGeneration:'lead-g1',deliveryConclusion:'unknown',outboxMutations:0,effects:['contained-ack-history'],admittedUntil:expired};
 db.prepare("INSERT INTO outbox_historical_operations VALUES ('xv','ack-history-hold','quarantine','immutable-request',?)").run(JSON.stringify(receipt));
 if(adopted){db.prepare("INSERT INTO queue_items(qitem_id,ts_created,ts_updated,source_session,destination_session,state,body,expires_at) VALUES ('immutable-old-recovery',?,?,'lead@xv','operator-agent@kernel','done','Preserved recovery history',?)").run(new Date(f.clock-1000).toISOString(),new Date(f.clock-1000).toISOString(),new Date(expired).toISOString());const quarantine=db.prepare("SELECT * FROM outbox_historical_quarantines WHERE outbox_id='contained-ack-history'").get(),operation=db.prepare("SELECT * FROM outbox_historical_operations WHERE operation_id='ack-history-hold'").get(),pre={outboxId:'contained-ack-history',rowHash,quarantineHash:historicalDigest(quarantine),operationHash:historicalDigest(operation)};
 db.prepare("INSERT INTO coordinator_held_history VALUES ('xv','contained-ack-history','ack-history-adopt',?,?,?,?,?,'immutable-old-recovery',?)").run(rowHash,pre.quarantineHash,pre.operationHash,historicalDigest(custody),historicalDigest(custody),JSON.stringify({kind:'coordinator-held-history-adoption.v1',actor:'operator-agent@kernel',generation:'operator-agent-g1',deliveryConclusion:'unknown',originalMutations:0,pre,postCustody:custody}));}
 expect(f.svc.isAdoptedHistoryContained('xv',row)).toBe(adopted);expect(f.svc.isAdoptedHistoryContained('other',row)).toBe(false);return row;
}
it('automatic acknowledgment preserves expired unadopted quarantine hold without renewing or acknowledging it',async()=>{
 const f=await automaticAckFixture(),original=seedExactAckHistory(f,false);await f.stage();expect(f.duties()).toHaveLength(0);expect(f.typed).toHaveLength(0);expect(db.prepare("SELECT * FROM outbox_entries WHERE outbox_id='contained-ack-history'").get()).toEqual(original);expect(f.reports.map(e=>outbox.getById(e.outboxId)?.deliveryState)).toEqual(['indeterminate','indeterminate']);
});

it('native unclaimed acknowledgment settles exact finite pending duty without fabricating a claim',async()=>{
 const f=await automaticAckFixture();await f.stage();await f.repo.drainPendingWakeIntents();const r=f.duties()[0],evidence=outbox.recipientAcknowledgmentContract('reviewer@xv','reviewer-g1',r.effectId),result=outbox.acknowledgeRecipientDelivery('reviewer@xv','reviewer-g1',evidence.contract);
 expect(f.repo.getById(r.queueId)).toMatchObject({state:'done',claimedAt:null});const transitions=f.repo.transitionLog.listForQitem(r.queueId);expect(transitions.some(t=>t.transitionNote==='claimed')).toBe(false);expect(transitions.at(-1)).toMatchObject({actorSession:'watchdog@system',identityProvenance:'system:operator-authorized-coordination'});expect(transitions.at(-1)?.transitionNote).toContain(result.receiptId);expect(transitions.at(-1)?.transitionNote).toContain('reviewer@xv');const before=db.prepare('SELECT * FROM queue_transitions ORDER BY transition_id').all();outbox.acknowledgeRecipientDelivery('reviewer@xv','reviewer-g1',evidence.contract);expect(db.prepare('SELECT * FROM queue_transitions ORDER BY transition_id').all()).toEqual(before);
});
it.each(['observer','replay'])('existing genuine unclaimed acknowledgment reconciles through %s once without rereading or resending',async mode=>{
 const f=await automaticAckFixture();await f.stage();await f.repo.drainPendingWakeIntents();const r=f.duties()[0],evidence=outbox.recipientAcknowledgmentContract('reviewer@xv','reviewer-g1',r.effectId),hook=outbox.onRecipientAcknowledgment;outbox.onRecipientAcknowledgment=undefined;const actual=outbox.acknowledgeRecipientDelivery('reviewer@xv','reviewer-g1',evidence.contract);outbox.onRecipientAcknowledgment=hook;expect(f.repo.getById(r.queueId)?.state).toBe('pending');const receiptBefore=f.repo.getById(actual.receiptId),eventBefore=db.prepare("SELECT * FROM events WHERE type='outbox.recipient_acknowledged'").all();
 if(mode==='observer')await f.stage();else outbox.acknowledgeRecipientDelivery('reviewer@xv','reviewer-g1',evidence.contract);expect(f.repo.getById(r.queueId)).toMatchObject({state:'done',claimedAt:null});expect(f.repo.getById(actual.receiptId)).toEqual(receiptBefore);expect(db.prepare("SELECT * FROM events WHERE type='outbox.recipient_acknowledged'").all()).toEqual(eventBefore);expect(f.typed).toHaveLength(1);await f.stage();const transitions=f.repo.transitionLog.listForQitem(r.queueId);await f.stage();expect(f.repo.transitionLog.listForQitem(r.queueId)).toEqual(transitions);expect(f.duties()).toHaveLength(2);expect(f.typed).toHaveLength(1);
});
it.each(['proof','stale','expired','unknown-notice'])('saved actual receipt preserves pending duty protection on %s',async kind=>{
 const f=await automaticAckFixture(kind!=='unknown-notice');await f.stage();await f.repo.drainPendingWakeIntents();const r=f.duties()[0],evidence=outbox.recipientAcknowledgmentContract('reviewer@xv','reviewer-g1',r.effectId),hook=outbox.onRecipientAcknowledgment;outbox.onRecipientAcknowledgment=undefined;const actual=outbox.acknowledgeRecipientDelivery('reviewer@xv','reviewer-g1',evidence.contract);outbox.onRecipientAcknowledgment=hook;
 if(kind==='proof')db.prepare("UPDATE queue_items SET body='altered saved receipt' WHERE qitem_id=?").run(actual.receiptId);if(kind==='stale')db.prepare("UPDATE occupant_tenures SET generation_uuid='reviewer-new' WHERE node_id='reviewer@xv'").run();if(kind==='expired')vi.setSystemTime(r.deadline+1);const original=outbox.getById(r.effectId),typed=f.typed.length;await f.stage();await f.repo.drainPendingWakeIntents();expect(f.repo.getById(r.queueId)).toMatchObject({state:'pending',claimedAt:null});expect(outbox.getById(r.effectId)).toEqual(original);expect(f.typed).toHaveLength(typed);expect(f.duties()).toHaveLength(1);
});

it('blocked acknowledgment scan checks duplicate exact recipient sender preflight only once',async()=>{
 const f=await automaticAckFixture();for(let i=0;i<20;i++)outbox.recordDirectAttempt({senderSession:'operator-agent@kernel',destinationSession:'reviewer@xv',body:'Real duplicate protected recipient evidence '+i},'indeterminate');outbox.record({outboxId:'hold-input',senderSession:'reviewer@xv',destinationSession:'operator-agent@kernel',body:'UNKNOWN ordinary operation'});
 const probe=vi.spyOn(f.repo as any,'recipientAckProtection');await f.stage();expect(probe).toHaveBeenCalledTimes(1);expect(f.duties()).toHaveLength(0);
});
it('blocked acknowledgment memo invalidates current native generation within the readonly segment',async()=>{
 const f=await automaticAckFixture();outbox.record({outboxId:'hold-input',senderSession:'reviewer@xv',destinationSession:'operator-agent@kernel',body:'UNKNOWN ordinary operation'});const original=(f.repo as any).recipientAckProtection.bind(f.repo),generations:string[]=[];
 vi.spyOn(f.repo as any,'recipientAckProtection').mockImplementation((r:any)=>{generations.push(r.recipientGeneration);const result=original(r);if(generations.length===1)db.prepare("UPDATE occupant_tenures SET generation_uuid='reviewer-g2' WHERE node_id='reviewer@xv'").run();return result;});await f.stage();expect(generations).toEqual(['reviewer-g1','reviewer-g2']);expect(f.duties()).toHaveLength(0);
});
it('blocked acknowledgment memo clears across actual guard await and staged mutation for an independent recipient',async()=>{
 const f=await automaticAckFixture();outbox.record({outboxId:'hold-input',senderSession:'reviewer@xv',destinationSession:'operator-agent@kernel',body:'UNKNOWN ordinary operation'});outbox.recordDirectAttempt({senderSession:'operator-agent@kernel',destinationSession:'architect@xv',body:'Independent real report'},'indeterminate');outbox.recordDirectAttempt({senderSession:'operator-agent@kernel',destinationSession:'reviewer@xv',body:'Later real report after guard boundary'},'indeterminate');const guard=f.transport.deliveryGuard!,original=guard.lifecycle.bind(guard);let crossed=false;
 vi.spyOn(guard,'lifecycle').mockImplementation((nodes,fn)=>original(nodes,async()=>{await Promise.resolve();if(!crossed){crossed=true;outbox.markFailed('hold-input');}return fn();}));const probe=vi.spyOn(f.repo as any,'recipientAckProtection');await f.stage();expect(crossed).toBe(true);expect(f.duties().map(r=>r.recipient)).toEqual(['architect@xv','reviewer@xv']);expect(probe.mock.calls.filter(([r]:any)=>r.recipient==='reviewer@xv').length).toBeGreaterThan(1);expect(f.typed).toHaveLength(0);
});
it('indexed exact direct origin keeps first-attempt proof semantics and avoids event scan',()=>{
 const e=effect(),before=outbox.recipientAcknowledgmentContract('lead@xv','lead-g1',e.outboxId);const original=db.prepare("SELECT payload FROM events WHERE type='outbox.direct_attempt' ORDER BY seq LIMIT 1").get() as {payload:string};db.prepare("INSERT INTO events(type,payload) VALUES ('outbox.direct_attempt',?)").run(JSON.stringify({...JSON.parse(original.payload),bodySha256:'changed duplicate'}));const plan=db.prepare("EXPLAIN QUERY PLAN SELECT payload FROM events WHERE type='outbox.direct_attempt' AND json_extract(payload,'$.outboxId')=? ORDER BY seq LIMIT 1").all(e.outboxId) as Array<{detail:string}>;expect(plan.some(r=>r.detail.includes('SEARCH events USING INDEX idx_events_outbox_origin_seq'))).toBe(true);expect(outbox.recipientAcknowledgmentContract('lead@xv','lead-g1',e.outboxId)).toEqual(before);
});

it('terminal native acknowledgment duty gets one fresh exact reading successor without replay or testimony',async()=>{
 const f=await automaticAckFixture();await f.stage();await f.repo.drainPendingWakeIntents();const previous=f.duties()[0];f.repo.claim({qitemId:previous.queueId,destinationSession:'reviewer@xv',identityProvenance:'transport:v1',actorGeneration:'reviewer-g1'});f.repo.update({qitemId:previous.queueId,actorSession:'reviewer@xv',actorGeneration:'reviewer-g1',identityProvenance:'transport:v1',state:'failed',note:'Actual message not read; preserve UNKNOWN'});const old=f.repo.getById(previous.queueId),original=outbox.getById(previous.effectId);await f.stage();expect(f.duties()).toHaveLength(2);const next=f.duties()[1];expect(next.previousQueueId).toBe(previous.queueId);expect(next.queueId).not.toBe(previous.queueId);await f.stage();expect(f.duties()).toHaveLength(2);await f.repo.drainPendingWakeIntents();expect(f.typed).toHaveLength(2);expect(outbox.getById(previous.effectId)).toEqual(original);expect(f.repo.getById(previous.queueId)).toEqual(old);
 const evidence=outbox.recipientAcknowledgmentContract('reviewer@xv','reviewer-g1',next.effectId);outbox.acknowledgeRecipientDelivery('reviewer@xv','reviewer-g1',evidence.contract);expect(f.repo.getById(next.queueId)).toMatchObject({state:'done',claimedAt:null});expect(outbox.getById(previous.effectId)?.deliveryState).toBe('delivered');
});
it.each(['live','expired-claimed','unknown-notice','stale','drift'] as const)('acknowledgment successor preserves %s predecessor hold',async kind=>{
 const f=await automaticAckFixture(kind!=='unknown-notice');await f.stage();await f.repo.drainPendingWakeIntents();const previous=f.duties()[0];f.repo.claim({qitemId:previous.queueId,destinationSession:'reviewer@xv',identityProvenance:'transport:v1',actorGeneration:'reviewer-g1'});
 if(kind!=='live'&&kind!=='expired-claimed')f.repo.update({qitemId:previous.queueId,actorSession:'reviewer@xv',actorGeneration:'reviewer-g1',identityProvenance:'transport:v1',state:'failed',note:'Not read'});
 if(kind==='expired-claimed')vi.setSystemTime(previous.deadline+1);if(kind==='stale')db.prepare("UPDATE occupant_tenures SET generation_uuid='reviewer-g2' WHERE node_id='reviewer@xv'").run();if(kind==='drift')db.prepare("UPDATE queue_items SET body='changed' WHERE qitem_id=?").run(previous.queueId);
 const old=f.repo.getById(previous.queueId),target=outbox.getById(previous.effectId);await f.stage();await f.repo.drainPendingWakeIntents();expect(f.duties().filter((r:any)=>r.effectId===previous.effectId)).toHaveLength(1);expect(f.repo.getById(previous.queueId)).toEqual(old);expect(outbox.getById(previous.effectId)).toEqual(target);if(kind==='drift')expect(f.duties().some((r:any)=>r.effectId!==previous.effectId)).toBe(true);
});

it('expired unclaimed delivered reading duty gets distinct finite successor without fabricated disposition',async()=>{
 const f=await automaticAckFixture();await f.stage();await f.repo.drainPendingWakeIntents();const previous=f.duties()[0];vi.setSystemTime(previous.deadline+1);db.prepare('UPDATE coordinator_authority SET lease_until=?').run(Date.now()+1200000);const old=f.repo.getById(previous.queueId),target=outbox.getById(previous.effectId);await f.stage();const next=f.duties().find((r:any)=>r.previousQueueId===previous.queueId);expect(next).toBeTruthy();expect(f.repo.getById(previous.queueId)).toEqual(old);expect(f.repo.getById(next.queueId)).toMatchObject({state:'pending',claimedAt:null});expect(outbox.getById(previous.effectId)).toEqual(target);await f.repo.drainPendingWakeIntents();expect(outbox.getById('wake-intent-'+next.queueId)?.deliveryState).toBe('delivered');
});
it('successor fresh delivery rechecks predecessor known outcome and never retries UNKNOWN notice',async()=>{
 const f=await automaticAckFixture();await f.stage();await f.repo.drainPendingWakeIntents();const previous=f.duties()[0];f.repo.claim({qitemId:previous.queueId,destinationSession:'reviewer@xv',identityProvenance:'transport:v1',actorGeneration:'reviewer-g1'});f.repo.update({qitemId:previous.queueId,actorSession:'reviewer@xv',actorGeneration:'reviewer-g1',identityProvenance:'transport:v1',state:'failed',note:'Unread'});await f.stage();const next=f.duties()[1];db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run('wake-intent-'+previous.queueId);await f.repo.drainPendingWakeIntents();expect(f.typed).toHaveLength(1);expect(outbox.getById('wake-intent-'+next.queueId)?.deliveryState).toBe('failed');await f.stage();await f.repo.drainPendingWakeIntents();expect(f.typed).toHaveLength(1);expect(f.duties()).toHaveLength(2);
});

async function heldAuthoringFixture(terminalReceiptNotice=false,administrativeBoundary=false){
 const f=await automaticAckFixture(true,administrativeBoundary);db.prepare("UPDATE nodes SET runtime='codex' WHERE id='lead@xv'").run();db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('authoring-binding','lead@xv','lead@xv','%8')").run();const history=seedExactAckHistory(f,true);let priorNotice:string|undefined;
 if(terminalReceiptNotice){const report=outbox.recordDirectAttempt({senderSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'Actual unread immutable direct diagnostic'},'indeterminate');await f.stage();await f.repo.drainPendingWakeIntents();const duty=f.duties().find((r:any)=>r.effectId===report.outboxId);f.repo.claim({qitemId:duty.queueId,destinationSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1'});f.repo.update({qitemId:duty.queueId,actorSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1',state:'failed',note:'Original not read, actual native failure preserves UNKNOWN'});priorNotice='wake-intent-'+duty.queueId;db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run(priorNotice);}
 const authority=f.svc.get('xv')!,stage=()=> (f.recovery as any).stageCoordinatorRecovery('xv',authority.epoch,'operator-agent-g1','restore-current-held-history-binding','coordinator_held_history_recovery_required',Date.now()+1200000);const intake=stage();expect(db.prepare("SELECT 1 FROM coordinator_operations WHERE kind='coordinator-lifecycle-control' AND json_extract(receipt,'$.kind')='held-history-authoring'").get()).toBeUndefined();f.repo.claim({qitemId:intake,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});const controls=()=>db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='coordinator-lifecycle-control' AND json_extract(receipt,'$.kind')='held-history-authoring'").all().map((r:any)=>JSON.parse(r.receipt));return {...f,history,priorNotice,intake,authoringStage:stage,controls};
}
it('native Lead authoring duty actually wakes and requires genuine authored record Operator claim and binding',async()=>{
 const f=await heldAuthoringFixture(true),prior=outbox.getById(f.priorNotice!),before=f.typed.length;f.recovery.supervise('xv','auto-job');const r=f.controls()[0];expect(r.operatorIntakeId).toBe(f.intake);expect(r.effects).toHaveLength(1);expect(f.repo.getById(r.queueId)).toMatchObject({state:'pending',claimedAt:null});f.authoringStage();expect(f.controls()).toHaveLength(1);await f.repo.drainPendingWakeIntents();expect(f.typed).toHaveLength(before+1);expect(outbox.getById('wake-intent-'+r.queueId)?.deliveryState).toBe('delivered');expect(outbox.getById(f.priorNotice!)).toEqual(prior);expect(db.prepare("SELECT * FROM outbox_entries WHERE outbox_id='contained-ack-history'").get()).toEqual(f.history);
 expect(()=>f.repo.claim({qitemId:r.queueId,destinationSession:'lead@xv',actorGeneration:'wrong',identityProvenance:'transport:v1'})).toThrow('Exact current native Lead');f.repo.claim({qitemId:r.queueId,destinationSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1'});expect(()=>f.repo.update({qitemId:r.queueId,actorSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'})).toThrow('prose is not completion');
 const body=JSON.parse(f.repo.getById(r.queueId)!.body);await f.repo.create({qitemId:r.recordQueueId,sourceSession:'lead@xv',destinationSession:'operator-agent@kernel',body:JSON.stringify(body.recordBody),expiresAt:new Date(r.deadline).toISOString(),nudge:false,identityProvenance:'transport:v1'});expect(f.recovery.lifecycleControlCompleted(r.queueId)).toBe(false);f.repo.claim({qitemId:r.recordQueueId,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});expect(f.recovery.lifecycleControlCompleted(r.queueId)).toBe(false);
 const row=db.prepare('SELECT * FROM queue_items WHERE qitem_id=?').get(r.recordQueueId);f.svc.bindHeldHistoryRecovery('operator-agent@kernel','operator-agent-g1',{rigId:'xv',operationId:r.bindingOperationId,effects:r.effects,recovery:{queueId:r.recordQueueId,rowHash:historicalDigest(row)}});expect(f.recovery.lifecycleControlCompleted(r.queueId)).toBe(true);f.repo.update({qitemId:r.queueId,actorSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'});expect(f.repo.getById(r.queueId)?.state).toBe('done');expect(outbox.getById(f.priorNotice!)).toEqual(prior);expect(db.prepare("SELECT * FROM outbox_entries WHERE outbox_id='contained-ack-history'").get()).toEqual(f.history);
});
it.each(['generation','epoch','unknown','expiry','typing','cohort-drift','pending-direct','sending-direct','guarded-direct','unproven-indeterminate'] as const)('fixed Lead authoring delivery preserves %s guard and no unknown notice replay',async kind=>{
 const f=await heldAuthoringFixture();f.authoringStage();const r=f.controls()[0];expect(r).toBeTruthy();if(kind==='generation')db.prepare("UPDATE occupant_tenures SET generation_uuid='lead-g2' WHERE node_id='lead@xv'").run();if(kind==='epoch')db.prepare('UPDATE coordinator_authority SET epoch=epoch+1').run();if(kind==='unknown')outbox.record({outboxId:'wake-intent-unrelated-unknown-control',senderSession:'watchdog@system',destinationSession:'lead@xv',body:'Unexplained executable control'});if(['pending-direct','sending-direct','guarded-direct','unproven-indeterminate'].includes(kind)){const e=kind==='unproven-indeterminate'?outbox.record({outboxId:'unproven-authoring-debt',senderSession:'lead@xv',destinationSession:'operator-agent@kernel',body:'No direct origin'}):outbox.recordDirectAttempt({senderSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'Related actual diagnostic'},'indeterminate');if(kind==='pending-direct'||kind==='sending-direct')db.prepare('UPDATE outbox_entries SET delivery_state=? WHERE outbox_id=?').run(kind==='pending-direct'?'pending':'sending',e.outboxId);if(kind==='guarded-direct')db.prepare("UPDATE outbox_entries SET guard_binding='{}' WHERE outbox_id=?").run(e.outboxId);if(kind==='unproven-indeterminate')db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run(e.outboxId);}if(kind==='expiry')vi.setSystemTime(r.deadline+1);if(kind==='typing')db.prepare("INSERT INTO seat_delivery_guards(node_id,desired,effective,actor,reason,changed_at) VALUES ('lead@xv',1,1,'test','protected',datetime('now'))").run();if(kind==='cohort-drift')db.prepare("UPDATE coordinator_operations SET receipt=json_set(receipt,'$.effects[0].rowHash','drift') WHERE operation_id=?").run(r.queueId);await f.repo.drainPendingWakeIntents();expect(f.typed).toHaveLength(0);expect(outbox.getById('wake-intent-'+r.queueId)?.deliveryState).toBe('failed');expect(f.recovery.lifecycleControlCompleted(r.queueId)).toBe(false);f.authoringStage();await f.repo.drainPendingWakeIntents();expect(f.typed).toHaveLength(0);expect(f.controls()).toHaveLength(1);
});
it('unknown started Lead authoring notice is held once while independent native receipt work continues',async()=>{
 const f=await heldAuthoringFixture();f.authoringStage();const r=f.controls()[0];db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run('wake-intent-'+r.queueId);f.authoringStage();await f.repo.drainPendingWakeIntents();expect(f.typed).toHaveLength(0);expect(f.controls()).toHaveLength(1);expect(outbox.getById('wake-intent-'+r.queueId)?.deliveryState).toBe('indeterminate');await f.stage();expect(f.duties().some((r:any)=>r.recipient==='reviewer@xv')).toBe(true);await f.repo.drainPendingWakeIntents();expect(f.typed).toHaveLength(1);expect(outbox.getById('wake-intent-'+r.queueId)?.deliveryState).toBe('indeterminate');
});

it.each(['failed','canceled'] as const)('fixed native authoring custody refuses every unclaim and supports claimant own %s expiry closure',async state=>{
 const f=await heldAuthoringFixture();f.authoringStage();const r=f.controls()[0];await f.repo.drainPendingWakeIntents();f.repo.claim({qitemId:r.queueId,destinationSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1'});const before=f.repo.getById(r.queueId),transitions=f.repo.transitionLog.listForQitem(r.queueId),history=db.prepare("SELECT * FROM outbox_entries WHERE outbox_id='contained-ack-history'").get();
 for(const actor of ['operator-agent@kernel','reviewer@xv','lead@xv'])expect(()=>f.repo.unclaim(r.queueId,actor,'Cannot clear another administrative claim','transport:v1')).toThrow('Fixed authoring custody cannot be unclaimed');expect(f.repo.getById(r.queueId)).toEqual(before);expect(f.repo.transitionLog.listForQitem(r.queueId)).toEqual(transitions);
 expect(()=>f.repo.update({qitemId:r.queueId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state})).toThrow('Exact current native Lead claimant');vi.setSystemTime(r.deadline+1);f.repo.update({qitemId:r.queueId,actorSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1',state,transitionNote:'Actual claimant reports expired finite authoring duty; preserve UNKNOWN and prior custody'});expect(f.repo.getById(r.queueId)).toMatchObject({state,claimedAt:before!.claimedAt});expect(db.prepare("SELECT * FROM outbox_entries WHERE outbox_id='contained-ack-history'").get()).toEqual(history);expect(db.prepare("SELECT 1 FROM coordinator_operations WHERE kind='held-history-recovery-binding'").get()).toBeUndefined();
});

it('actual native initial authoring claim consumes own exact UNKNOWN notice without inferring delivery or resending',async()=>{
 const f=await heldAuthoringFixture();f.authoringStage();const r=f.controls()[0],noticeId='wake-intent-'+r.queueId;db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run(noticeId);const notice=outbox.getById(noticeId),history=db.prepare("SELECT * FROM outbox_entries WHERE outbox_id='contained-ack-history'").get();expect(f.recovery.validLifecycleControlWake('watchdog@system','lead@xv',r.queueId)).toBe(false);expect(()=>f.repo.claim({qitemId:r.queueId,destinationSession:'reviewer@xv',actorGeneration:'reviewer-g1',identityProvenance:'transport:v1'})).toThrow('Exact current native Lead');f.repo.claim({qitemId:r.queueId,destinationSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1'});expect(f.repo.getById(r.queueId)?.state).toBe('in-progress');expect(outbox.getById(noticeId)).toEqual(notice);expect(f.recovery.validLifecycleControlWake('watchdog@system','lead@xv',r.queueId)).toBe(false);expect(f.recovery.lifecycleControlCompleted(r.queueId)).toBe(false);await f.repo.drainPendingWakeIntents();expect(f.typed).toHaveLength(0);expect(outbox.getById(noticeId)).toEqual(notice);expect(db.prepare("SELECT * FROM outbox_entries WHERE outbox_id='contained-ack-history'").get()).toEqual(history);
});
it.each(['generation','missing-native','expired','hash','unrelated-unknown'] as const)('native initial UNKNOWN authoring claim refuses %s and preserves exact custody',async kind=>{
 const f=await heldAuthoringFixture();f.authoringStage();const r=f.controls()[0],noticeId='wake-intent-'+r.queueId;db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run(noticeId);if(kind==='expired')vi.setSystemTime(r.deadline+1);if(kind==='hash')db.prepare("UPDATE outbox_entries SET body='altered' WHERE outbox_id=?").run(noticeId);if(kind==='unrelated-unknown')outbox.record({outboxId:'wake-intent-unrelated-live-protected',senderSession:'watchdog@system',destinationSession:'lead@xv',body:'Protected unrelated control'});const before=f.repo.getById(r.queueId),notice=outbox.getById(noticeId);expect(()=>f.repo.claim({qitemId:r.queueId,destinationSession:'lead@xv',actorGeneration:kind==='generation'?'lead-wrong':'lead-g1',identityProvenance:kind==='missing-native'?null:'transport:v1'})).toThrow('Exact current native Lead');expect(f.repo.getById(r.queueId)).toEqual(before);expect(outbox.getById(noticeId)).toEqual(notice);expect(f.recovery.validLifecycleControlWake('watchdog@system','lead@xv',r.queueId)).toBe(false);
});
async function heldRecordFollowthrough(){const f=await heldAuthoringFixture(false,true);db.prepare("UPDATE nodes SET runtime='codex' WHERE id='operator-agent@kernel'").run();db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('operator-followthrough','operator-agent@kernel','operator-agent@kernel','%9')").run();f.authoringStage();const r=f.controls()[0];await f.repo.drainPendingWakeIntents();f.repo.claim({qitemId:r.queueId,destinationSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1'});const b=JSON.parse(f.repo.getById(r.queueId)!.body);await f.repo.create({qitemId:r.recordQueueId,sourceSession:'lead@xv',destinationSession:'operator-agent@kernel',body:JSON.stringify(b.recordBody),expiresAt:new Date(r.deadline).toISOString(),nudge:false,identityProvenance:'transport:v1'});return {...f,r};}
it('held history actual record automatically yields once-only genuine Operator pickup and exact binding',async()=>{const f=await heldRecordFollowthrough(),before=f.typed.length;f.recovery.supervise('xv','auto-job');const p=db.prepare("SELECT receipt FROM coordinator_operations WHERE json_extract(receipt,'$.kind')='held-history-pickup'").get() as any;expect(p).toBeTruthy();const r=JSON.parse(p.receipt);f.recovery.supervise('xv','auto-job');expect(db.prepare("SELECT count(*) n FROM coordinator_operations WHERE json_extract(receipt,'$.kind')='held-history-pickup'").get()).toMatchObject({n:1});await f.repo.drainPendingWakeIntents();expect(outbox.getById('wake-intent-'+r.queueId)).toMatchObject({deliveryState:'delivered'});expect(f.typed.length).toBe(before+1);expect(()=>f.repo.claim({qitemId:r.queueId,destinationSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1'})).toThrow();f.repo.claim({qitemId:r.queueId,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});f.repo.claim({qitemId:f.r.recordQueueId,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});const row=db.prepare('SELECT * FROM queue_items WHERE qitem_id=?').get(f.r.recordQueueId);f.svc.bindHeldHistoryRecovery('operator-agent@kernel','operator-agent-g1',{rigId:'xv',operationId:f.r.bindingOperationId,effects:f.r.effects,recovery:{queueId:f.r.recordQueueId,rowHash:historicalDigest(row)}});f.repo.update({qitemId:f.r.queueId,actorSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'});expect(f.recovery.lifecycleControlCompleted(r.queueId)).toBe(true);f.repo.update({qitemId:r.queueId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'});expect(db.prepare("SELECT * FROM outbox_entries WHERE outbox_id='contained-ack-history'").get()).toEqual(f.history);});
it.each(['foreign-record','unknown-pickup','expiry','generation'] as const)('held history pickup preserves %s fence',async kind=>{const f=await heldRecordFollowthrough();if(kind==='foreign-record')db.prepare("UPDATE queue_transitions SET actor_session='reviewer@xv' WHERE qitem_id=? AND transition_note='created'").run(f.r.recordQueueId);if(kind==='generation')db.prepare("UPDATE occupant_tenures SET generation_uuid='operator-g2' WHERE node_id='operator-agent@kernel'").run();if(kind==='expiry')vi.setSystemTime(f.r.deadline+1);if(kind==='generation'){expect(()=>f.recovery.supervise('xv','auto-job')).toThrow('Current Operator job and plan required');return;}f.recovery.supervise('xv','auto-job');const p=db.prepare("SELECT receipt FROM coordinator_operations WHERE json_extract(receipt,'$.kind')='held-history-pickup'").get() as any;if(kind==='unknown-pickup'){expect(p).toBeTruthy();const r=JSON.parse(p.receipt);db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run('wake-intent-'+r.queueId);await f.repo.drainPendingWakeIntents();expect(f.recovery.validLifecycleControlWake('watchdog@system','operator-agent@kernel',r.queueId)).toBe(false);expect(outbox.getById('wake-intent-'+r.queueId)?.deliveryState).toBe('indeterminate');}else expect(p).toBeUndefined();});
it('held history expiry preserves claimed duty and record until genuine native terminal disposition then one successor',async()=>{const f=await heldRecordFollowthrough();db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run('wake-intent-'+f.r.queueId);const original=outbox.getById('wake-intent-'+f.r.queueId);vi.setSystemTime(f.r.deadline+1);f.recovery.supervise('xv','auto-job');expect(f.controls()).toHaveLength(1);const p=db.prepare("SELECT receipt FROM coordinator_operations WHERE json_extract(receipt,'$.kind')='held-history-retirement'").get() as any;expect(p).toBeTruthy();const t=JSON.parse(p.receipt);await f.repo.drainPendingWakeIntents();f.repo.claim({qitemId:t.queueId,destinationSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1'});expect(()=>f.repo.update({qitemId:f.r.queueId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'failed'})).toThrow();f.repo.update({qitemId:f.r.queueId,actorSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1',state:'failed'});f.recovery.supervise('xv','auto-job');expect(f.controls()).toHaveLength(1);const opRetirement=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE json_extract(receipt,'$.kind')='held-history-retirement' AND json_extract(receipt,'$.targetQueueId')=?").get(f.r.recordQueueId) as any).receipt);await f.repo.drainPendingWakeIntents();f.repo.claim({qitemId:opRetirement.queueId,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});f.repo.update({qitemId:f.r.recordQueueId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'failed'});f.repo.update({qitemId:opRetirement.queueId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'});f.repo.update({qitemId:t.queueId,actorSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'});f.recovery.supervise('xv','auto-job');expect(f.controls()).toHaveLength(2);f.recovery.supervise('xv','auto-job');expect(f.controls()).toHaveLength(2);expect(outbox.getById('wake-intent-'+f.r.queueId)).toEqual(original);expect(f.repo.getById(f.r.recordQueueId)?.claimedAt).toBeNull();});

it('held history retirement staged after a plan revision carries current issue provenance and is sendable',async()=>{const f=await heldRecordFollowthrough();db.prepare("UPDATE coordinator_operations SET receipt=replace(receipt,json_extract(receipt,'$.revision'),'post-issue-plan-r2') WHERE kind='coordination-plan'").run();expect(f.recovery.plan('xv')!.revision).toBe('post-issue-plan-r2');db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run('wake-intent-'+f.r.queueId);vi.setSystemTime(f.r.deadline+1);f.recovery.supervise('xv','auto-job');const t=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE json_extract(receipt,'$.kind')='held-history-retirement' AND json_extract(receipt,'$.targetQueueId')=?").get(f.r.queueId) as any).receipt);expect(t).toMatchObject({kind:'held-history-retirement',planRevision:'post-issue-plan-r2',issuedAt:f.r.deadline+1,targetQueueId:f.r.queueId});expect(f.repo.getById(t.queueId)?.sourceSession).toBe('watchdog@system');expect(f.recovery.dutyFacts(t.queueId)).toMatchObject({send:true,claim:true});expect(f.recovery.validLifecycleControlWake('watchdog@system','lead@xv',t.queueId)).toBe(true);expect(f.repo.getById(t.queueId)?.state).toBe('pending');expect(f.repo.getById(f.r.queueId)?.claimedAt).toBeTruthy();});
it('held history claimed pickup custody survives expiry and prevents competing successor',async()=>{const f=await heldRecordFollowthrough();f.recovery.supervise('xv','auto-job');const p=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE json_extract(receipt,'$.kind')='held-history-pickup'").get() as any).receipt);await f.repo.drainPendingWakeIntents();f.repo.claim({qitemId:p.queueId,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});vi.setSystemTime(f.r.deadline+1);f.repo.update({qitemId:f.r.queueId,actorSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1',state:'failed'});f.repo.update({qitemId:f.r.recordQueueId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'failed'});const before=f.repo.getById(p.queueId);f.recovery.supervise('xv','auto-job');expect(f.controls()).toHaveLength(1);expect(f.repo.getById(p.queueId)).toEqual(before);expect(()=>f.repo.update({qitemId:p.queueId,actorSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1',state:'failed'})).toThrow();const t=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE json_extract(receipt,'$.kind')='held-history-retirement' AND json_extract(receipt,'$.targetQueueId')=?").get(p.queueId) as any).receipt);await f.repo.drainPendingWakeIntents();f.repo.claim({qitemId:t.queueId,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});f.repo.update({qitemId:p.queueId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'failed'});f.repo.update({qitemId:t.queueId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'});f.recovery.supervise('xv','auto-job');expect(f.controls()).toHaveLength(2);});

it('held history expired unclaimed UNKNOWN pickup has genuine failure-only owner disposition and no replay',async()=>{const f=await heldRecordFollowthrough();f.recovery.supervise('xv','auto-job');const p=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE json_extract(receipt,'$.kind')='held-history-pickup'").get() as any).receipt);db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run('wake-intent-'+p.queueId);const unknown=outbox.getById('wake-intent-'+p.queueId);vi.setSystemTime(f.r.deadline+1);expect(()=>f.repo.claim({qitemId:p.queueId,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'})).toThrow();f.repo.update({qitemId:f.r.queueId,actorSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1',state:'failed'});f.repo.update({qitemId:f.r.recordQueueId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'failed'});f.recovery.supervise('xv','auto-job');const t=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE json_extract(receipt,'$.kind')='held-history-retirement' AND json_extract(receipt,'$.targetQueueId')=?").get(p.queueId) as any).receipt);await f.repo.drainPendingWakeIntents();expect(outbox.getById('wake-intent-'+t.queueId)?.deliveryState).toBe('delivered');expect(()=>f.repo.update({qitemId:p.queueId,actorSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1',state:'failed'})).toThrow();f.repo.claim({qitemId:t.queueId,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});f.repo.update({qitemId:p.queueId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'failed'});expect(f.repo.getById(p.queueId)?.claimedAt).toBeNull();f.repo.update({qitemId:t.queueId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'});f.recovery.supervise('xv','auto-job');expect(f.controls()).toHaveLength(2);expect(outbox.getById('wake-intent-'+p.queueId)).toEqual(unknown);f.recovery.supervise('xv','auto-job');expect(f.controls()).toHaveLength(2);});
it.each(['pending','sending','delivered','indeterminate','failed'] as const)('shared duty facets retirement terminal-first native claim preserves %s notice',async noticeState=>{const f=await heldRecordFollowthrough();vi.setSystemTime(f.r.deadline+1);f.recovery.supervise('xv','auto-job');const t=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE json_extract(receipt,'$.kind')='held-history-retirement' AND json_extract(receipt,'$.targetQueueId')=?").get(f.r.queueId) as any).receipt);f.repo.update({qitemId:f.r.queueId,actorSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1',state:'failed'});db.prepare('UPDATE outbox_entries SET delivery_state=? WHERE outbox_id=?').run(noticeState,'wake-intent-'+t.queueId);const notice=outbox.getById('wake-intent-'+t.queueId);expect(f.recovery.validLifecycleControlWake('watchdog@system','lead@xv',t.queueId)).toBe(false);f.repo.claim({qitemId:t.queueId,destinationSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1'});f.repo.update({qitemId:t.queueId,actorSession:'lead@xv',actorGeneration:'lead-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'});expect(f.repo.getById(t.queueId)?.state).toBe('done');expect(outbox.getById('wake-intent-'+t.queueId)).toEqual(notice);});
