import {describe,it,expect} from "vitest";
import Database from "better-sqlite3";
import {seed} from "./helpers/coordinator-fixture.js";
import {QueueRepository} from "../src/domain/queue-repository.js";
import {EventBus} from "../src/domain/event-bus.js";
import {OutboxHandler} from "../src/domain/outbox-handler.js";
import {runWakeLadderTick} from "../src/domain/queue-wake-ladder.js";
async function fixture(aggregate=false,reverse=false){ const db=new Database(":memory:");seed(db);db.prepare("INSERT INTO self_host_identity VALUES(1,'fixture-host','now','now')").run();const repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>repo.coordinatorAuthority.generation(s)});repo.attachOutbox(new OutboxHandler(db));
for(const [id,dest] of (reverse?[["healthy","worker@other"],["protected","builder@xv"]]:[["protected","builder@xv"],["healthy","worker@other"]])){await repo.create({qitemId:id,sourceSession:"sender@external",destinationSession:dest,body:id,nudge:false});db.prepare("UPDATE queue_items SET handed_off_from='origin',last_nudge_result='failed:offline',last_nudge_attempt=NULL WHERE qitem_id=?").run(id);}
if(aggregate){await repo.create({qitemId:"resolved",sourceSession:"sender@external",destinationSession:"worker@other",body:"resolved",nudge:false});await repo.update({qitemId:"resolved",actorSession:"sender@external",state:"done",closureReason:"no-follow-on"});db.prepare("UPDATE queue_items SET tags=? WHERE qitem_id='protected'").run(JSON.stringify(["wake-escalation","recovery-for:resolved"]));}
db.prepare(`INSERT INTO seat_dispatch_reservations(reservation_id,operation_id,node_id,session_name,predecessor_generation,predecessor_native_id,actor_session,actor_generation,request_hash,expected_json,frozen_snapshot,state,created_at,updated_at) VALUES('r','op','builder@xv','builder@xv','builder-g1','native','operator-agent@kernel','operator-agent-g1','hash','{}','{}','reserved','now','now')`).run();return {db,repo};}
describe("wake ladder isolates protected scopes",()=>{
it("reserved first retry cannot starve later healthy retry; current Operator notice actually wakes and claims",async()=>{const {db,repo}=await fixture();try{const original=db.prepare("SELECT * FROM queue_items WHERE qitem_id='protected'").get();let claimed="";db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('opbinding','operator-agent@kernel','operator-agent@kernel','%1')").run();repo.attachTransport({send:async(_dest,_body,opts:any)=>{if(opts?.queueAssignmentId?.startsWith("qitem-wake-ladder-control")){claimed=opts.queueAssignmentId;repo.claim({qitemId:claimed,destinationSession:"operator-agent@kernel",identityProvenance:"transport:v1"});}return {ok:true,verified:true};}} as any);const result=await runWakeLadderTick({db,queueRepo:repo,attemptWake:async(id)=>{repo.recordNudgeAttempt(id,"verified");return "verified";}});expect(result.outcome).toBe("failed");expect(result.actions.some(a=>a.qitemId==="healthy"&&a.action==="retry")).toBe(true);expect(db.prepare("SELECT * FROM queue_items WHERE qitem_id='protected'").get()).toEqual(original);expect(result.refusals?.[0].recoveryError).toBeUndefined();expect(claimed).toBeTruthy();expect(repo.getById(claimed)?.state).toBe("in-progress");const body=JSON.parse(repo.getById(claimed)!.body);expect(body.recipientGeneration).toBe("operator-agent-g1");expect(body.returnPath.queueId).toBe(claimed);const again=await runWakeLadderTick({db,queueRepo:repo,attemptWake:async(id)=>{repo.recordNudgeAttempt(id,"verified");return "verified";}});expect(again.refusals?.[0].recoveryQueueId).toBe(claimed);}finally{db.close();}});
it("protected escalation creation refusal preserves healthy destination actions",async()=>{const {db,repo}=await fixture();try{const result=await runWakeLadderTick({db,queueRepo:repo,retryCap:0,resolveOrchestrator:s=>s==="builder@xv"?"builder@xv@fixture-host":"lead@xv",attemptWake:async()=>"verified"});expect(result.outcome).toBe("failed");expect(result.actions.some(a=>a.qitemId==="healthy")).toBe(true);expect(repo.getById("protected")?.state).toBe("pending");}finally{db.close();}});
it("reserved aggregate retirement refuses locally then healthy retry commits",async()=>{const {db,repo}=await fixture(true);try{const result=await runWakeLadderTick({db,queueRepo:repo,attemptWake:async(id)=>{repo.recordNudgeAttempt(id,"verified");return "verified";}});expect(result.refusals?.some(r=>r.phase==="aggregate-retirement")).toBe(true);expect(result.actions.some(a=>a.qitemId==="healthy")).toBe(true);expect(repo.getById("protected")?.state).toBe("pending");}finally{db.close();}});
it("later refusal retains prior healthy committed action with absent Operator boundary",async()=>{const {db,repo}=await fixture(false,true);try{db.prepare("DELETE FROM occupant_tenures WHERE node_id='operator-agent@kernel'").run();const result=await runWakeLadderTick({db,queueRepo:repo,attemptWake:async(id)=>{repo.recordNudgeAttempt(id,"verified");return "verified";}});expect(result.actions[0].qitemId).toBe("healthy");expect(result.refusals?.[0].recoveryError).toContain("Actual current Operator");expect(repo.getById("healthy")?.lastNudgeResult).toBe("verified");}finally{db.close();}});

it("late orchestrator reservation preserves committed aggregate receipt and later healthy action",async()=>{const {db,repo}=await fixture();try{let once=false;const result=await runWakeLadderTick({db,queueRepo:repo,retryCap:0,resolveOrchestrator:s=>s==="builder@xv"?"lead@xv":"peer@xv",attemptWake:async(id,target)=>{if(!once&&target==="lead@xv"){once=true;db.prepare(`INSERT INTO seat_dispatch_reservations(reservation_id,operation_id,node_id,session_name,predecessor_generation,predecessor_native_id,actor_session,actor_generation,request_hash,expected_json,frozen_snapshot,state,created_at,updated_at) VALUES('late','late-op','lead@xv','lead@xv','lead-g1','nativelead','operator-agent@kernel','operator-agent-g1','hash','{}','{}','reserved','now','now')`).run();}repo.recordNudgeAttempt(id,"verified");return "verified";}});const receipt=result.aggregates?.find(a=>a.destination==="lead@xv");expect(receipt?.action).toBe("created");expect(repo.getById(receipt!.qitemId)?.state).toBe("pending");expect(result.actions.some(a=>a.qitemId==="healthy")).toBe(true);expect(result.refusals?.[0].recoveryQueueId).toBeTruthy();expect(repo.getById(result.refusals![0].recoveryQueueId!)?.destinationSession).toBe("operator-agent@kernel");}finally{db.close();}});

});
