import {describe,it,expect} from 'vitest';
import {createHash} from 'node:crypto';
import Database from 'better-sqlite3';
import {Hono} from 'hono';
import {seed} from './helpers/coordinator-fixture.js';
import {QueueRepository} from '../src/domain/queue-repository.js';
import {EventBus} from '../src/domain/event-bus.js';
import {OutboxHandler} from '../src/domain/outbox-handler.js';
import {SeatDeliveryGuard} from '../src/domain/seat-delivery-guard.js';
import {inspectQueueRecovery} from '../src/domain/queue-recovery-inspection.js';
import {sourceFacts,runWakeLadderTick} from '../src/domain/queue-wake-ladder.js';
import {queueRoutes} from '../src/routes/queue.js';
const OP='operator-agent@kernel',gen='operator-agent-g1',sha=(s:string)=>createHash('sha256').update(s).digest('hex');
async function fixture(protectedSeat=true,author="owner@local"){
 const db=new Database(':memory:');seed(db);db.prepare("INSERT INTO self_host_identity VALUES(1,'fixture-host','now','now')").run();
 const repo=new QueueRepository(db,new EventBus(db),{resolveOccupantGeneration:s=>repo.coordinatorAuthority.generation(s)}),outbox=new OutboxHandler(db);repo.attachOutbox(outbox);
 db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES('op',? ,?,'%1')").run(OP,OP);
 const guard=new SeatDeliveryGuard(db,s=>{const id=s.endsWith('@fixture-host')?s.slice(0,-13):s;const n=db.prepare('SELECT id FROM nodes WHERE id=?').get(id) as {id:string}|undefined;return n?{nodeId:n.id,session:id,occupant:repo.coordinatorAuthority.generation(id),pane:'%1'}:null;});
 await repo.create({qitemId:'original',sourceSession:'owner@local',destinationSession:'builder@xv',body:'valuable original',nudge:false,identityProvenance:'claimed:v1'});
 repo.claim({qitemId:'original',destinationSession:'builder@xv',identityProvenance:'transport:v1'});
 await repo.create({qitemId:'old-notice',sourceSession:'owner@local',destinationSession:OP,body:'valuable blocked guard duty',nudge:false,identityProvenance:'claimed:v1'});repo.claim({qitemId:'old-notice',destinationSession:OP,identityProvenance:'transport:v1'});await repo.update({qitemId:'old-notice',actorSession:OP,state:'blocked',blockedOn:'auth:existing-boundary',wakeAfterSeconds:1800});
 if(protectedSeat)db.prepare(`INSERT INTO seat_dispatch_reservations(reservation_id,operation_id,node_id,session_name,predecessor_generation,predecessor_native_id,actor_session,actor_generation,request_hash,expected_json,frozen_snapshot,state,created_at,updated_at) VALUES('r','reserved-op','builder@xv','builder@xv','builder-g1','native',?,?, 'hash','{}','{}','started','now','now')`).run(OP,gen);
 const input={qitemId:'original',sourceFactsHash:sha(sourceFacts(repo.getById('original')!)),operationId:'inspect-one',authorizationId:'auth-inspect'};
 const body={kind:'queue-recovery-inspection-authorization.v1',purpose:'inspect-protected-obligation',...{qitemId:input.qitemId,sourceFactsHash:input.sourceFactsHash,operationId:input.operationId},operatorGeneration:gen,expiresAt:Date.now()+600000};
 await repo.create({qitemId:input.authorizationId,sourceSession:author,destinationSession:OP,body:JSON.stringify(body),nudge:false,identityProvenance:'transport:v1'});repo.claim({qitemId:input.authorizationId,destinationSession:OP,identityProvenance:'transport:v1'});
 const sends:string[]=[];repo.attachTransport({send:async(_d:string,_b:string,o:any)=>{sends.push(o.queueAssignmentId);return {ok:true,verified:false};}} as any);
 const protectedRaw=()=>({original:db.prepare("SELECT * FROM queue_items WHERE qitem_id='original'").get(),old:db.prepare("SELECT * FROM queue_items WHERE qitem_id='old-notice'").get(),reservation:db.prepare("SELECT * FROM seat_dispatch_reservations").all(),resources:db.prepare('SELECT * FROM coordinator_resources').all()});
 const parents=()=>db.prepare("SELECT * FROM queue_items WHERE json_valid(body) AND json_extract(body,'$.inspection.operationId')='inspect-one'").all();
 return {db,repo,guard,outbox,input,sends,protectedRaw,parents};
}
describe('genuine Operator recovery inspection',()=>{
 it('real reservation refusal commits distinct parent atomically; overdue child→actual Operator claim; original unchanged',async()=>{const f=await fixture();try{
  const before=f.protectedRaw();const r=await inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input);expect(r.disposition).toBe('created-control');expect(r.protectionCode).toBe('seat_dispatch_reserved');expect(r.pickup).toBe('unverified');expect(f.protectedRaw()).toEqual(before);expect(f.parents()).toHaveLength(1);
  const parent=f.repo.getById(r.recoveryQueueId!)!;expect(parent.expiresAt).toBeTruthy();expect(JSON.parse(parent.body).inspection.authorizationId).toBe('auth-inspect');const intent=f.outbox.getById('wake-intent-'+parent.qitemId);expect(intent?.deliveryState).toBe('indeterminate');
  await inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input);expect(f.parents()).toHaveLength(1);expect(f.sends).toHaveLength(1);expect(f.outbox.getById('wake-intent-'+parent.qitemId)).toEqual(intent);
  f.repo.attachTransport({send:async(_d:string,_b:string,o:any)=>{f.repo.claim({qitemId:o.queueAssignmentId,destinationSession:OP,identityProvenance:'transport:v1'});return {ok:true,verified:true};}} as any);
  const tick=await runWakeLadderTick({db:f.db,queueRepo:f.repo,now:new Date(Date.parse(parent.expiresAt!)+1)});const child=tick.controls?.find(x=>x.qitemId===parent.qitemId)?.recoveryQueueId;expect(child).toBeTruthy();expect(f.repo.getById(child!)?.state).toBe('in-progress');expect(f.protectedRaw()).toEqual(before);
 }finally{f.db.close();}});
 it('unprotected real obligation creates no control or wake',async()=>{const f=await fixture(false);try{const r=await inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input);expect(r.disposition).toBe('unprotected');expect(f.parents()).toHaveLength(0);expect(f.sends).toHaveLength(0);}finally{f.db.close();}});
 it.each(['expired','unclaimed','wrong-purpose','wrong-generation','wrong-hash'])('refuses %s exact authorization without effects',async mode=>{const f=await fixture();try{const raw=f.repo.getById('auth-inspect')!,b=JSON.parse(raw.body);if(mode==='expired')b.expiresAt=Date.now()-1;if(mode==='wrong-purpose')b.purpose='dispose-work';if(mode==='wrong-generation')b.operatorGeneration='g2';if(mode==='wrong-hash')b.sourceFactsHash='f'.repeat(64);if(mode==='unclaimed')f.db.prepare("UPDATE queue_items SET state='pending' WHERE qitem_id='auth-inspect'").run();else f.db.prepare("UPDATE queue_items SET body=? WHERE qitem_id='auth-inspect'").run(JSON.stringify(b));const before=f.protectedRaw();await expect(inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input)).rejects.toThrow();expect(f.parents()).toHaveLength(0);expect(f.protectedRaw()).toEqual(before);}finally{f.db.close();}});
 it('rechecks generation/expiry after actual serialized wait and refuses no effect',async()=>{const f=await fixture();try{let release!:()=>void;let entered!:()=>void;const inside=new Promise<void>(r=>entered=r);const held=f.guard.inspectProtection('builder@xv',async()=>{entered();await new Promise<void>(r=>release=r);});await inside;const pending=inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input);f.db.prepare("UPDATE occupant_tenures SET generation_uuid='g2' WHERE node_id=?").run(OP);release();await held;await expect(pending).rejects.toThrow();expect(f.parents()).toHaveLength(0);}finally{f.db.close();}});
 it('refuses changed source or changed protection replay instead of remint',async()=>{const f=await fixture();try{await inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input);f.db.prepare("UPDATE seat_dispatch_reservations SET state='released' WHERE reservation_id='r'").run();await expect(inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input)).rejects.toThrow();expect(f.parents()).toHaveLength(1);expect(f.sends).toHaveLength(1);}finally{f.db.close();}});
 it('transaction failure rolls back parent and intent',async()=>{const f=await fixture();try{f.db.exec("CREATE TRIGGER fail_notice BEFORE INSERT ON outbox_entries WHEN NEW.sender_session='watchdog@system' BEGIN SELECT RAISE(ABORT,'injected-intent-failure');END");await expect(inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input)).rejects.toThrow();expect(f.parents()).toHaveLength(0);expect(f.sends).toHaveLength(0);}finally{f.db.close();}});
 it.each(['protection','tuple','metadata-expiry','clock-expiry'])('refuses late %s drift at atomic boundary',async mode=>{const f=await fixture();try{
  const original=f.guard.inspectProtection.bind(f.guard);f.guard.inspectProtection=async(name,fn)=>original(name,(target,protection)=>{
   if(mode==='protection')f.db.prepare("UPDATE seat_dispatch_reservations SET updated_at='later' WHERE reservation_id='r'").run();
   if(mode==='tuple'){const targetOriginal=f.guard.target.bind(f.guard);f.guard.target=s=>({...targetOriginal(s),pane:'%9'});}
   if(mode==='metadata-expiry')f.db.prepare("UPDATE queue_items SET expires_at='2000-01-01T00:00:00Z' WHERE qitem_id='auth-inspect'").run();
   return fn(target,protection);
  });
  await expect(inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input,mode==='clock-expiry'?()=>new Date(Date.now()+700000):()=>new Date())).rejects.toThrow();expect(f.parents()).toHaveLength(0);expect(f.sends).toHaveLength(0);
 }finally{f.db.close();}});
 it('operator protection allows no input but reports retained commitment on delivery failure',async()=>{const f=await fixture();try{
  f.repo.deliverWakeForSuccessor=async()=>{throw Error('delivery failed');};const before=f.protectedRaw();const result=await inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input);expect(result.deliveryError).toBe('inspection_control_delivery_failed');expect(result.created).toBe(true);expect(f.parents()).toHaveLength(1);expect(f.protectedRaw()).toEqual(before);
 }finally{f.db.close();}});
 it('concurrent same-operation inspections produce one parent and one send',async()=>{const f=await fixture();try{const result=await Promise.all([inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input),inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input)]);expect(result.filter(x=>x.created)).toHaveLength(1);expect(f.parents()).toHaveLength(1);expect(f.sends).toHaveLength(1);}finally{f.db.close();}});
 it('changed exact source hash refuses before protection notice',async()=>{const f=await fixture();try{await expect(inspectQueueRecovery(f.repo,f.guard,OP,gen,{...f.input,sourceFactsHash:'f'.repeat(64)})).rejects.toThrow();expect(f.parents()).toHaveLength(0);}finally{f.db.close();}});
 it('claimed-only creator cannot be upgraded to genuine transport authorization',async()=>{const f=await fixture();try{f.db.prepare("UPDATE queue_transitions SET identity_provenance='claimed:v1' WHERE qitem_id='auth-inspect' AND state='pending'").run();await expect(inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input)).rejects.toThrow();expect(f.parents()).toHaveLength(0);}finally{f.db.close();}});
 it.each(['foreign-parent','missing-intent','forged-intent'])('rejects %s replay without remint/redrive',async mode=>{const f=await fixture();try{const r=await inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input);if(mode==='foreign-parent')f.db.prepare("UPDATE queue_items SET source_session='foreign@other' WHERE qitem_id=?").run(r.recoveryQueueId);if(mode==='missing-intent')f.db.prepare('DELETE FROM outbox_entries WHERE outbox_id=?').run('wake-intent-'+r.recoveryQueueId);if(mode==='forged-intent')f.db.prepare("UPDATE outbox_entries SET identity_provenance='claimed:v1' WHERE outbox_id=?").run('wake-intent-'+r.recoveryQueueId);await expect(inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input)).rejects.toThrow();expect(f.parents()).toHaveLength(1);expect(f.sends).toHaveLength(1);}finally{f.db.close();}});
 it('current Operator can issue and genuinely claim its own scoped authorization under standing authority',async()=>{const f=await fixture(true,OP);try{const r=await inspectQueueRecovery(f.repo,f.guard,OP,gen,f.input);expect(r.disposition).toBe('created-control');expect(f.parents()).toHaveLength(1);}finally{f.db.close();}});
 it('actual authenticated route refuses absent auth and caller-selected protection then current Operator path succeeds',async()=>{const f=await fixture();try{const app=new Hono();app.use('*',async(c,next)=>{c.set('queueRepo' as never,f.repo as never);c.set('terminalBearerToken' as never,'test-token' as never);c.set('tmuxAdapter' as never,{deliveryGuard:f.guard} as never);await next();});app.route('/api/queue',queueRoutes());const payload={sourceFactsHash:f.input.sourceFactsHash,operationId:f.input.operationId,authorizationId:f.input.authorizationId};const send=(body:any,auth=true)=>app.request('/api/queue/original/inspect-recovery',{method:'POST',headers:{'Content-Type':'application/json',...(auth?{'Authorization':'Bearer test-token','X-OpenRig-Session':OP,'X-OpenRig-Occupant-Generation':gen}:{})},body:JSON.stringify(body)});expect((await send(payload,false)).status).toBe(401);expect((await send({...payload,protectionCode:'seat_dispatch_reserved'})).status).toBe(400);expect((await send(payload)).status).toBe(200);}finally{f.db.close();}});
});
