import {Hono} from 'hono';
import {coordinatorRoutes} from '../src/routes/coordinator.js';
import {makeResilienceRolloutPolicy} from '../src/domain/policies/resilience-rollout.js';
import type {PolicyJob} from '../src/domain/policies/types.js';
import {ResilienceRolloutService,STANDARD_RESILIENCE_POLICY} from '../src/domain/resilience-rollout-service.js';
import {WatchdogJobsRepository} from '../src/domain/watchdog-jobs-repository.js';
import {RigRepository} from '../src/domain/rig-repository.js';
import {RigSpecSchema} from '../src/domain/rigspec-schema.js';
import {RigSpecCodec} from '../src/domain/rigspec-codec.js';
import {readFileSync} from 'node:fs';
import {RuntimeOutcomeAssessment,type OutcomePolicy} from '../src/domain/runtime-outcome-assessment.js';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {resolve} from 'node:path';
import { describe,it,expect,beforeEach,afterEach,vi } from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import type Database from 'better-sqlite3';
import {createDb} from '../src/db/connection.js';import {EventBus} from '../src/domain/event-bus.js';
import {QueueRepository} from '../src/domain/queue-repository.js';import {OutboxHandler} from '../src/domain/outbox-handler.js';
import {CoordinationRecoveryService,coordinationIdle,type CoordinationActivity,type CoordinationTask,type CoordinationPlan} from '../src/domain/coordination-recovery-service.js';
import {SeatActivityService} from '../src/domain/seat-activity-service.js';
import {digest} from '../src/domain/coordinator-authority-service.js';import {seed,token} from './helpers/coordinator-fixture.js';
describe('shared resilience rollout',()=>{
 let dir:string,db:Database.Database,repo:QueueRepository,svc:CoordinationRecoveryService,clock:number,samples:Map<string,CoordinationActivity>;
 const task=(key:string,owner='builder@xv',more:Partial<CoordinationTask>={}):CoordinationTask=>({key,packageKey:key,owner,action:'Perform '+key+' and return bounded evidence',deadline:clock+20000,body:key,predecessors:[],admission:{generation:repo.coordinatorAuthority.generation(owner)!,configurationDigest:svc.configurationDigest(owner)!,qualificationRef:'approved/non-subject/'+key,capacityRef:'current/provider/'+key,effortRef:'current/effort/'+key,validUntil:clock+60000},...more});
 const plan=(tasks:CoordinationTask[]):CoordinationPlan=>({rigId:'xv',revision:'r1',operatorGeneration:'operator-agent-g1',stallMs:10000,allowIdlePeerTransfer:true,tasks});
 function sample(session:string):CoordinationActivity {const generation=repo.coordinatorAuthority.generation(session)!;return {generation,identityVerified:true,state:{seatNodeId:session,activity:'idle-at-prompt',needsInput:{count:0,reason:null},decidedBy:'window-sampling',seq:1,changedAt:new Date(clock).toISOString(),rungs:[],lastSwap:{generation,at:new Date(clock).toISOString()}},witness:{seatNodeId:session,sessionName:session,rung:'window-sampling',sourceId:'tmux',seq:1,observedAt:new Date(clock).toISOString(),activity:'idle-at-prompt'}};}
 function configure(tasks:CoordinationTask[],resources:Record<string,string[]>={}){for(const t of tasks)repo.coordinatorAuthority.admit('operator-agent@kernel','operator-agent-g1','xv',t.packageKey,{inputDigest:digest(t.key),destination:t.owner,bodyHash:digest(t.body),resources:resources[t.key]??[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});return svc.configure('operator-agent@kernel','operator-agent-g1',plan(tasks));}
 function refresh(){for(const s of ['lead@xv','peer@xv','builder@xv','reviewer@xv','architect@xv'])samples.set(s,sample(s));}
 function job(){db.prepare(`INSERT INTO watchdog_jobs(job_id,target_session,policy,interval_seconds,spec_yaml,state,registered_by_session,registered_at,registered_by_generation_uuid) VALUES ('j','operator-agent@kernel','coordinator-continuity',1,'context: {}','active','operator-agent@kernel',?,'operator-agent-g1')`).run(new Date(clock).toISOString());}
 beforeEach(async()=>{vi.useFakeTimers({toFake:['Date']});clock=Date.now();dir=mkdtempSync(join(tmpdir(),'coordination-'));db=createDb(join(dir,'db'));seed(db);db.prepare("INSERT INTO self_host_identity VALUES(1,'fixture-host',?,?)").run(new Date(clock).toISOString(),new Date(clock).toISOString());const bus=new EventBus(db);repo=new QueueRepository(db,bus,{resolveOccupantGeneration:s=>repo.coordinatorAuthority.generation(s)});repo.attachOutbox(new OutboxHandler(db));await repo.create({qitemId:'baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'coordinate',nudge:false});repo.coordinatorAuthority.enable('operator-agent@kernel','operator-agent-g1',{rigId:'xv',batonId:'baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:60000,operationId:'enable'});repo.coordinatorAuthority.acknowledge('lead@xv',token,{operationId:'ack',obligationsDigest:repo.coordinatorAuthority.reconciliationDigest('xv')});samples=new Map();refresh();svc=new CoordinationRecoveryService(repo,s=>samples.get(s)??null,()=>clock);repo.coordinatorAuthority.coordinationRecovery=svc;});
 afterEach(()=>{db.close();rmSync(dir,{recursive:true,force:true});vi.useRealTimers();});

 const cfg=()=>({schemaVersion:1,mode:'observe',enabled:true,primary:'local',providers:{local:{adapter:'laya',endpoint:'http://127.0.0.1:18091/v1/systemone',model:'typed-decisions',acceptedModels:['qualified-fixture'],timeoutMs:100,allowedData:['private'],maxResponseBytes:16384,capabilities:{schema:'systemone.v1',primitives:['choice'],maxStateChars:10000,maxQuestions:10,maxOptions:10,inputCoverage:'reported'},threshold:{minTopProbability:0.8,calibrationId:'synthetic-test'}}}});
 function outcome(fetch:typeof globalThis.fetch,mode:'observe'|'enforce'='enforce',negative=false){const c=cfg();const r=new RuntimeOutcomeAssessment(repo,{fetchImpl:fetch},()=>clock);repo.coordinatorAuthority.runtimeOutcomeAssessment=r;const p:OutcomePolicy={rigId:'xv',revision:'p1',mode,operatorGeneration:'operator-agent-g1',dataClass:'private',allowPaid:false,allowUnqualifiedNegativeAdvice:negative,adapterConfig:c,qualification:{ref:'synthetic-test-only',providerConfigDigest:digest(JSON.stringify(c)),validUntil:clock+60000}};r.configure('operator-agent@kernel','operator-agent-g1',p);return r;}
 const reply=(choice='yes',coverage=true)=>vi.fn(async()=>new Response(JSON.stringify({model:'qualified-fixture',answers:{outcome:{type:'choice',choice,probabilities:{yes:choice==='yes'?.9:.05,no:choice==='no'?.9:.05,unknown:choice==='unknown'?.9:.05}}},usage:coverage?{input_tokens:150,output_tokens:0,truncated:false}:{input_tokens:150,output_tokens:0}}),{status:200})) as unknown as typeof fetch;

 const normal=()=>[task('product'),task('repair','architect@xv',{recoveryFor:'product'})];
 function rollout(){const jobs=new WatchdogJobsRepository(db,()=>new Date(clock),s=>repo.coordinatorAuthority.generation(s));const roll=new ResilienceRolloutService(repo,jobs,()=>clock);repo.coordinatorAuthority.resilienceRollout=roll;return roll;}
 it('all existing project rigs inventoried; unenrolled project gets actual deduplicated Operator custody without false enrollment',()=>{const r=rollout();const rows=r.reconcile();expect(rows.map(x=>x.rigId)).toEqual(['other','xv']);const other=rows.find(x=>x.rigId==='other')!;expect(other.state).toBe('recovery-pending');expect(repo.coordinatorAuthority.get('other')).toBeUndefined();repo.claim({qitemId:other.queueId!,destinationSession:'operator-agent@kernel',identityProvenance:'transport:v1'});expect(repo.getById(other.queueId!)?.state).toBe('in-progress');const body=JSON.parse(repo.getById(other.queueId!)!.body);expect(body.returnPath.queueId).toBe(other.queueId);expect(body.returnPath.actor).toBe('operator-agent@kernel');expect(body.recipientGeneration).toBe('operator-agent-g1');expect(r.reconcile().find(x=>x.rigId==='other')?.queueId).toBe(other.queueId);});
 it('genuine absent Operator is visible in inventory and creates no fabricated queue assignment',()=>{db.prepare("DELETE FROM occupant_tenures WHERE node_id='operator-agent@kernel'").run();const r=rollout();expect(r.inventory().every(x=>x.state==='operator-unavailable')).toBe(true);expect(r.reconcile().every(x=>x.state==='operator-unavailable')).toBe(true);expect(db.prepare("SELECT 1 FROM queue_items WHERE destination_session='operator-agent@kernel'").get()).toBeUndefined();});
 it('current authenticated Operator materializes enforcement plus actual current-generation observer registration once',()=>{configure(normal());outcome(reply());const r=rollout(),p=repo.coordinatorAuthority.runtimeOutcomeAssessment!.policy('xv')!;const first=r.materialize('operator-agent@kernel','operator-agent-g1',p);expect(first).toMatchObject({state:'covered',rigId:'xv',policyRevision:'p1'});expect(first.jobId).toBeTruthy();expect(r.materialize('operator-agent@kernel','operator-agent-g1',p).jobId).toBe(first.jobId);expect(db.prepare("SELECT registered_by_generation_uuid,target_generation_uuid FROM watchdog_jobs WHERE job_id=?").get(first.jobId)).toEqual({registered_by_generation_uuid:'operator-agent-g1',target_generation_uuid:'operator-agent-g1'});expect(r.inventory().find(x=>x.rigId==='other')?.state).toBe('recovery-pending');});
 it('missing actual Peer is assigned to Operator and never silently inferred or enrolled',()=>{configure(normal());outcome(reply());db.prepare("UPDATE coordinator_authority SET coordinators='[\"lead@xv\"]' WHERE rig_id='xv'").run();const r=rollout(),p=repo.coordinatorAuthority.runtimeOutcomeAssessment!.policy('xv')!;const receipt=r.materialize('operator-agent@kernel','operator-agent-g1',p);expect(receipt.state).toBe('recovery-pending');expect(receipt.reasons).toContain('actual-current-Lead-and-distinct-Peer-required');repo.claim({qitemId:receipt.queueId!,destinationSession:'operator-agent@kernel'});expect(repo.getById(receipt.queueId!)?.state).toBe('in-progress');expect(db.prepare("SELECT 1 FROM watchdog_jobs WHERE policy='coordinator-continuity'").get()).toBeUndefined();});
 it('expired admission or Operator generation and stopped job remain explicit recovery debt, not inherited coverage',()=>{configure(normal());outcome(reply());const r=rollout(),p=repo.coordinatorAuthority.runtimeOutcomeAssessment!.policy('xv')!;r.materialize('operator-agent@kernel','operator-agent-g1',p);clock+=60001;vi.setSystemTime(clock);expect(r.reconcile('xv')[0].reasons).toContain('fresh-exact-task-admissions-required');db.prepare("UPDATE occupant_tenures SET generation_uuid='operator-agent-g2' WHERE node_id='operator-agent@kernel'").run();expect(()=>r.materialize('operator-agent@kernel','operator-agent-g1',p)).toThrow();expect(r.reconcile('xv')[0].operatorGeneration).toBe('operator-agent-g2');});
 it('closing a recovery notice without materializing never credits success; next obligation preserves history',()=>{const r=rollout(),first=r.reconcile('other')[0];repo.claim({qitemId:first.queueId!,destinationSession:'operator-agent@kernel'});repo.update({qitemId:first.queueId!,actorSession:'operator-agent@kernel',state:'done',closureReason:'no-follow-on'});const next=r.reconcile('other')[0];expect(next.queueId).not.toBe(first.queueId);expect(repo.getById(first.queueId!)?.state).toBe('done');expect(JSON.parse(repo.getById(next.queueId!)!.body).previousQueueId).toBe(first.queueId);});
 it('new rig creation uses additive real inventory; project can exist before Peer/provider readiness',()=>{const r=rollout(),rigs=new RigRepository(db);rigs.onRigCreated=rig=>{r.reconcile(rig.id);};const created=rigs.createRig('new-project');expect(r.inventory().some(x=>x.rigId===created.id)).toBe(true);const receipt=r.reconcile(created.id)[0];expect(receipt.state).toBe('recovery-pending');expect(receipt.queueId).toBeTruthy();expect(repo.coordinatorAuthority.get(created.id)).toBeUndefined();});
 it('standard RigSpec ref roundtrips and rejects inherited provider permissions',()=>{const raw={version:'0.2',name:'example',pods:[],edges:[],resilience_policy:'builtin:standard'};const normalized=RigSpecSchema.normalize(raw);expect(normalized.resiliencePolicy).toBe('builtin:standard');expect(RigSpecSchema.normalize({...raw,resilience_policy:undefined}).resiliencePolicy).toBe('builtin:standard');expect(RigSpecCodec.serialize(normalized)).toContain('resilience_policy: builtin:standard');expect(RigSpecSchema.validate({...raw,resilience_policy:{allow_paid:true,qualification_ref:'stale'}}).valid).toBe(false);const template=JSON.parse(readFileSync(new URL('../src/builtins/resilience-policy.json',import.meta.url),'utf8'));expect(template).toMatchObject(STANDARD_RESILIENCE_POLICY);expect(template.inheritQualifications).toBe(false);});
 const auditJob=()=>({jobId:'audit',policy:'resilience-rollout',registeredBySession:'daemon@kernel',target:{session:'operator-agent@kernel'},context:{policyRef:'builtin:standard'}} as PolicyJob);
 it('native periodic audit detects coverage expiry and changed actual Operator without granting new policy',async()=>{configure(normal());outcome(reply());const r=rollout(),p=repo.coordinatorAuthority.runtimeOutcomeAssessment!.policy('xv')!;r.armDefaultAudit();r.materialize('operator-agent@kernel','operator-agent-g1',p);const policy=makeResilienceRolloutPolicy(r);clock+=60001;vi.setSystemTime(clock);await policy.evaluate(auditJob());const first=r.reconcile('xv')[0];expect(first.reasons).toContain('current-qualified-outcome-policy-required');repo.claim({qitemId:first.queueId!,destinationSession:'operator-agent@kernel'});expect(repo.getById(first.queueId!)?.state).toBe('in-progress');db.prepare("UPDATE occupant_tenures SET generation_uuid='operator-agent-g2' WHERE node_id='operator-agent@kernel'").run();await policy.evaluate(auditJob());const next=r.reconcile('xv')[0];expect(next.operatorGeneration).toBe('operator-agent-g2');expect(next.queueId).not.toBe(first.queueId);expect(repo.coordinatorAuthority.runtimeOutcomeAssessment!.policy('xv')?.operatorGeneration).toBe('operator-agent-g1');});
 it('native audit without actual Operator exposes inventory and does not forge pickup',async()=>{const r=rollout();r.armDefaultAudit();db.prepare("DELETE FROM occupant_tenures WHERE node_id='operator-agent@kernel'").run();const result=await makeResilienceRolloutPolicy(r).evaluate(auditJob());expect(result.action).toBe('skip');expect(result.notes?.receipts).toEqual(expect.arrayContaining([expect.objectContaining({state:'operator-unavailable'})]));expect(db.prepare("SELECT 1 FROM queue_items WHERE destination_session='operator-agent@kernel'").get()).toBeUndefined();});
 it.each(['null','[]','{"privateSecret":"must-not-leak"}','not-json','{"bad":"watchdog@system"}'])('malformed per-rig coordinator record %s never parks other projects or leaks record',async(record)=>{db.prepare('UPDATE coordinator_authority SET coordinators=? WHERE rig_id=?').run(record,'xv');const r=rollout();const rows=r.reconcile();expect(rows.find(x=>x.rigId==='xv')?.state).toBe('recovery-pending');const other=rows.find(x=>x.rigId==='other')!;repo.claim({qitemId:other.queueId!,destinationSession:'operator-agent@kernel'});expect(repo.getById(other.queueId!)?.state).toBe('in-progress');expect(JSON.stringify(rows)).not.toContain('must-not-leak');});
 it('malformed policy and plan parse are per-rig recovery, while unaffected project custody continues',()=>{configure(normal());outcome(reply());db.prepare("UPDATE coordinator_operations SET receipt='not-json' WHERE kind='runtime-outcome-policy'").run();const r=rollout();expect(r.reconcile('xv')[0].reasons.join()).toContain('malformed-current-control-record');db.prepare("UPDATE coordinator_operations SET receipt='null' WHERE kind='coordination-plan'").run();const other=r.reconcile('other')[0];repo.claim({qitemId:other.queueId!,destinationSession:'operator-agent@kernel'});expect(repo.getById(other.queueId!)?.state).toBe('in-progress');});

 it('stopped default audit is visible and never silently rearmed on boot',()=>{const r=rollout(),id=r.armDefaultAudit();db.prepare("UPDATE watchdog_jobs SET state='stopped' WHERE job_id=?").run(id);expect(r.armDefaultAudit()).toBe(id);expect(r.inventory().every(x=>x.defaultAuditState==='stopped')).toBe(true);});
 it('duplicate Lead names do not manufacture a distinct Peer',()=>{configure(normal());outcome(reply());db.prepare(`UPDATE coordinator_authority SET coordinators='["lead@xv","lead@xv"]' WHERE rig_id='xv'`).run();expect(rollout().reconcile('xv')[0].reasons).toContain('actual-current-Lead-and-distinct-Peer-required');});
 it('malformed policy body is rejected before materialization rather than crashing',()=>{const r=rollout();for(const value of [null,[],{},'policy'])expect(()=>r.materialize('operator-agent@kernel','operator-agent-g1',value as any)).toThrow('Typed actual per-rig OutcomePolicy required');});
 it('supported authenticated route exposes inventory and only current Operator materializes',async()=>{configure(normal());outcome(reply());rollout();const app=new Hono();app.use('*',async(c,next)=>{c.set('queueRepo' as never,repo as never);await next();});app.route('/api/coordinator',coordinatorRoutes({bearerToken:'test-control'}));const h={'Authorization':'Bearer test-control','X-OpenRig-Session':'operator-agent@kernel','X-OpenRig-Occupant-Generation':'operator-agent-g1','Content-Type':'application/json'};expect((await app.request('/api/coordinator/resilience-inventory',{headers:h})).status).toBe(200);const p=repo.coordinatorAuthority.runtimeOutcomeAssessment!.policy('xv')!;const response=await app.request('/api/coordinator/resilience-materialize',{method:'POST',headers:h,body:JSON.stringify(p)});expect(response.status).toBe(200);expect(await response.json()).toMatchObject({state:'covered',rigId:'xv'});expect((await app.request('/api/coordinator/resilience-materialize',{method:'POST',headers:{...h,'X-OpenRig-Occupant-Generation':'retired'},body:JSON.stringify(p)})).status).toBe(409);expect((await app.request('/api/coordinator/resilience-materialize',{method:'POST',headers:h,body:'null'})).status).toBe(409);});

 it('committed rollout wake really drains through transport before genuine Operator pickup and return',async()=>{const r=rollout(),sent:string[]=[];db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('op-binding','operator-agent@kernel','operator-agent@kernel','%1')").run();repo.attachTransport({send:async(session,text,opts)=>{expect(session).toBe('operator-agent@kernel');expect(opts?.actorSession).toBe('watchdog@system');expect(text).toContain(opts!.queueAssignmentId!);sent.push(opts!.queueAssignmentId!);repo.claim({qitemId:opts!.queueAssignmentId!,destinationSession:session,identityProvenance:'transport:v1'});return {ok:true,verified:true};}});const first=r.reconcile('other')[0];expect(repo.getById(first.queueId!)?.state).toBe('pending');await r.deliver();expect(sent).toEqual([first.queueId]);expect(repo.getById(first.queueId!)?.state).toBe('in-progress');repo.update({qitemId:first.queueId!,actorSession:'operator-agent@kernel',state:'done',closureReason:'no-follow-on'});expect((db.prepare('SELECT claimed_by_generation_uuid FROM queue_items WHERE qitem_id=?').get(first.queueId) as any).claimed_by_generation_uuid).toBe('operator-agent-g1');await r.deliver();expect(sent).toHaveLength(1);});

 it('boot before transport binds intended Operator generation and refuses old notice after late successor drift',async()=>{const r=rollout(),first=r.reconcile('other')[0];db.prepare("UPDATE occupant_tenures SET generation_uuid='operator-agent-g2' WHERE node_id='operator-agent@kernel'").run();db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('op-late','operator-agent@kernel','operator-agent@kernel','%1')").run();const sent:string[]=[];repo.attachTransport({send:async(session,text,opts)=>{sent.push(opts!.queueAssignmentId!);repo.claim({qitemId:opts!.queueAssignmentId!,destinationSession:session});return {ok:true,verified:true};}});await r.deliver();expect(sent).toEqual([]);expect(repo.getById(first.queueId!)?.state).toBe('pending');const current=r.reconcile('other')[0];expect(current.queueId).not.toBe(first.queueId);await r.deliver();expect(sent).toEqual([current.queueId]);expect(repo.getById(current.queueId!)?.state).toBe('in-progress');expect(repo.getById(first.queueId!)?.state).toBe('pending');});

 it.each([{tags:['queue:recipient-generation:']},{tags:['queue:recipient-generation:operator-agent-g1','queue:recipient-generation:operator-agent-g1']},{tags:[17]},{tags:{bad:'private-record'}}])('invalid generation tags %j refuse only that wake and retain independent recovery pickup',async({tags})=>{const r=rollout(),first=r.reconcile('other')[0];db.prepare('UPDATE outbox_entries SET tags=? WHERE audit_pointer=?').run(JSON.stringify(tags),first.queueId);db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('op-tags','operator-agent@kernel','operator-agent@kernel','%1')").run();const next=r.reconcile('xv')[0],sent:string[]=[];repo.attachTransport({send:async(session,text,opts)=>{sent.push(opts!.queueAssignmentId!);repo.claim({qitemId:opts!.queueAssignmentId!,destinationSession:session});return {ok:true,verified:true};}});await r.deliver();expect(sent).toEqual([next.queueId]);expect(repo.getById(first.queueId!)?.state).toBe('pending');expect(repo.getById(next.queueId!)?.state).toBe('in-progress');});

});
