import {RuntimeOutcomeAssessment,sanitizedAssessmentEvidence,type OutcomePolicy} from '../src/domain/runtime-outcome-assessment.js';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {resolve} from 'node:path';
import { describe,it,expect,beforeEach,afterEach,vi } from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import type Database from 'better-sqlite3';
import {createDb} from '../src/db/connection.js';import {EventBus} from '../src/domain/event-bus.js';
import {QueueRepository} from '../src/domain/queue-repository.js';import {OutboxHandler} from '../src/domain/outbox-handler.js';
import {CoordinationRecoveryService,coordinationIdle,type CoordinationActivity,type CoordinationTask,type CoordinationPlan} from '../src/domain/coordination-recovery-service.js';
import {SeatActivityService} from '../src/domain/seat-activity-service.js';
import {digest} from '../src/domain/coordinator-authority-service.js';import {seed,token} from './helpers/coordinator-fixture.js';
describe('runtime outcome enforcement',()=>{
 let dir:string,db:Database.Database,repo:QueueRepository,svc:CoordinationRecoveryService,clock:number,samples:Map<string,CoordinationActivity>;
 const task=(key:string,owner='builder@xv',more:Partial<CoordinationTask>={}):CoordinationTask=>({key,packageKey:key,owner,action:'Perform '+key+' and return bounded evidence',deadline:clock+20000,body:key,predecessors:[],admission:{generation:repo.coordinatorAuthority.generation(owner)!,configurationDigest:svc.configurationDigest(owner)!,qualificationRef:'approved/non-subject/'+key,capacityRef:'current/provider/'+key,effortRef:'current/effort/'+key,validUntil:clock+60000},...more});
 const plan=(tasks:CoordinationTask[]):CoordinationPlan=>({rigId:'xv',revision:'r1',operatorGeneration:'operator-agent-g1',stallMs:10000,allowIdlePeerTransfer:true,tasks});
 function sample(session:string):CoordinationActivity {const generation=repo.coordinatorAuthority.generation(session)!;return {generation,identityVerified:true,state:{seatNodeId:session,activity:'idle-at-prompt',needsInput:{count:0,reason:null},decidedBy:'window-sampling',seq:1,changedAt:new Date(clock).toISOString(),rungs:[],lastSwap:{generation,at:new Date(clock).toISOString()}},witness:{seatNodeId:session,sessionName:session,rung:'window-sampling',sourceId:'tmux',seq:1,observedAt:new Date(clock).toISOString(),activity:'idle-at-prompt'}};}
 function configure(tasks:CoordinationTask[],resources:Record<string,string[]>={},revision='r1'){for(const t of tasks)repo.coordinatorAuthority.admit('operator-agent@kernel','operator-agent-g1','xv',t.packageKey,{inputDigest:digest(t.key),destination:t.owner,bodyHash:digest(t.body),resources:resources[t.key]??[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});return svc.configure('operator-agent@kernel','operator-agent-g1',{...plan(tasks),revision});}
 function refresh(){for(const s of ['lead@xv','peer@xv','builder@xv','reviewer@xv','architect@xv'])samples.set(s,sample(s));}
 function job(){db.prepare(`INSERT INTO watchdog_jobs(job_id,target_session,policy,interval_seconds,spec_yaml,state,registered_by_session,registered_at,registered_by_generation_uuid) VALUES ('j','operator-agent@kernel','coordinator-continuity',1,'context: {}','active','operator-agent@kernel',?,'operator-agent-g1')`).run(new Date(clock).toISOString());}
 beforeEach(async()=>{vi.useFakeTimers({toFake:['Date']});clock=Date.now();dir=mkdtempSync(join(tmpdir(),'coordination-'));db=createDb(join(dir,'db'));seed(db);db.prepare("INSERT INTO self_host_identity VALUES(1,'fixture-host',?,?)").run(new Date(clock).toISOString(),new Date(clock).toISOString());const bus=new EventBus(db);repo=new QueueRepository(db,bus,{resolveOccupantGeneration:s=>repo.coordinatorAuthority.generation(s)});repo.attachOutbox(new OutboxHandler(db));await repo.create({qitemId:'baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'coordinate',nudge:false});repo.coordinatorAuthority.enable('operator-agent@kernel','operator-agent-g1',{rigId:'xv',batonId:'baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:60000,operationId:'enable'});repo.coordinatorAuthority.acknowledge('lead@xv',token,{operationId:'ack',obligationsDigest:repo.coordinatorAuthority.reconciliationDigest('xv')});samples=new Map();refresh();svc=new CoordinationRecoveryService(repo,s=>samples.get(s)??null,()=>clock);repo.coordinatorAuthority.coordinationRecovery=svc;});
 afterEach(()=>{db.close();rmSync(dir,{recursive:true,force:true});vi.useRealTimers();});

 const cfg=()=>({schemaVersion:1,mode:'observe',enabled:true,primary:'local',providers:{local:{adapter:'laya',endpoint:'http://127.0.0.1:18091/v1/systemone',model:'typed-decisions',acceptedModels:['qualified-fixture'],timeoutMs:100,allowedData:['private'],maxResponseBytes:16384,capabilities:{schema:'systemone.v1',primitives:['choice'],maxStateChars:10000,maxQuestions:10,maxOptions:10,inputCoverage:'reported'},threshold:{minTopProbability:0.8,calibrationId:'synthetic-test'}}}});
 function outcome(fetch:typeof globalThis.fetch,mode:'observe'|'enforce'='enforce',negative=false){const c=cfg();const r=new RuntimeOutcomeAssessment(repo,{fetchImpl:fetch},()=>clock);repo.coordinatorAuthority.runtimeOutcomeAssessment=r;const p:OutcomePolicy={rigId:'xv',revision:'p1',mode,operatorGeneration:'operator-agent-g1',dataClass:'private',allowPaid:false,allowUnqualifiedNegativeAdvice:negative,adapterConfig:c,qualification:{ref:'synthetic-test-only',providerConfigDigest:digest(JSON.stringify(c)),validUntil:clock+60000}};r.configure('operator-agent@kernel','operator-agent-g1',p);return r;}
 const reply=(choice='yes',coverage=true)=>vi.fn(async()=>new Response(JSON.stringify({model:'qualified-fixture',answers:{outcome:{type:'choice',choice,probabilities:{yes:choice==='yes'?.9:.05,no:choice==='no'?.9:.05,unknown:choice==='unknown'?.9:.05}}},usage:coverage?{input_tokens:150,output_tokens:0,truncated:false}:{input_tokens:150,output_tokens:0}}),{status:200})) as unknown as typeof fetch;
 async function returned(state:'done'|'failed'='done'){const q=svc.reconcile('lead@xv','lead-g1','xv')[0].queueId!;repo.claim({qitemId:q,destinationSession:'builder@xv',identityProvenance:'transport:v1'});repo.update({qitemId:q,actorSession:'builder@xv',state,closureReason:state==='done'?'no-follow-on':undefined});await repo.create({qitemId:'result',sourceSession:'builder@xv',destinationSession:'lead@xv',body:JSON.stringify({packageKey:'product',inputDigest:digest('product'),evidence:[{kind:'report',ref:'report.md'}],outcomeSummary:'Required implementation will be finished later'}),nudge:false});repo.coordinatorAuthority.dispose('builder@xv','builder-g1','xv','product','result');return q;}
 function storedPolicy(){return JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-policy' ORDER BY rowid DESC LIMIT 1").get() as {receipt:string}).receipt) as OutcomePolicy;}
 function qualificationRefresh(p:OutcomePolicy,dutyQueueId:string){return {rigId:'xv',dutyQueueId,operationId:'fresh-proof',policyRevision:p.revision,policyDigest:digest(JSON.stringify(p)),qualifiedAt:clock,qualification:{...p.qualification,ref:'actual-new-dated-proof',validUntil:clock+60000}};}
 it('same logical policy qualification refresh preserves expired required recovery and never repeats provider effects',async()=>{
  configure(normal());const f=reply(),r=outcome(f);await returned();await r.drain('xv');const p=storedPolicy(),history=db.prepare("SELECT * FROM coordinator_operations WHERE kind IN ('runtime-outcome-policy','runtime-outcome-finished','runtime-outcome-recovery')").all();clock+=61000;vi.setSystemTime(clock);expect(()=>r.configure('operator-agent@kernel','operator-agent-g1',{...p,revision:'unsafe-revision',qualification:{...p.qualification,validUntil:clock+60000}})).toThrow('authorized recovery');
  const dutyId=r.stagePolicyBoundary('xv')!;const input=qualificationRefresh(p,dutyId);expect(()=>r.refreshQualification('operator-agent@kernel','operator-agent-g1',input)).toThrow('natively claimed');repo.claim({qitemId:dutyId,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});expect(()=>r.refreshQualification('lead@xv','lead-g1',{...input,operationId:'wrong-actor'})).toThrow();expect(()=>r.refreshQualification('operator-agent@kernel','operator-agent-g1',{...input,operationId:'drift',policyDigest:digest('other-private-paid-config')})).toThrow('unchanged');expect(()=>r.refreshQualification('operator-agent@kernel','operator-agent-g1',{...input,operationId:'expired',qualification:{...input.qualification,validUntil:clock-1}})).toThrow('Fresh dated');r.refreshQualification('operator-agent@kernel','operator-agent-g1',input);r.refreshQualification('operator-agent@kernel','operator-agent-g1',input);expect(r.policy('xv')).toEqual({...p,qualification:input.qualification});expect(svc.dutyFacts(dutyId).complete).toBe(true);repo.update({qitemId:dutyId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'});expect(r.requiresRecovery('xv','product')).toBe(true);expect(()=>r.assertAcceptance('xv','product')).toThrow('authorized recovery');expect(db.prepare("SELECT * FROM coordinator_operations WHERE kind IN ('runtime-outcome-policy','runtime-outcome-finished','runtime-outcome-recovery')").all()).toEqual(history);await r.drain('xv');expect(vi.mocked(f)).toHaveBeenCalledTimes(1);
  expect(()=>r.refreshQualification('operator-agent@kernel','operator-agent-g1',{...input,qualification:{...input.qualification,ref:'changed'}})).toThrow('replay differs');
 });
 async function outsideOriginal(){
  const parentId='outside-product',dispositionId='outside-result';configure([task('independent','reviewer@xv',{predecessors:[{queueId:parentId,dispositionId}]}),task('independent-backup','architect@xv',{recoveryFor:'independent'})]);const f=reply('yes'),r=outcome(f);repo.coordinatorAuthority.admit('operator-agent@kernel','operator-agent-g1','xv','outside',{inputDigest:digest('outside'),destination:'builder@xv',bodyHash:digest('outside'),resources:[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});await repo.create({qitemId:parentId,sourceSession:'lead@xv',destinationSession:'builder@xv',body:'outside',dispatch:{token,packageKey:'outside'},nudge:false});repo.claim({qitemId:parentId,destinationSession:'builder@xv'});repo.update({qitemId:parentId,actorSession:'builder@xv',state:'done',closureReason:'no-follow-on'});await repo.create({qitemId:dispositionId,sourceSession:'builder@xv',destinationSession:'lead@xv',body:JSON.stringify({packageKey:'outside',inputDigest:digest('outside'),evidence:[{kind:'report',ref:'original.md'}],outcomeSummary:'Required work is unfinished'}),nudge:false});repo.coordinatorAuthority.dispose('builder@xv','builder-g1','xv','outside',dispositionId);await r.drain('xv');const originalContract=(db.prepare("SELECT contract FROM coordinator_packages WHERE package_key='outside'").get() as {contract:string}).contract;return {r,f,parentId,dispositionId,originalContract};
 }
 async function outsideRepair(original:Awaited<ReturnType<typeof outsideOriginal>>,linked=true,active=false){
  const closureTarget={rigId:'xv',packageKey:'outside',queueId:original.parentId,dispositionId:original.dispositionId,contractHash:digest(original.originalContract)},body=JSON.stringify({action:'Complete actual remaining scope',...(linked?{closureTarget}:{}),evidenceInputs:['separate-review.md']});repo.coordinatorAuthority.admit('operator-agent@kernel','operator-agent-g1','xv','actual-recovery',{inputDigest:digest('actual-recovery'),destination:'architect@xv',bodyHash:digest(body),resources:[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});await repo.create({qitemId:'actual-recovery-queue',sourceSession:'lead@xv',destinationSession:'architect@xv',body,dispatch:{token,packageKey:'actual-recovery'},nudge:false});repo.claim({qitemId:'actual-recovery-queue',destinationSession:'architect@xv'});if(active){configure([...svc.plan('xv')!.tasks,task('actual-recovery','architect@xv',{body}),task('actual-recovery-backup','builder@xv',{recoveryFor:'actual-recovery'})],{},'active-r2');const contract=(db.prepare("SELECT contract FROM coordinator_packages WHERE package_key='actual-recovery'").get() as {contract:string}).contract;return {rigId:'xv',operationId:'active-attribution',originalPackageKey:'outside',originalDispositionId:original.dispositionId,originalContractHash:digest(original.originalContract),recoveryPackageKey:'actual-recovery',recoveryQueueId:'actual-recovery-queue',recoveryContractHash:digest(contract),evidenceRef:'actual-holder-active-recovery-attribution.md',deadline:clock+20000};}repo.update({qitemId:'actual-recovery-queue',actorSession:'architect@xv',state:'done',closureReason:'no-follow-on'});await repo.create({qitemId:'actual-recovery-result',sourceSession:'architect@xv',destinationSession:'lead@xv',body:JSON.stringify({packageKey:'actual-recovery',inputDigest:digest('actual-recovery'),evidence:[{kind:'report',ref:'actual-closure.md'}],...(linked?{closureTarget}:{}),outcomeSummary:'Required recovery completed'}),nudge:false});repo.coordinatorAuthority.dispose('architect@xv','architect-g1','xv','actual-recovery','actual-recovery-result');vi.mocked(original.f).mockImplementation(reply('no'));await original.r.drain('xv');const repairContract=(db.prepare("SELECT contract FROM coordinator_packages WHERE package_key='actual-recovery'").get() as {contract:string}).contract;return {rigId:'xv',operationId:'explicit-technical-attribution',originalPackageKey:'outside',originalDispositionId:original.dispositionId,originalContractHash:digest(original.originalContract),recoveryPackageKey:'actual-recovery',recoveryQueueId:'actual-recovery-queue',recoveryContractHash:digest(repairContract),evidenceRef:'actual-holder-technical-attribution.md',deadline:clock+20000};
 }
 it('outside-plan original gets one actionable binding duty and exact actual recovery acceptance releases authorized frontier',async()=>{
  const o=await outsideOriginal();const oldPlan=JSON.stringify(svc.plan('xv')),original=repo.getById(o.parentId),duty=o.r.stageRecoveryBoundary('xv');expect(duty).toHaveLength(1);repo.claim({qitemId:duty[0],destinationSession:'operator-agent@kernel'});expect(()=>repo.update({qitemId:duty[0],actorSession:'operator-agent@kernel',state:'done',closureReason:'no-follow-on'})).toThrow('actual holder recovery acceptance');expect(o.r.stageRecoveryBoundary('xv')).toEqual(duty);const intake=JSON.parse(repo.getById(duty[0])!.body);expect(intake).toMatchObject({action:'materialize-exact-outcome-recovery-binding',originalQueueId:o.parentId,grantsAuthority:false,recoveryAssignmentContract:{closureTarget:{queueId:o.parentId,dispositionId:o.dispositionId}}});expect(()=>svc.accept('lead@xv','lead-g1','xv','outside',o.dispositionId,'parent.md')).toThrow('authorized recovery');const input=await outsideRepair(o);o.r.bindRecovery('lead@xv','lead-g1',input);o.r.bindRecovery('lead@xv','lead-g1',input);expect(()=>o.r.assertAcceptance('xv','outside')).toThrow('authorized recovery');svc.accept('lead@xv','lead-g1','xv','actual-recovery','actual-recovery-result','actual-recovery-acceptance.md');svc.accept('lead@xv','lead-g1','xv','outside',o.dispositionId,'actual-original-acceptance.md');repo.update({qitemId:duty[0],actorSession:'operator-agent@kernel',state:'done',closureReason:'no-follow-on'});const next=svc.reconcile('lead@xv','lead-g1','xv').find(x=>x.key==='independent')!;repo.claim({qitemId:next.queueId!,destinationSession:'reviewer@xv'});expect(repo.getById(next.queueId!)?.state).toBe('in-progress');expect(JSON.stringify(svc.plan('xv'))).toBe(oldPlan);expect(repo.getById(o.parentId)).toEqual(original);
 });
 it('outside-plan binding refuses separate review without immutable exact closureTarget',async()=>{const o=await outsideOriginal(),input=await outsideRepair(o,false);expect(()=>o.r.bindRecovery('lead@xv','lead-g1',input)).toThrow('separate review is not recovery');expect(()=>o.r.assertAcceptance('xv','outside')).toThrow('authorized recovery');});
 it('outside-plan binding refuses wrong holder, drift and expired authority and grants nothing after holder generation changes',async()=>{const o=await outsideOriginal(),input=await outsideRepair(o);expect(()=>o.r.bindRecovery('operator-agent@kernel','operator-agent-g1',input)).toThrow('Current live holder');expect(()=>o.r.bindRecovery('lead@xv','lead-g1',{...input,originalContractHash:digest('drift')})).toThrow('Exact required');expect(()=>o.r.bindRecovery('lead@xv','lead-g1',{...input,deadline:clock-1})).toThrow('expire');o.r.bindRecovery('lead@xv','lead-g1',input);svc.accept('lead@xv','lead-g1','xv','actual-recovery','actual-recovery-result','actual-accept.md');clock+=20001;vi.setSystemTime(clock);expect(()=>o.r.assertAcceptance('xv','outside')).toThrow('authorized recovery');clock-=20001;vi.setSystemTime(clock);db.prepare("UPDATE occupant_tenures SET generation_uuid='lead-g2' WHERE node_id='lead@xv'").run();expect(()=>o.r.assertAcceptance('xv','outside')).toThrow('authorized recovery');});
 it('outside-plan active binding requires actual current admitted custody and finite task deadline',async()=>{const o=await outsideOriginal(),input=await outsideRepair(o,true,true);o.r.bindRecovery('lead@xv','lead-g1',input);expect(()=>o.r.assertAcceptance('xv','outside')).toThrow('authorized recovery');clock+=20001;vi.setSystemTime(clock);expect(()=>o.r.bindRecovery('lead@xv','lead-g1',{...input,operationId:'expired-active',deadline:clock+10000})).toThrow('current configured admission');expect(repo.getById('actual-recovery-queue')?.state).toBe('in-progress');});
 const normal=()=>[task('product'),task('repair','architect@xv',{recoveryFor:'product'})];
 it('real common return produces qualified negative recovery and actual admitted pickup',async()=>{configure(normal());const f=reply(),r=outcome(f);await returned();expect(()=>svc.accept('lead@xv','lead-g1','xv','product','result','accept.md')).toThrow('not yet resolved');await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(true);const repair=svc.reconcile('lead@xv','lead-g1','xv').find(x=>x.key==='repair')!;expect(repair.state).toBe('pending-pickup');repo.claim({qitemId:repair.queueId!,destinationSession:'architect@xv',identityProvenance:'transport:v1'});expect(svc.reconcile('lead@xv','lead-g1','xv').find(x=>x.key==='repair')?.state).toBe('picked-up');expect(()=>svc.accept('lead@xv','lead-g1','xv','product','result','accept.md')).toThrow('authorized recovery');expect(JSON.stringify(vi.mocked(f).mock.calls)).toContain('finished later');await r.drain('xv');expect(vi.mocked(f)).toHaveBeenCalledTimes(1);});
 it('provider unavailable leaves successful factual acceptance rules and independent frontier usable',async()=>{configure([...normal(),task('independent','reviewer@xv'),task('independent-repair','architect@xv',{recoveryFor:'independent'})]);const r=outcome(vi.fn(async()=>{throw new Error('offline')}) as unknown as typeof fetch);await returned();await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(false);svc.accept('lead@xv','lead-g1','xv','product','result','actual/technical-review.md');expect(svc.reconcile('lead@xv','lead-g1','xv').find(x=>x.key==='independent')?.state).toBe('pending-pickup');});
 it('failed actual state creates recovery even when model unavailable',async()=>{configure(normal());const r=outcome(vi.fn(async()=>{throw new Error('offline')}) as unknown as typeof fetch);await returned('failed');await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(true);const repair=svc.reconcile('lead@xv','lead-g1','xv')[1];repo.claim({qitemId:repair.queueId!,destinationSession:'architect@xv'});expect(repo.getById(repair.queueId!)?.state).toBe('in-progress');});
 it('expired policy commits one generation-bound Operator recovery, without extending policy or calling provider',async()=>{
  configure(normal());const f=reply(),r=outcome(f);const policy=r.policy('xv')!;expect(r.stagePolicyBoundary('xv')).toBeNull();clock=policy.qualification.validUntil+1;vi.setSystemTime(clock);
  const id=r.stagePolicyBoundary('xv')!;expect(r.stagePolicyBoundary('xv')).toBe(id);const q=repo.getById(id)!;expect(q.destinationSession).toBe('operator-agent@kernel');expect(JSON.parse(q.body)).toMatchObject({action:'refresh-exact-expired-outcome-qualification',queueId:id,recipientGeneration:'operator-agent-g1',policyRevision:policy.revision,grantsAuthority:false,qualificationRefreshContract:{rigId:'xv',dutyQueueId:id,policyRevision:policy.revision,policyDigest:digest(JSON.stringify(storedPolicy()))}});expect(r.policy('xv')).toEqual(policy);expect(vi.mocked(f)).not.toHaveBeenCalled();
  const wakes=db.prepare('SELECT * FROM outbox_entries WHERE audit_pointer=?').all(id) as any[];expect(wakes).toHaveLength(1);expect(wakes[0].delivery_state).toBe('pending');expect(JSON.parse(wakes[0].tags)).toContain('queue:recipient-generation:operator-agent-g1');
  repo.attachTransport({send:async()=>({ok:true,verified:true})});await svc.deliverCommitted();repo.claim({qitemId:id,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});expect(db.prepare('SELECT claimed_by_generation_uuid FROM queue_items WHERE qitem_id=?').get(id)).toEqual({claimed_by_generation_uuid:'operator-agent-g1'});
  const originalDeadline=Date.parse(q.expiresAt!);clock=originalDeadline+1;vi.setSystemTime(clock);expect(r.stagePolicyBoundary('xv')).toBe(id);const retirement=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='coordinator-lifecycle-control' AND json_extract(receipt,'$.kind')='lifecycle-retirement' AND json_extract(receipt,'$.targetQueueId')=?").get(id) as {receipt:string}).receipt);expect(retirement.deadline).toBeLessThanOrEqual(clock+1200000);expect(repo.getById(id)?.claimedAt).toBeTruthy();repo.update({qitemId:id,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'failed',transitionNote:'actual native expired-duty failure'});expect(svc.dutyFacts(id)).toMatchObject({failedByRecipient:true,retired:true});expect(r.stagePolicyBoundary('xv')).not.toBe(id);await svc.deliverCommitted();const successor=r.stagePolicyBoundary('xv')!;expect(successor).not.toBe(id);const successorReceipt=svc.lifecycleControlReceipt(successor);expect(successorReceipt).toMatchObject({kind:'outcome-qualification-refresh',previousQueueId:id,qualificationRef:policy.qualification.ref,deadline:expect.any(Number)});expect(successorReceipt.deadline).toBeLessThanOrEqual(clock+1200000);expect(repo.getById(id)?.expiresAt).toBe(q.expiresAt);expect(repo.getById(successor)?.expiresAt).not.toBe(q.expiresAt);
  db.prepare("UPDATE occupant_tenures SET generation_uuid='operator-agent-g2' WHERE node_id='operator-agent@kernel'").run();expect(r.stagePolicyBoundary('xv')).toBeNull();
 });
 it('successive refresh binds latest expired overlay while retaining immutable logical policy digest',()=>{
  configure(normal());const r=outcome(reply());const original=storedPolicy();
  clock=original.qualification.validUntil+1;vi.setSystemTime(clock);db.prepare('UPDATE coordinator_authority SET lease_until=?').run(clock+3600000);
  const first=r.stagePolicyBoundary('xv')!;repo.claim({qitemId:first,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});
  const one=qualificationRefresh(original,first);r.refreshQualification('operator-agent@kernel','operator-agent-g1',one);
  repo.update({qitemId:first,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'});
  clock=one.qualification.validUntil+1;vi.setSystemTime(clock);
  const second=r.stagePolicyBoundary('xv')!;expect(second).toBeTruthy();expect(second).not.toBe(first);
  expect(svc.lifecycleControlReceipt(second)).toMatchObject({qualificationRef:one.qualification.ref,policyDigest:digest(JSON.stringify(original))});
  repo.claim({qitemId:second,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});
  const two={...qualificationRefresh(original,second),operationId:'second-proof',qualification:{...one.qualification,ref:'actual-second-dated-proof',validUntil:clock+60000}};
  r.refreshQualification('operator-agent@kernel','operator-agent-g1',two);
  expect(storedPolicy()).toEqual(original);expect(r.policy('xv')?.qualification).toEqual(two.qualification);
  expect(svc.dutyFacts(second)).toMatchObject({complete:true});
 });
 it('qualification refresh is authorized only by the exact claimed expired-qualification duty, never another claimed Operator duty',()=>{
   configure(normal());const r=outcome(reply());const p=r.policy('xv')!;
   repo.coordinatorAuthority.admit('operator-agent@kernel','operator-agent-g1','xv','unplanned',{inputDigest:digest('unplanned'),destination:'builder@xv',bodyHash:digest('unplanned'),resources:[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});
   const admin=svc.reconcile('lead@xv','lead-g1','xv').find(x=>x.key==='materialization:unplanned')!.queueId!;expect(svc.lifecycleControlReceipt(admin)).toMatchObject({kind:'materialization',recipient:'operator-agent@kernel'});db.prepare("UPDATE outbox_entries SET delivery_state='delivered' WHERE outbox_id=?").run('wake-intent-'+admin);repo.claim({qitemId:admin,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});expect(svc.dutyFacts(admin).claim).toBe(true);
   clock=p.qualification.validUntil+1;vi.setSystemTime(clock);db.prepare('UPDATE coordinator_authority SET lease_until=?').run(clock+1200000);
   const dutyId=r.stagePolicyBoundary('xv')!,input=qualificationRefresh(p,dutyId);
   expect(()=>r.refreshQualification('operator-agent@kernel','operator-agent-g1',{...input,dutyQueueId:admin,operationId:'foreign-claimed-duty'})).toThrow('Exact active expired-qualification duty');
   expect(db.prepare("SELECT 1 FROM coordinator_operations WHERE kind='runtime-outcome-qualification'").get()).toBeUndefined();
   repo.claim({qitemId:dutyId,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});
   expect(()=>r.refreshQualification('operator-agent@kernel','operator-agent-g1',{...input,dutyQueueId:admin,operationId:'foreign-claimed-duty-now-claimed'})).toThrow('Exact active expired-qualification duty');
   r.refreshQualification('operator-agent@kernel','operator-agent-g1',input);
   const receipt=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-qualification'").get() as {receipt:string}).receipt);
   expect(receipt).toMatchObject({dutyQueueId:dutyId,policyRevision:p.revision,grantsAuthority:false});expect(r.policy('xv')).toEqual({...p,qualification:input.qualification});
  });
  it('qualification refresh completion is a monotone receipt postcondition beyond the freshness window and duty deadline',()=>{
   configure(normal());const r=outcome(reply());const p=r.policy('xv')!;clock=p.qualification.validUntil+1;vi.setSystemTime(clock);db.prepare('UPDATE coordinator_authority SET lease_until=?').run(clock+1200000);
   const dutyId=r.stagePolicyBoundary('xv')!;const issued=svc.lifecycleControlReceipt(dutyId)!;repo.claim({qitemId:dutyId,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});
   const beforeIssue=clock-60000;clock+=1000;vi.setSystemTime(clock);const input={...qualificationRefresh(p,dutyId),qualifiedAt:beforeIssue};
   r.refreshQualification('operator-agent@kernel','operator-agent-g1',input);
   db.prepare("UPDATE outbox_entries SET delivery_state='delivered' WHERE outbox_id=?").run('wake-intent-'+dutyId);
   expect(svc.dutyFacts(dutyId)).toMatchObject({complete:true,close:true});
   clock=issued.issuedAt+200001;vi.setSystemTime(clock);expect(svc.dutyFacts(dutyId)).toMatchObject({complete:true,close:true});
   repo.update({qitemId:dutyId,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'});expect(repo.getById(dutyId)?.state).toBe('done');
   clock=issued.deadline+1;vi.setSystemTime(clock);expect(svc.dutyFacts(dutyId)).toMatchObject({complete:true});expect(repo.getById(dutyId)?.expiresAt).toBe(new Date(issued.deadline).toISOString());
  });
  it('atomically records qualification completion before a delayed observer crosses the duty deadline',()=>{
   configure(normal());const r=outcome(reply()),p=r.policy('xv')!;
   clock=p.qualification.validUntil+1;vi.setSystemTime(clock);
   const id=r.stagePolicyBoundary('xv')!,duty=svc.lifecycleControlReceipt(id)!;
   repo.claim({qitemId:id,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});
   r.refreshQualification('operator-agent@kernel','operator-agent-g1',qualificationRefresh(p,id));
   clock=duty.deadline+1;vi.setSystemTime(clock);
   expect(svc.dutyFacts(id)).toMatchObject({complete:true,close:true,act:false,expired:true});
   repo.update({qitemId:id,actorSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1',state:'done',closureReason:'no-follow-on'});
   expect(repo.getById(id)?.state).toBe('done');
  });
  function operatorDirectEffect(body:string){const handler=new OutboxHandler(db);handler.recordDirectAttempt({senderSession:'lead@xv',destinationSession:'operator-agent@kernel',body,tags:['report']},'indeterminate');return (db.prepare("SELECT outbox_id FROM outbox_entries WHERE destination_session='operator-agent@kernel' ORDER BY rowid DESC LIMIT 1").get() as {outbox_id:string}).outbox_id;}
  it('administrative qualification boundary tolerates one acknowledged UNKNOWN direct effect for the Operator seat',()=>{
   configure(normal());const r=outcome(reply());const p=r.policy('xv')!;clock=p.qualification.validUntil+1;vi.setSystemTime(clock);
   const effect=operatorDirectEffect('unrelated direct report whose delivery is genuinely uncertain');
   expect(()=>new OutboxHandler(db).recipientAcknowledgmentContract('operator-agent@kernel','operator-agent-g1',effect)).not.toThrow();
   const id=r.stagePolicyBoundary('xv')!;expect(repo.getById(id)?.destinationSession).toBe('operator-agent@kernel');expect(JSON.parse(repo.getById(id)!.body)).toMatchObject({action:'refresh-exact-expired-outcome-qualification',policyRevision:p.revision});
   expect(svc.dutyFacts(id)).toMatchObject({claim:true});expect(db.prepare("SELECT delivery_state FROM outbox_entries WHERE outbox_id=?").get(effect)).toEqual({delivery_state:'indeterminate'});
  });
  it('pending historical effects cannot starve exact qualification and remain byte-identical',()=>{
   configure(normal());const r=outcome(reply());const p=r.policy('xv')!;
   const effect=operatorDirectEffect('historical pending report');db.prepare("UPDATE outbox_entries SET delivery_state='pending' WHERE outbox_id=?").run(effect);
   const before=db.prepare('SELECT * FROM outbox_entries WHERE outbox_id=?').get(effect);
   clock=p.qualification.validUntil+1;vi.setSystemTime(clock);
   const id=r.stagePolicyBoundary('xv')!;expect(id).toBeTruthy();
   expect(svc.lifecycleControlReceipt(id)).toMatchObject({kind:'outcome-qualification-refresh',recipient:'operator-agent@kernel'});
   expect(svc.dutyFacts(id)).toMatchObject({claim:true});
   repo.claim({qitemId:id,destinationSession:'operator-agent@kernel',actorGeneration:'operator-agent-g1',identityProvenance:'transport:v1'});
   r.refreshQualification('operator-agent@kernel','operator-agent-g1',qualificationRefresh(p,id));
   expect(db.prepare('SELECT * FROM outbox_entries WHERE outbox_id=?').get(effect)).toEqual(before);
   expect(db.prepare("SELECT count(*) n FROM coordinator_operations WHERE kind='package-acceptance'").get()).toMatchObject({n:0});
  });
  it('in-flight direct effect blocks the administrative duty but produces one accountable intake instead of silence',()=>{
   configure(normal());const r=outcome(reply());const p=r.policy('xv')!;clock=p.qualification.validUntil+1;vi.setSystemTime(clock);
   const effect=operatorDirectEffect('unrelated direct effect still in flight');db.prepare("UPDATE outbox_entries SET delivery_state='sending' WHERE outbox_id=?").run(effect);
   expect(r.stagePolicyBoundary('xv')).toBeNull();
   const intakes=db.prepare("SELECT body FROM queue_items WHERE json_valid(body) AND json_extract(body,'$.reason')='lifecycle-recipient-protected'").all() as any[];expect(intakes).toHaveLength(1);
   expect(JSON.parse(intakes[0].body)).toMatchObject({action:'resolve-exact-coordination-task-hold',packageKey:'outcome-qualification:'+p.revision,taskOwner:'operator-agent@kernel',retainedQueueId:null,recipientGeneration:'operator-agent-g1',grantsAuthority:false});
   expect(r.stagePolicyBoundary('xv')).toBeNull();expect(db.prepare("SELECT count(*) n FROM queue_items WHERE json_valid(body) AND json_extract(body,'$.reason')='lifecycle-recipient-protected'").get()).toMatchObject({n:1});
   expect(db.prepare("SELECT count(*) n FROM coordinator_operations WHERE kind='coordinator-lifecycle-control'").get()).toMatchObject({n:0});
  });
  it('materialization keeps the strict zero-debt gate while an acknowledged UNKNOWN direct effect exists',()=>{
   configure(normal());const r=outcome(reply());const p=r.policy('xv')!;clock=p.qualification.validUntil+1;vi.setSystemTime(clock);db.prepare('UPDATE coordinator_authority SET lease_until=?').run(clock+60000);
   operatorDirectEffect('acknowledged uncertain direct report');
   repo.coordinatorAuthority.admit('operator-agent@kernel','operator-agent-g1','xv','unplanned',{inputDigest:digest('unplanned'),destination:'builder@xv',bodyHash:digest('unplanned'),resources:[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});
   const duty=svc.reconcile('lead@xv','lead-g1','xv').find(x=>x.key==='materialization:unplanned')!;expect(duty).toMatchObject({state:'held',reason:'lifecycle-recipient-protected'});
   expect(duty.queueId??null).toBeNull();expect(svc.lifecycleControlReceipt('qitem-unissued')).toBeNull();
   expect(db.prepare("SELECT 1 FROM queue_items WHERE qitem_id LIKE 'qitem-coordination-lifecycle-%'").get()).toBeUndefined();
   expect(db.prepare("SELECT 1 FROM queue_items WHERE json_valid(body) AND json_extract(body,'$.action')='refresh-exact-expired-outcome-qualification'").get()).toBeUndefined();
  });
  it('pending historical intake notice cannot block qualification after active sending ends',async()=>{
   configure(normal());const r=outcome(reply());const p=r.policy('xv')!;clock=p.qualification.validUntil+1;vi.setSystemTime(clock);
   const block=operatorDirectEffect('unrelated effect still in flight');db.prepare("UPDATE outbox_entries SET delivery_state='sending' WHERE outbox_id=?").run(block);
   expect(r.stagePolicyBoundary('xv')).toBeNull();const intakes=()=>db.prepare("SELECT qitem_id,body FROM queue_items WHERE json_valid(body) AND json_extract(body,'$.action')='resolve-exact-coordination-task-hold' AND json_extract(body,'$.reason')='lifecycle-recipient-protected'").all() as any[];
   expect(intakes()).toHaveLength(1);const notice='wake-intent-'+intakes()[0].qitem_id;expect((db.prepare('SELECT delivery_state FROM outbox_entries WHERE outbox_id=?').get(notice) as {delivery_state:string}).delivery_state).toBe('pending');
   db.prepare("UPDATE outbox_entries SET delivery_state='delivered' WHERE outbox_id=?").run(block);expect(r.stagePolicyBoundary('xv')).toBeTruthy();expect(intakes()).toHaveLength(1);
   operatorDirectEffect('acknowledged uncertain direct report');repo.attachTransport({send:async()=>({ok:true,verified:true})});await svc.deliverCommitted();
   expect(['delivered','failed']).toContain((db.prepare('SELECT delivery_state FROM outbox_entries WHERE outbox_id=?').get(notice) as {delivery_state:string}).delivery_state);
   expect(r.stagePolicyBoundary('xv')).toBeTruthy();expect(intakes()).toHaveLength(1);
  });
  it('a persistent administrative hold renews for as long as it persists, one bounded item at a time',()=>{
   configure(normal());const r=outcome(reply());const p=r.policy('xv')!;clock=p.qualification.validUntil+1;vi.setSystemTime(clock);
   const block=operatorDirectEffect('unrelated effect still in flight');db.prepare("UPDATE outbox_entries SET delivery_state='sending' WHERE outbox_id=?").run(block);
   expect(r.stagePolicyBoundary('xv')).toBeNull();
   const ids=()=>db.prepare("SELECT qitem_id FROM queue_items WHERE json_valid(body) AND json_extract(body,'$.action')='resolve-exact-coordination-task-hold' AND json_extract(body,'$.reason')='lifecycle-recipient-protected' ORDER BY rowid").all() as Array<{qitem_id:string}>;
   expect(ids()).toHaveLength(1);const rootId=ids()[0].qitem_id,first=repo.getById(rootId)!;
   for(let round=1;round<=3;round++){
    clock=Date.parse(repo.getById(ids()[round-1].qitem_id)!.expiresAt!)+1;vi.setSystemTime(clock);
    expect(r.stagePolicyBoundary('xv')).toBeNull();expect(ids()).toHaveLength(round+1);
    const latest=repo.getById(ids()[round].qitem_id)!,body=JSON.parse(latest.body),previous=repo.getById(ids()[round-1].qitem_id)!;
    const prevId=ids()[round-1].qitem_id,newId=latest.qitemId;
    expect(body).toMatchObject({renewsIntakeQueueId:rootId,rootQueueId:rootId,previousIntakeQueueId:prevId,retainedQueueId:null,grantsAuthority:false});expect(newId).not.toBe(prevId);expect(newId).not.toBe(rootId);
    expect(Date.parse(latest.expiresAt!)).toBeGreaterThan(clock);
    expect(repo.getById(prevId)).toEqual(previous);
    const chain=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='coordination-intake-chain' AND operation_id=?").get('coordination-intake-chain:'+newId) as {receipt:string}).receipt);expect(chain).toMatchObject({rootQueueId:rootId,previousIntakeQueueId:prevId,grantsAuthority:false});expect(chain.noticeBodyHash).toBe(digest((db.prepare('SELECT body FROM outbox_entries WHERE outbox_id=?').get('wake-intent-'+newId) as {body:string}).body));
   }
   expect((db.prepare("SELECT delivery_state FROM outbox_entries WHERE outbox_id=?").get(block) as {delivery_state:string}).delivery_state).toBe('sending');
   // Exactly one genuinely live accountable item owns this hold; superseded items stay on
   // record, unclaimed and unexpended-into new authority.
   expect((db.prepare("SELECT count(*) n FROM queue_items WHERE destination_session='operator-agent@kernel' AND state IN ('pending','in-progress','blocked') AND expires_at>? AND json_valid(body) AND json_extract(body,'$.action')='resolve-exact-coordination-task-hold' AND json_extract(body,'$.reason')='lifecycle-recipient-protected'").get(new Date(clock).toISOString()) as {n:number}).n).toBe(1);
   expect((db.prepare("SELECT count(*) n FROM queue_items WHERE destination_session='operator-agent@kernel' AND state IN ('pending','in-progress','blocked') AND expires_at<=? AND json_valid(body) AND json_extract(body,'$.action')='resolve-exact-coordination-task-hold' AND json_extract(body,'$.reason')='lifecycle-recipient-protected'").get(new Date(clock).toISOString()) as {n:number}).n).toBe(3);
   expect((db.prepare("SELECT count(*) n FROM queue_items WHERE destination_session='operator-agent@kernel' AND state IN ('in-progress','blocked') AND json_valid(body)").get() as {n:number}).n).toBe(0);
  });
  it('historical UNKNOWN guarded notice is preserved while active delivery guard fences issue',()=>{
   configure(normal());const r=outcome(reply());const p=r.policy('xv')!;
   const id=operatorDirectEffect('historical guarded pointer');db.prepare("UPDATE outbox_entries SET guard_binding='{}' WHERE outbox_id=?").run(id);
   const old=db.prepare('SELECT * FROM outbox_entries WHERE outbox_id=?').get(id);
   clock=p.qualification.validUntil+1;vi.setSystemTime(clock);
   db.prepare("INSERT INTO seat_delivery_guards(node_id,desired,effective,actor,reason,changed_at) VALUES ('operator-agent@kernel',1,1,'test','typing',datetime('now'))").run();
   expect(r.stagePolicyBoundary('xv')).toBeNull();
   db.prepare("UPDATE seat_delivery_guards SET desired=0,effective=0 WHERE node_id='operator-agent@kernel'").run();
   const duty=r.stagePolicyBoundary('xv')!;expect(duty).toBeTruthy();
   expect(svc.dutyFacts(duty)).toMatchObject({claim:true});
   db.prepare("UPDATE seat_delivery_guards SET desired=1,effective=1 WHERE node_id='operator-agent@kernel'").run();
   expect(svc.dutyFacts(duty)).toMatchObject({claim:false});
   db.prepare("UPDATE seat_delivery_guards SET desired=0,effective=0 WHERE node_id='operator-agent@kernel'").run();
   db.prepare("UPDATE outbox_entries SET delivery_state='sending' WHERE outbox_id=?").run(id);
   expect(svc.dutyFacts(duty)).toMatchObject({claim:false});
   db.prepare("UPDATE outbox_entries SET delivery_state='indeterminate' WHERE outbox_id=?").run(id);
   expect(db.prepare('SELECT * FROM outbox_entries WHERE outbox_id=?').get(id)).toEqual(old);
  });

  it('observation and absent policy never add authority or semantic holds',async()=>{configure(normal());const r=outcome(reply(),'observe');await returned();await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(false);svc.accept('lead@xv','lead-g1','xv','product','result','actual/review.md');expect(db.prepare("SELECT count(*) n FROM coordinator_operations WHERE kind='coordination-accept'").get()).toEqual({n:1});});
 it('unknown coverage negative advice remains expressly unqualified and only opt-in',async()=>{configure(normal());const r=outcome(reply('yes',false),'enforce',true);await returned();await r.drain('xv');const row=db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-finished'").get() as {receipt:string};expect(JSON.parse(row.receipt)).toMatchObject({status:'abstained',negativeAdvice:true,required:true,grantsAuthority:false});expect(JSON.parse(row.receipt).provenance.inputCoverage).not.toBe('reported_complete');});
 it('generation drift while provider pending cannot apply old advice',async()=>{configure(normal());const f=vi.fn(async()=>{db.prepare("UPDATE occupant_tenures SET generation_uuid='builder-g2' WHERE node_id='builder@xv'").run();return new Response(JSON.stringify({model:'qualified-fixture',answers:{outcome:{type:'choice',choice:'yes',probabilities:{yes:.9,no:.05,unknown:.05}}},usage:{input_tokens:150,output_tokens:0,truncated:false}}),{status:200});}) as unknown as typeof fetch;const r=outcome(f);await returned();await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(false);const row=db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-finished'").get() as {receipt:string};expect(JSON.parse(row.receipt)).toMatchObject({reason:'state-changed',classification:'unknown',grantsAuthority:false});});
 it('two rigs and Codex/Pi identities process independently through common disposition',async()=>{
  configure(normal());const f=reply(),r=outcome(f);
  for(const name of ['lead','peer','repair']){const id=name+'@other';db.prepare('INSERT INTO nodes(id,rig_id,logical_id,runtime) VALUES (?,?,?,?)').run(id,'other',name,'pi');db.prepare('INSERT INTO sessions(id,node_id,session_name) VALUES (?,?,?)').run(id,id,id);db.prepare("INSERT INTO occupant_tenures(id,node_id,generation_ordinal,generation_uuid,kind) VALUES(?,?,1,?,'fresh')").run(id,id,name+'-other-g1');}
  db.prepare("UPDATE nodes SET runtime='pi' WHERE id='worker@other'").run();
  await repo.create({qitemId:'other-baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@other',body:'coordinate',nudge:false});repo.coordinatorAuthority.enable('operator-agent@kernel','operator-agent-g1',{rigId:'other',batonId:'other-baton',owner:'lead@other',ownerGeneration:'lead-other-g1',coordinators:['lead@other','peer@other'],leaseMs:60000,operationId:'other-enable'});repo.coordinatorAuthority.acknowledge('lead@other',{rigId:'other',epoch:1,generation:'lead-other-g1'},{operationId:'other-ack',obligationsDigest:repo.coordinatorAuthority.reconciliationDigest('other')});
  const tasks=[task('other-product','worker@other'),task('other-repair','repair@other',{recoveryFor:'other-product'})];
  for(const t of tasks){repo.coordinatorAuthority.admit('operator-agent@kernel','operator-agent-g1','other',t.packageKey,{inputDigest:digest(t.key),destination:t.owner,bodyHash:digest(t.body),resources:[],returnContract:{destination:'lead@other',evidenceRequired:['report']}});samples.set(t.owner,sample(t.owner));}
  svc.configure('operator-agent@kernel','operator-agent-g1',{...plan(tasks),rigId:'other'});const p=r.policy('xv')!;r.configure('operator-agent@kernel','operator-agent-g1',{...p,rigId:'other'});
  await returned();const q=svc.reconcile('lead@other','lead-other-g1','other')[0].queueId!;repo.claim({qitemId:q,destinationSession:'worker@other'});repo.update({qitemId:q,actorSession:'worker@other',state:'done',closureReason:'no-follow-on'});await repo.create({qitemId:'other-result',sourceSession:'worker@other',destinationSession:'lead@other',body:JSON.stringify({packageKey:'other-product',inputDigest:digest('other-product'),evidence:[{kind:'report',ref:'other/report.md'}],outcomeSummary:'Assigned required work remains unfinished'}),nudge:false});repo.coordinatorAuthority.dispose('worker@other','worker-g1','other','other-product','other-result');
  await Promise.all([r.drain('xv'),r.drain('other')]);expect(vi.mocked(f)).toHaveBeenCalledTimes(2);expect(r.requiresRecovery('xv','product')).toBe(true);expect(r.requiresRecovery('other','other-product')).toBe(true);const repair=svc.reconcile('lead@other','lead-other-g1','other')[1];repo.claim({qitemId:repair.queueId!,destinationSession:'repair@other'});expect(repo.getById(repair.queueId!)?.state).toBe('in-progress');
 });

 it('invalid, model mismatch, nonfinite and truncated advice cannot create semantic enforcement',async()=>{for(const raw of [{model:'wrong',answers:{}},{model:'qualified-fixture',answers:{outcome:{type:'choice',choice:'yes',probabilities:{yes:2,no:0,unknown:0}}}},{model:'qualified-fixture',answers:{outcome:{type:'choice',choice:'yes',probabilities:{yes:.9,no:.05,unknown:.05}}},usage:{truncated:true,input_tokens:10,output_tokens:0}}]){configure(normal());const r=outcome(vi.fn(async()=>new Response(JSON.stringify(raw))) as unknown as typeof fetch,'enforce',true);await returned();await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(false);db.prepare("DELETE FROM coordinator_operations WHERE kind LIKE 'runtime-outcome%'").run();db.prepare("DELETE FROM coordinator_operations WHERE kind NOT IN ('coordination-plan','enable','acknowledge')").run();db.prepare('DELETE FROM outbox_entries').run();db.prepare('DELETE FROM coordinator_assignments').run();db.prepare("DELETE FROM queue_items WHERE qitem_id!='baton'").run();}});
 it('same-rig simultaneous drains yield one request and one recovery intent',async()=>{configure(normal());const f=reply(),r=outcome(f);await returned();await Promise.all([r.drain('xv'),r.drain('xv')]);expect(vi.mocked(f)).toHaveBeenCalledTimes(1);expect(db.prepare("SELECT count(*) n FROM coordinator_assignments WHERE package_key='repair'").get()).toEqual({n:1});});
 it('policy revision cannot erase pending or unresolved negative obligation',async()=>{configure(normal());const r=outcome(reply());await returned();const p=r.policy('xv')!;expect(()=>r.configure('operator-agent@kernel','operator-agent-g1',{...p,revision:'p2',mode:'observe'})).toThrow('not yet resolved');await r.drain('xv');expect(()=>r.configure('operator-agent@kernel','operator-agent-g1',{...p,revision:'p2',mode:'observe'})).toThrow('authorized recovery');});
 it('negative advice is disabled by default for unknown coverage',async()=>{configure(normal());const r=outcome(reply('yes',false));await returned();await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(false);});
 it('strict flags and paid/private remote opt-ins fail before provider or credentials',()=>{configure(normal());const r=outcome(reply()),p=r.policy('xv')!;expect(()=>r.configure('operator-agent@kernel','operator-agent-g1',{...p,revision:'bad',allowUnqualifiedNegativeAdvice:'false' as unknown as boolean})).toThrow('strict opt-ins');const c=cfg();c.providers.local.endpoint='https://api.typesafe.ai/v1/systemone';expect(()=>r.configure('operator-agent@kernel','operator-agent-g1',{...p,revision:'remote',adapterConfig:c,qualification:{...p.qualification,providerConfigDigest:digest(JSON.stringify(c))}})).toThrow();});
 it('terminal return from retired generation is refused by actual common boundary',async()=>{configure(normal());const r=outcome(reply());const q=svc.reconcile('lead@xv','lead-g1','xv')[0].queueId!;repo.claim({qitemId:q,destinationSession:'builder@xv'});repo.update({qitemId:q,actorSession:'builder@xv',state:'done',closureReason:'no-follow-on'});expect(()=>repo.coordinatorAuthority.dispose('builder@xv','retired','xv','product','none')).toThrow();expect(db.prepare("SELECT 1 FROM coordinator_operations WHERE kind='runtime-outcome-pending'").get()).toBeUndefined();});

 it('missing recovery for incomplete leaf is accountable gap and cannot imply completion',async()=>{configure(normal());const r=outcome(reply());await returned('failed');await r.drain('xv');const repair=svc.reconcile('lead@xv','lead-g1','xv')[1];repo.claim({qitemId:repair.queueId!,destinationSession:'architect@xv'});repo.update({qitemId:repair.queueId!,actorSession:'architect@xv',state:'done',closureReason:'no-follow-on'});await repo.create({qitemId:'repair-result',sourceSession:'architect@xv',destinationSession:'lead@xv',body:JSON.stringify({packageKey:'repair',inputDigest:digest('repair'),evidence:[{kind:'report',ref:'repair.md'}],outcomeSummary:'Required repair unfinished'}),nudge:false});repo.coordinatorAuthority.dispose('architect@xv','architect-g1','xv','repair','repair-result');db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('op-bound','operator-agent@kernel','operator-agent@kernel','%1')").run();const sent:string[]=[];repo.attachTransport({send:async(session,text,opts)=>{if(session==='operator-agent@kernel'){expect(text).toContain(opts!.queueAssignmentId!);sent.push(opts!.queueAssignmentId!);repo.claim({qitemId:opts!.queueAssignmentId!,destinationSession:session,identityProvenance:'transport:v1'});}return {ok:true,verified:true};}});await r.drain('xv');expect(()=>svc.accept('lead@xv','lead-g1','xv','repair','repair-result','review.md')).toThrow('authorized recovery');const row=db.prepare("SELECT receipt FROM coordinator_operations WHERE operation_id='runtime-outcome-recovery:repair-result'").get() as {receipt:string};expect(JSON.parse(row.receipt).recoveryGap).toMatchObject({owner:'operator-agent@kernel',deadline:clock+60000});const notice=db.prepare("SELECT qitem_id,body FROM queue_items WHERE destination_session='operator-agent@kernel' AND body LIKE '%repair-result%'").get() as {qitem_id:string;body:string};expect(sent).toContain(notice.qitem_id);expect(repo.getById(notice.qitem_id)?.state).toBe('in-progress');await r.drain('xv');expect(sent.filter(q=>q===notice.qitem_id)).toHaveLength(1);expect(JSON.parse(notice.body).returnPath).toBe('current coordinator holder lead@xv');});
 it('successful independently accepted recovery restores holder acceptance without model grant',async()=>{configure(normal());let choice='yes';const f=vi.fn(async()=>await reply(choice)('http://fixture')) as unknown as typeof fetch;const r=outcome(f);await returned();await r.drain('xv');choice='no';const repair=svc.reconcile('lead@xv','lead-g1','xv')[1];repo.claim({qitemId:repair.queueId!,destinationSession:'architect@xv'});repo.update({qitemId:repair.queueId!,actorSession:'architect@xv',state:'done',closureReason:'no-follow-on'});await repo.create({qitemId:'repair-result',sourceSession:'architect@xv',destinationSession:'lead@xv',body:JSON.stringify({packageKey:'repair',inputDigest:digest('repair'),evidence:[{kind:'report',ref:'independent-review.md'}]}),nudge:false});repo.coordinatorAuthority.dispose('architect@xv','architect-g1','xv','repair','repair-result');await r.drain('xv');expect(()=>svc.accept('lead@xv','lead-g1','xv','product','result','review.md')).toThrow();svc.accept('lead@xv','lead-g1','xv','repair','repair-result','actual/independent-acceptance.md');svc.accept('lead@xv','lead-g1','xv','product','result','actual/parent-acceptance.md');expect(db.prepare("SELECT count(*) n FROM coordinator_operations WHERE kind='coordination-accept'").get()).toEqual({n:2});});

 it('missing-plan wake cannot notify a successor Operator from predecessor-generation policy',async()=>{configure(normal());const r=outcome(reply());await returned('failed');await r.drain('xv');const repair=svc.reconcile('lead@xv','lead-g1','xv')[1];repo.claim({qitemId:repair.queueId!,destinationSession:'architect@xv'});repo.update({qitemId:repair.queueId!,actorSession:'architect@xv',state:'done',closureReason:'no-follow-on'});await repo.create({qitemId:'repair-late-result',sourceSession:'architect@xv',destinationSession:'lead@xv',body:JSON.stringify({packageKey:'repair',inputDigest:digest('repair'),evidence:[{kind:'report',ref:'repair.md'}],outcomeSummary:'Required repair unfinished'}),nudge:false});repo.coordinatorAuthority.dispose('architect@xv','architect-g1','xv','repair','repair-late-result');await r.drain('xv');const notice=db.prepare("SELECT qitem_id FROM queue_items WHERE destination_session='operator-agent@kernel'").get() as {qitem_id:string};expect(notice).toBeTruthy();db.prepare("UPDATE occupant_tenures SET generation_uuid='operator-agent-g2' WHERE node_id='operator-agent@kernel'").run();db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('op-new','operator-agent@kernel','operator-agent@kernel','%1')").run();const sent=vi.fn(async()=>({ok:true,verified:true}));repo.attachTransport({send:sent});await repo.drainPendingWakeIntents();expect(sent).not.toHaveBeenCalled();expect(repo.getById(notice.qitem_id)?.state).toBe('pending');});

 it('durable audit retains normalized evidence and original binding without raw secrets',async()=>{configure(normal());const f=vi.fn(async()=>new Response(JSON.stringify({model:'qualified-fixture',secret:'NEVER_STORE_TOKEN',answers:{outcome:{type:'choice',choice:'yes',probabilities:{yes:.9,no:.05,unknown:.05},secret:'NEVER_STORE_TOKEN'}},usage:{input_tokens:150,output_tokens:2,cost:0,truncated:false,secret:'NEVER_STORE_TOKEN'}}))) as unknown as typeof fetch;const r=outcome(f);await returned();const pending=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-pending'").get() as {receipt:string}).receipt);await r.drain('xv');const raw=(db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-finished'").get() as {receipt:string}).receipt;const result=JSON.parse(raw);expect(raw).not.toContain('NEVER_STORE_TOKEN');expect(raw).not.toContain('finished later');expect(result.assessmentEvidence).toMatchObject({schema:'runtime-assessment-evidence.v1',outcome:{choice:'yes',probabilities:{yes:.9,no:.05,unknown:.05}},usage:{input_tokens:150,output_tokens:2,cost:0},applied:true,suppressed:false,grantsAuthority:false});expect(result.jobBinding).toMatchObject({worker:pending.worker,generation:pending.generation,configurationDigest:pending.configurationDigest,inputDigest:pending.inputDigest,createdAt:pending.createdAt});expect(result.assessmentEvidence.assessmentInputDigest).toMatch(/^[a-f0-9]{64}$/);expect(result.assessmentEvidence.rubricDigest).toMatch(/^[a-f0-9]{64}$/);});
 it('stale response preserves diagnostic evidence explicitly suppressed',async()=>{configure(normal());const f=vi.fn(async()=>{db.prepare("UPDATE occupant_tenures SET generation_uuid='builder-g2' WHERE node_id='builder@xv'").run();return reply()('http://fixture');}) as unknown as typeof fetch;const r=outcome(f);await returned();await r.drain('xv');const result=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-finished'").get() as {receipt:string}).receipt);expect(result).toMatchObject({reason:'state-changed',required:false,negativeAdvice:false,assessmentEvidence:{applied:false,suppressed:true,outcome:{choice:'yes'},grantsAuthority:false}});});
 it('unavailable audit retains job timing without fabricated model evidence',async()=>{configure(normal());const r=outcome(vi.fn(async()=>{throw new Error('PRIVATE_ERROR_TOKEN')}) as unknown as typeof fetch);await returned();await r.drain('xv');const raw=(db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-finished'").get() as {receipt:string}).receipt;const result=JSON.parse(raw);expect(raw).not.toContain('PRIVATE_ERROR_TOKEN');expect(result.jobBinding).toMatchObject({worker:'builder@xv',createdAt:clock,startedAt:clock});expect(result.assessmentEvidence.outcome).toBeNull();expect(result.assessmentEvidence.usage).toEqual({});expect(result.assessmentEvidence.applied).toBe(false);});
 it('audit allowlist rejects malformed numbers and oversized strings with bounded output',()=>{const result=sanitizedAssessmentEvidence({providerId:'x'.repeat(100000),model:{secret:'TOKEN'},rubricDigest:'TOKEN',answers:{outcome:{type:'choice',choice:'yes',probabilities:{yes:Infinity,no:0,unknown:0},topProbability:1,margin:1,secret:'TOKEN'}},usage:{input_tokens:-1,output_tokens:Infinity,cost:Infinity,secret:'TOKEN'},latencyMs:-1,raw:'TOKEN'},'a'.repeat(64));expect(result).toMatchObject({providerId:null,model:null,rubricDigest:null,outcome:null,usage:{},latencyMs:null,grantsAuthority:false});expect(JSON.stringify(result)).not.toContain('TOKEN');expect(JSON.stringify(result).length).toBeLessThan(4096);});

});
