import {RuntimeOutcomeAssessment,sanitizedAssessmentEvidence,type OutcomePolicy} from '../src/domain/runtime-outcome-assessment.js';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {resolve} from 'node:path';
import { describe,it,expect,beforeEach,afterEach,vi } from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import type Database from 'better-sqlite3';
import {createDb} from '../src/db/connection.js';import {EventBus} from '../src/domain/event-bus.js';
import {QueueRepository} from '../src/domain/queue-repository.js';import {OutboxHandler} from '../src/domain/outbox-handler.js';
import {CoordinationRecoveryService,coordinationIdle,type CoordinationActivity,type CoordinationTask,type CoordinationPlan} from '../src/domain/coordination-recovery-service.js';
import {SeatActivityService} from '../src/domain/seat-activity-service.js';
import {digest} from '../src/domain/coordinator-authority-service.js';import {seed,token} from './helpers/coordinator-fixture.js';
describe('runtime outcome enforcement',()=>{
 let dir:string,db:Database.Database,repo:QueueRepository,svc:CoordinationRecoveryService,clock:number,samples:Map<string,CoordinationActivity>;
 const task=(key:string,owner='builder@xv',more:Partial<CoordinationTask>={}):CoordinationTask=>({key,packageKey:key,owner,action:'Perform '+key+' and return bounded evidence',deadline:clock+20000,body:key,predecessors:[],admission:{generation:repo.coordinatorAuthority.generation(owner)!,configurationDigest:svc.configurationDigest(owner)!,qualificationRef:'approved/non-subject/'+key,capacityRef:'current/provider/'+key,effortRef:'current/effort/'+key,validUntil:clock+60000},...more});
 const plan=(tasks:CoordinationTask[]):CoordinationPlan=>({rigId:'xv',revision:'r1',operatorGeneration:'operator-agent-g1',stallMs:10000,allowIdlePeerTransfer:true,tasks});
 function sample(session:string):CoordinationActivity {const generation=repo.coordinatorAuthority.generation(session)!;return {generation,identityVerified:true,state:{seatNodeId:session,activity:'idle-at-prompt',needsInput:{count:0,reason:null},decidedBy:'window-sampling',seq:1,changedAt:new Date(clock).toISOString(),rungs:[],lastSwap:{generation,at:new Date(clock).toISOString()}},witness:{seatNodeId:session,sessionName:session,rung:'window-sampling',sourceId:'tmux',seq:1,observedAt:new Date(clock).toISOString(),activity:'idle-at-prompt'}};}
 function configure(tasks:CoordinationTask[],resources:Record<string,string[]>={}){for(const t of tasks)repo.coordinatorAuthority.admit('operator-agent@kernel','operator-agent-g1','xv',t.packageKey,{inputDigest:digest(t.key),destination:t.owner,bodyHash:digest(t.body),resources:resources[t.key]??[],returnContract:{destination:'lead@xv',evidenceRequired:['report']}});return svc.configure('operator-agent@kernel','operator-agent-g1',plan(tasks));}
 function refresh(){for(const s of ['lead@xv','peer@xv','builder@xv','reviewer@xv','architect@xv'])samples.set(s,sample(s));}
 function job(){db.prepare(`INSERT INTO watchdog_jobs(job_id,target_session,policy,interval_seconds,spec_yaml,state,registered_by_session,registered_at,registered_by_generation_uuid) VALUES ('j','operator-agent@kernel','coordinator-continuity',1,'context: {}','active','operator-agent@kernel',?,'operator-agent-g1')`).run(new Date(clock).toISOString());}
 beforeEach(async()=>{vi.useFakeTimers({toFake:['Date']});clock=Date.now();dir=mkdtempSync(join(tmpdir(),'coordination-'));db=createDb(join(dir,'db'));seed(db);db.prepare("INSERT INTO self_host_identity VALUES(1,'fixture-host',?,?)").run(new Date(clock).toISOString(),new Date(clock).toISOString());const bus=new EventBus(db);repo=new QueueRepository(db,bus,{resolveOccupantGeneration:s=>repo.coordinatorAuthority.generation(s)});repo.attachOutbox(new OutboxHandler(db));await repo.create({qitemId:'baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@xv',body:'coordinate',nudge:false});repo.coordinatorAuthority.enable('operator-agent@kernel','operator-agent-g1',{rigId:'xv',batonId:'baton',owner:'lead@xv',ownerGeneration:'lead-g1',coordinators:['lead@xv','peer@xv'],leaseMs:60000,operationId:'enable'});repo.coordinatorAuthority.acknowledge('lead@xv',token,{operationId:'ack',obligationsDigest:repo.coordinatorAuthority.reconciliationDigest('xv')});samples=new Map();refresh();svc=new CoordinationRecoveryService(repo,s=>samples.get(s)??null,()=>clock);repo.coordinatorAuthority.coordinationRecovery=svc;});
 afterEach(()=>{db.close();rmSync(dir,{recursive:true,force:true});vi.useRealTimers();});

 const cfg=()=>({schemaVersion:1,mode:'observe',enabled:true,primary:'local',providers:{local:{adapter:'laya',endpoint:'http://127.0.0.1:18091/v1/systemone',model:'typed-decisions',acceptedModels:['qualified-fixture'],timeoutMs:100,allowedData:['private'],maxResponseBytes:16384,capabilities:{schema:'systemone.v1',primitives:['choice'],maxStateChars:10000,maxQuestions:10,maxOptions:10,inputCoverage:'reported'},threshold:{minTopProbability:0.8,calibrationId:'synthetic-test'}}}});
 function outcome(fetch:typeof globalThis.fetch,mode:'observe'|'enforce'='enforce',negative=false){const c=cfg();const r=new RuntimeOutcomeAssessment(repo,{fetchImpl:fetch},()=>clock);repo.coordinatorAuthority.runtimeOutcomeAssessment=r;const p:OutcomePolicy={rigId:'xv',revision:'p1',mode,operatorGeneration:'operator-agent-g1',dataClass:'private',allowPaid:false,allowUnqualifiedNegativeAdvice:negative,adapterConfig:c,qualification:{ref:'synthetic-test-only',providerConfigDigest:digest(JSON.stringify(c)),validUntil:clock+60000}};r.configure('operator-agent@kernel','operator-agent-g1',p);return r;}
 const reply=(choice='yes',coverage=true)=>vi.fn(async()=>new Response(JSON.stringify({model:'qualified-fixture',answers:{outcome:{type:'choice',choice,probabilities:{yes:choice==='yes'?.9:.05,no:choice==='no'?.9:.05,unknown:choice==='unknown'?.9:.05}}},usage:coverage?{input_tokens:150,output_tokens:0,truncated:false}:{input_tokens:150,output_tokens:0}}),{status:200})) as unknown as typeof fetch;
 async function returned(state:'done'|'failed'='done'){const q=svc.reconcile('lead@xv','lead-g1','xv')[0].queueId!;repo.claim({qitemId:q,destinationSession:'builder@xv',identityProvenance:'transport:v1'});repo.update({qitemId:q,actorSession:'builder@xv',state,closureReason:state==='done'?'no-follow-on':undefined});await repo.create({qitemId:'result',sourceSession:'builder@xv',destinationSession:'lead@xv',body:JSON.stringify({packageKey:'product',inputDigest:digest('product'),evidence:[{kind:'report',ref:'report.md'}],outcomeSummary:'Required implementation will be finished later'}),nudge:false});repo.coordinatorAuthority.dispose('builder@xv','builder-g1','xv','product','result');return q;}
 const normal=()=>[task('product'),task('repair','architect@xv',{recoveryFor:'product'})];
 it('real common return produces qualified negative recovery and actual admitted pickup',async()=>{configure(normal());const f=reply(),r=outcome(f);await returned();expect(()=>svc.accept('lead@xv','lead-g1','xv','product','result','accept.md')).toThrow('not yet resolved');await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(true);const repair=svc.reconcile('lead@xv','lead-g1','xv').find(x=>x.key==='repair')!;expect(repair.state).toBe('pending-pickup');repo.claim({qitemId:repair.queueId!,destinationSession:'architect@xv',identityProvenance:'transport:v1'});expect(svc.reconcile('lead@xv','lead-g1','xv').find(x=>x.key==='repair')?.state).toBe('picked-up');expect(()=>svc.accept('lead@xv','lead-g1','xv','product','result','accept.md')).toThrow('authorized recovery');expect(JSON.stringify(vi.mocked(f).mock.calls)).toContain('finished later');await r.drain('xv');expect(vi.mocked(f)).toHaveBeenCalledTimes(1);});
 it('provider unavailable leaves successful factual acceptance rules and independent frontier usable',async()=>{configure([...normal(),task('independent','reviewer@xv'),task('independent-repair','architect@xv',{recoveryFor:'independent'})]);const r=outcome(vi.fn(async()=>{throw new Error('offline')}) as unknown as typeof fetch);await returned();await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(false);svc.accept('lead@xv','lead-g1','xv','product','result','actual/technical-review.md');expect(svc.reconcile('lead@xv','lead-g1','xv').find(x=>x.key==='independent')?.state).toBe('pending-pickup');});
 it('failed actual state creates recovery even when model unavailable',async()=>{configure(normal());const r=outcome(vi.fn(async()=>{throw new Error('offline')}) as unknown as typeof fetch);await returned('failed');await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(true);const repair=svc.reconcile('lead@xv','lead-g1','xv')[1];repo.claim({qitemId:repair.queueId!,destinationSession:'architect@xv'});expect(repo.getById(repair.queueId!)?.state).toBe('in-progress');});
 it('expired policy commits one generation-bound Operator recovery, without extending policy or calling provider',async()=>{
  configure(normal());const f=reply(),r=outcome(f);const policy=r.policy('xv')!;expect(r.stagePolicyBoundary('xv')).toBeNull();clock=policy.qualification.validUntil+1;vi.setSystemTime(clock);
  const id=r.stagePolicyBoundary('xv')!;expect(r.stagePolicyBoundary('xv')).toBe(id);const q=repo.getById(id)!;expect(q.destinationSession).toBe('operator-agent@kernel');expect(JSON.parse(q.body)).toMatchObject({action:'requalify-expired-outcome-policy',recipientGeneration:'operator-agent-g1',policyRevision:policy.revision,grantsAuthority:false});expect(r.policy('xv')).toEqual(policy);expect(vi.mocked(f)).not.toHaveBeenCalled();
  const wakes=db.prepare('SELECT * FROM outbox_entries WHERE audit_pointer=?').all(id) as any[];expect(wakes).toHaveLength(1);expect(wakes[0].delivery_state).toBe('pending');expect(JSON.parse(wakes[0].tags)).toContain('queue:recipient-generation:operator-agent-g1');
  repo.attachTransport({send:async()=>({ok:true,verified:true})});await svc.deliverCommitted();repo.claim({qitemId:id,destinationSession:'operator-agent@kernel'});expect(db.prepare('SELECT claimed_by_generation_uuid FROM queue_items WHERE qitem_id=?').get(id)).toEqual({claimed_by_generation_uuid:'operator-agent-g1'});
  db.prepare("UPDATE occupant_tenures SET generation_uuid='operator-agent-g2' WHERE node_id='operator-agent@kernel'").run();expect(r.stagePolicyBoundary('xv')).toBeNull();
 });
 it('observation and absent policy never add authority or semantic holds',async()=>{configure(normal());const r=outcome(reply(),'observe');await returned();await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(false);svc.accept('lead@xv','lead-g1','xv','product','result','actual/review.md');expect(db.prepare("SELECT count(*) n FROM coordinator_operations WHERE kind='coordination-accept'").get()).toEqual({n:1});});
 it('unknown coverage negative advice remains expressly unqualified and only opt-in',async()=>{configure(normal());const r=outcome(reply('yes',false),'enforce',true);await returned();await r.drain('xv');const row=db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-finished'").get() as {receipt:string};expect(JSON.parse(row.receipt)).toMatchObject({status:'abstained',negativeAdvice:true,required:true,grantsAuthority:false});expect(JSON.parse(row.receipt).provenance.inputCoverage).not.toBe('reported_complete');});
 it('generation drift while provider pending cannot apply old advice',async()=>{configure(normal());const f=vi.fn(async()=>{db.prepare("UPDATE occupant_tenures SET generation_uuid='builder-g2' WHERE node_id='builder@xv'").run();return new Response(JSON.stringify({model:'qualified-fixture',answers:{outcome:{type:'choice',choice:'yes',probabilities:{yes:.9,no:.05,unknown:.05}}},usage:{input_tokens:150,output_tokens:0,truncated:false}}),{status:200});}) as unknown as typeof fetch;const r=outcome(f);await returned();await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(false);const row=db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-finished'").get() as {receipt:string};expect(JSON.parse(row.receipt)).toMatchObject({reason:'state-changed',classification:'unknown',grantsAuthority:false});});
 it('two rigs and Codex/Pi identities process independently through common disposition',async()=>{
  configure(normal());const f=reply(),r=outcome(f);
  for(const name of ['lead','peer','repair']){const id=name+'@other';db.prepare('INSERT INTO nodes(id,rig_id,logical_id,runtime) VALUES (?,?,?,?)').run(id,'other',name,'pi');db.prepare('INSERT INTO sessions(id,node_id,session_name) VALUES (?,?,?)').run(id,id,id);db.prepare("INSERT INTO occupant_tenures(id,node_id,generation_ordinal,generation_uuid,kind) VALUES(?,?,1,?,'fresh')").run(id,id,name+'-other-g1');}
  db.prepare("UPDATE nodes SET runtime='pi' WHERE id='worker@other'").run();
  await repo.create({qitemId:'other-baton',sourceSession:'operator-agent@kernel',destinationSession:'lead@other',body:'coordinate',nudge:false});repo.coordinatorAuthority.enable('operator-agent@kernel','operator-agent-g1',{rigId:'other',batonId:'other-baton',owner:'lead@other',ownerGeneration:'lead-other-g1',coordinators:['lead@other','peer@other'],leaseMs:60000,operationId:'other-enable'});repo.coordinatorAuthority.acknowledge('lead@other',{rigId:'other',epoch:1,generation:'lead-other-g1'},{operationId:'other-ack',obligationsDigest:repo.coordinatorAuthority.reconciliationDigest('other')});
  const tasks=[task('other-product','worker@other'),task('other-repair','repair@other',{recoveryFor:'other-product'})];
  for(const t of tasks){repo.coordinatorAuthority.admit('operator-agent@kernel','operator-agent-g1','other',t.packageKey,{inputDigest:digest(t.key),destination:t.owner,bodyHash:digest(t.body),resources:[],returnContract:{destination:'lead@other',evidenceRequired:['report']}});samples.set(t.owner,sample(t.owner));}
  svc.configure('operator-agent@kernel','operator-agent-g1',{...plan(tasks),rigId:'other'});const p=r.policy('xv')!;r.configure('operator-agent@kernel','operator-agent-g1',{...p,rigId:'other'});
  await returned();const q=svc.reconcile('lead@other','lead-other-g1','other')[0].queueId!;repo.claim({qitemId:q,destinationSession:'worker@other'});repo.update({qitemId:q,actorSession:'worker@other',state:'done',closureReason:'no-follow-on'});await repo.create({qitemId:'other-result',sourceSession:'worker@other',destinationSession:'lead@other',body:JSON.stringify({packageKey:'other-product',inputDigest:digest('other-product'),evidence:[{kind:'report',ref:'other/report.md'}],outcomeSummary:'Assigned required work remains unfinished'}),nudge:false});repo.coordinatorAuthority.dispose('worker@other','worker-g1','other','other-product','other-result');
  await Promise.all([r.drain('xv'),r.drain('other')]);expect(vi.mocked(f)).toHaveBeenCalledTimes(2);expect(r.requiresRecovery('xv','product')).toBe(true);expect(r.requiresRecovery('other','other-product')).toBe(true);const repair=svc.reconcile('lead@other','lead-other-g1','other')[1];repo.claim({qitemId:repair.queueId!,destinationSession:'repair@other'});expect(repo.getById(repair.queueId!)?.state).toBe('in-progress');
 });

 it('invalid, model mismatch, nonfinite and truncated advice cannot create semantic enforcement',async()=>{for(const raw of [{model:'wrong',answers:{}},{model:'qualified-fixture',answers:{outcome:{type:'choice',choice:'yes',probabilities:{yes:2,no:0,unknown:0}}}},{model:'qualified-fixture',answers:{outcome:{type:'choice',choice:'yes',probabilities:{yes:.9,no:.05,unknown:.05}}},usage:{truncated:true,input_tokens:10,output_tokens:0}}]){configure(normal());const r=outcome(vi.fn(async()=>new Response(JSON.stringify(raw))) as unknown as typeof fetch,'enforce',true);await returned();await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(false);db.prepare("DELETE FROM coordinator_operations WHERE kind LIKE 'runtime-outcome%'").run();db.prepare("DELETE FROM coordinator_operations WHERE kind NOT IN ('coordination-plan','enable','acknowledge')").run();db.prepare('DELETE FROM outbox_entries').run();db.prepare('DELETE FROM coordinator_assignments').run();db.prepare("DELETE FROM queue_items WHERE qitem_id!='baton'").run();}});
 it('same-rig simultaneous drains yield one request and one recovery intent',async()=>{configure(normal());const f=reply(),r=outcome(f);await returned();await Promise.all([r.drain('xv'),r.drain('xv')]);expect(vi.mocked(f)).toHaveBeenCalledTimes(1);expect(db.prepare("SELECT count(*) n FROM coordinator_assignments WHERE package_key='repair'").get()).toEqual({n:1});});
 it('policy revision cannot erase pending or unresolved negative obligation',async()=>{configure(normal());const r=outcome(reply());await returned();const p=r.policy('xv')!;expect(()=>r.configure('operator-agent@kernel','operator-agent-g1',{...p,revision:'p2',mode:'observe'})).toThrow('not yet resolved');await r.drain('xv');expect(()=>r.configure('operator-agent@kernel','operator-agent-g1',{...p,revision:'p2',mode:'observe'})).toThrow('authorized recovery');});
 it('negative advice is disabled by default for unknown coverage',async()=>{configure(normal());const r=outcome(reply('yes',false));await returned();await r.drain('xv');expect(r.requiresRecovery('xv','product')).toBe(false);});
 it('strict flags and paid/private remote opt-ins fail before provider or credentials',()=>{configure(normal());const r=outcome(reply()),p=r.policy('xv')!;expect(()=>r.configure('operator-agent@kernel','operator-agent-g1',{...p,revision:'bad',allowUnqualifiedNegativeAdvice:'false' as unknown as boolean})).toThrow('strict opt-ins');const c=cfg();c.providers.local.endpoint='https://api.typesafe.ai/v1/systemone';expect(()=>r.configure('operator-agent@kernel','operator-agent-g1',{...p,revision:'remote',adapterConfig:c,qualification:{...p.qualification,providerConfigDigest:digest(JSON.stringify(c))}})).toThrow();});
 it('terminal return from retired generation is refused by actual common boundary',async()=>{configure(normal());const r=outcome(reply());const q=svc.reconcile('lead@xv','lead-g1','xv')[0].queueId!;repo.claim({qitemId:q,destinationSession:'builder@xv'});repo.update({qitemId:q,actorSession:'builder@xv',state:'done',closureReason:'no-follow-on'});expect(()=>repo.coordinatorAuthority.dispose('builder@xv','retired','xv','product','none')).toThrow();expect(db.prepare("SELECT 1 FROM coordinator_operations WHERE kind='runtime-outcome-pending'").get()).toBeUndefined();});

 it('missing recovery for incomplete leaf is accountable gap and cannot imply completion',async()=>{configure(normal());const r=outcome(reply());await returned('failed');await r.drain('xv');const repair=svc.reconcile('lead@xv','lead-g1','xv')[1];repo.claim({qitemId:repair.queueId!,destinationSession:'architect@xv'});repo.update({qitemId:repair.queueId!,actorSession:'architect@xv',state:'done',closureReason:'no-follow-on'});await repo.create({qitemId:'repair-result',sourceSession:'architect@xv',destinationSession:'lead@xv',body:JSON.stringify({packageKey:'repair',inputDigest:digest('repair'),evidence:[{kind:'report',ref:'repair.md'}],outcomeSummary:'Required repair unfinished'}),nudge:false});repo.coordinatorAuthority.dispose('architect@xv','architect-g1','xv','repair','repair-result');db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('op-bound','operator-agent@kernel','operator-agent@kernel','%1')").run();const sent:string[]=[];repo.attachTransport({send:async(session,text,opts)=>{if(session==='operator-agent@kernel'){expect(text).toContain(opts!.queueAssignmentId!);sent.push(opts!.queueAssignmentId!);repo.claim({qitemId:opts!.queueAssignmentId!,destinationSession:session,identityProvenance:'transport:v1'});}return {ok:true,verified:true};}});await r.drain('xv');expect(()=>svc.accept('lead@xv','lead-g1','xv','repair','repair-result','review.md')).toThrow('authorized recovery');const row=db.prepare("SELECT receipt FROM coordinator_operations WHERE operation_id='runtime-outcome-recovery:repair-result'").get() as {receipt:string};expect(JSON.parse(row.receipt).recoveryGap).toMatchObject({owner:'operator-agent@kernel',deadline:clock+60000});const notice=db.prepare("SELECT qitem_id,body FROM queue_items WHERE destination_session='operator-agent@kernel' AND body LIKE '%repair-result%'").get() as {qitem_id:string;body:string};expect(sent).toContain(notice.qitem_id);expect(repo.getById(notice.qitem_id)?.state).toBe('in-progress');await r.drain('xv');expect(sent.filter(q=>q===notice.qitem_id)).toHaveLength(1);expect(JSON.parse(notice.body).returnPath).toBe('current coordinator holder lead@xv');});
 it('successful independently accepted recovery restores holder acceptance without model grant',async()=>{configure(normal());let choice='yes';const f=vi.fn(async()=>await reply(choice)('http://fixture')) as unknown as typeof fetch;const r=outcome(f);await returned();await r.drain('xv');choice='no';const repair=svc.reconcile('lead@xv','lead-g1','xv')[1];repo.claim({qitemId:repair.queueId!,destinationSession:'architect@xv'});repo.update({qitemId:repair.queueId!,actorSession:'architect@xv',state:'done',closureReason:'no-follow-on'});await repo.create({qitemId:'repair-result',sourceSession:'architect@xv',destinationSession:'lead@xv',body:JSON.stringify({packageKey:'repair',inputDigest:digest('repair'),evidence:[{kind:'report',ref:'independent-review.md'}]}),nudge:false});repo.coordinatorAuthority.dispose('architect@xv','architect-g1','xv','repair','repair-result');await r.drain('xv');expect(()=>svc.accept('lead@xv','lead-g1','xv','product','result','review.md')).toThrow();svc.accept('lead@xv','lead-g1','xv','repair','repair-result','actual/independent-acceptance.md');svc.accept('lead@xv','lead-g1','xv','product','result','actual/parent-acceptance.md');expect(db.prepare("SELECT count(*) n FROM coordinator_operations WHERE kind='coordination-accept'").get()).toEqual({n:2});});

 it('missing-plan wake cannot notify a successor Operator from predecessor-generation policy',async()=>{configure(normal());const r=outcome(reply());await returned('failed');await r.drain('xv');const repair=svc.reconcile('lead@xv','lead-g1','xv')[1];repo.claim({qitemId:repair.queueId!,destinationSession:'architect@xv'});repo.update({qitemId:repair.queueId!,actorSession:'architect@xv',state:'done',closureReason:'no-follow-on'});await repo.create({qitemId:'repair-late-result',sourceSession:'architect@xv',destinationSession:'lead@xv',body:JSON.stringify({packageKey:'repair',inputDigest:digest('repair'),evidence:[{kind:'report',ref:'repair.md'}],outcomeSummary:'Required repair unfinished'}),nudge:false});repo.coordinatorAuthority.dispose('architect@xv','architect-g1','xv','repair','repair-late-result');await r.drain('xv');const notice=db.prepare("SELECT qitem_id FROM queue_items WHERE destination_session='operator-agent@kernel'").get() as {qitem_id:string};expect(notice).toBeTruthy();db.prepare("UPDATE occupant_tenures SET generation_uuid='operator-agent-g2' WHERE node_id='operator-agent@kernel'").run();db.prepare("INSERT INTO bindings(id,node_id,tmux_session,tmux_pane) VALUES ('op-new','operator-agent@kernel','operator-agent@kernel','%1')").run();const sent=vi.fn(async()=>({ok:true,verified:true}));repo.attachTransport({send:sent});await repo.drainPendingWakeIntents();expect(sent).not.toHaveBeenCalled();expect(repo.getById(notice.qitem_id)?.state).toBe('pending');});

 it('durable audit retains normalized evidence and original binding without raw secrets',async()=>{configure(normal());const f=vi.fn(async()=>new Response(JSON.stringify({model:'qualified-fixture',secret:'NEVER_STORE_TOKEN',answers:{outcome:{type:'choice',choice:'yes',probabilities:{yes:.9,no:.05,unknown:.05},secret:'NEVER_STORE_TOKEN'}},usage:{input_tokens:150,output_tokens:2,cost:0,truncated:false,secret:'NEVER_STORE_TOKEN'}}))) as unknown as typeof fetch;const r=outcome(f);await returned();const pending=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-pending'").get() as {receipt:string}).receipt);await r.drain('xv');const raw=(db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-finished'").get() as {receipt:string}).receipt;const result=JSON.parse(raw);expect(raw).not.toContain('NEVER_STORE_TOKEN');expect(raw).not.toContain('finished later');expect(result.assessmentEvidence).toMatchObject({schema:'runtime-assessment-evidence.v1',outcome:{choice:'yes',probabilities:{yes:.9,no:.05,unknown:.05}},usage:{input_tokens:150,output_tokens:2,cost:0},applied:true,suppressed:false,grantsAuthority:false});expect(result.jobBinding).toMatchObject({worker:pending.worker,generation:pending.generation,configurationDigest:pending.configurationDigest,inputDigest:pending.inputDigest,createdAt:pending.createdAt});expect(result.assessmentEvidence.assessmentInputDigest).toMatch(/^[a-f0-9]{64}$/);expect(result.assessmentEvidence.rubricDigest).toMatch(/^[a-f0-9]{64}$/);});
 it('stale response preserves diagnostic evidence explicitly suppressed',async()=>{configure(normal());const f=vi.fn(async()=>{db.prepare("UPDATE occupant_tenures SET generation_uuid='builder-g2' WHERE node_id='builder@xv'").run();return reply()('http://fixture');}) as unknown as typeof fetch;const r=outcome(f);await returned();await r.drain('xv');const result=JSON.parse((db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-finished'").get() as {receipt:string}).receipt);expect(result).toMatchObject({reason:'state-changed',required:false,negativeAdvice:false,assessmentEvidence:{applied:false,suppressed:true,outcome:{choice:'yes'},grantsAuthority:false}});});
 it('unavailable audit retains job timing without fabricated model evidence',async()=>{configure(normal());const r=outcome(vi.fn(async()=>{throw new Error('PRIVATE_ERROR_TOKEN')}) as unknown as typeof fetch);await returned();await r.drain('xv');const raw=(db.prepare("SELECT receipt FROM coordinator_operations WHERE kind='runtime-outcome-finished'").get() as {receipt:string}).receipt;const result=JSON.parse(raw);expect(raw).not.toContain('PRIVATE_ERROR_TOKEN');expect(result.jobBinding).toMatchObject({worker:'builder@xv',createdAt:clock,startedAt:clock});expect(result.assessmentEvidence.outcome).toBeNull();expect(result.assessmentEvidence.usage).toEqual({});expect(result.assessmentEvidence.applied).toBe(false);});
 it('audit allowlist rejects malformed numbers and oversized strings with bounded output',()=>{const result=sanitizedAssessmentEvidence({providerId:'x'.repeat(100000),model:{secret:'TOKEN'},rubricDigest:'TOKEN',answers:{outcome:{type:'choice',choice:'yes',probabilities:{yes:Infinity,no:0,unknown:0},topProbability:1,margin:1,secret:'TOKEN'}},usage:{input_tokens:-1,output_tokens:Infinity,cost:Infinity,secret:'TOKEN'},latencyMs:-1,raw:'TOKEN'},'a'.repeat(64));expect(result).toMatchObject({providerId:null,model:null,rubricDigest:null,outcome:null,usage:{},latencyMs:null,grantsAuthority:false});expect(JSON.stringify(result)).not.toContain('TOKEN');expect(JSON.stringify(result).length).toBeLessThan(4096);});

});
