import type Database from 'better-sqlite3';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { accessSync,constants,readFileSync,lstatSync,realpathSync } from 'node:fs';
import type { TmuxAdapter } from '../adapters/tmux.js';
import type { PiResumeAdapter } from '../adapters/pi-resume.js';
import { buildPiRunnerArgs,piSeatPaths, type PiRunnerState } from '../adapters/pi-runner-protocol.js';
import type { PiNativeProof } from './coordinator-runtime-availability.js';
import { PiDetachedResume,type PiDetachedBinding } from './pi-detached-resume.js';
import type { SeatDeliveryGuard } from './seat-delivery-guard.js';
import { NativeDutyLaunchStore,observeNativeDutyLaunch,verifyNativeDutyProcessIdentity } from './native-duty-launch.js';
import { SeatLaunchEnvironment,structuredNativeExecutable } from './seat-launch-environment.js';
import { listNativeProcesses, type NativeProcessRow } from './native-process-lineage.js';
import { observeSolePane } from './pane-binding-observation.js';
import { provePiIdentityAbsent } from './codex-rehost-integration.js';
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
export function validatePiDetachedHistory(binding:PiDetachedBinding,bytes:Buffer):{nativeIdentity:string;lastEntryId:string}{
 const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(!text.endsWith('\n'))throw new Error('Incomplete Pi history');
 const rows=text.slice(0,-1).split('\n').map(line=>JSON.parse(line));const header=rows.shift();if(header?.type!=='session'||typeof header.id!=='string'||!header.id||header.cwd!==binding.cwd)throw new Error('Pi session header mismatch');
 const ids=new Set<string>();let last:string|null=null;
 for(const row of rows){if(typeof row.id!=='string'||!row.id||ids.has(row.id)||!('parentId' in row)||row.parentId!==null&&!ids.has(row.parentId))throw new Error('Pi entry chain invalid');ids.add(row.id);last=row.id;}
 if(!last)throw new Error('Pi session cursor missing');return {nativeIdentity:header.id,lastEntryId:last};
}
export function piSupervisorCandidates(rows:NativeProcessRow[],panePid:number):NativeProcessRow[]{
 const descendants=new Set([panePid]);for(let i=0;i<rows.length;i++){let changed=false;for(const row of rows)if(descendants.has(row.ppid)&&!descendants.has(row.pid)){descendants.add(row.pid);changed=true;}if(!changed)break;}
 return rows.filter(row=>row.pid!==panePid&&descendants.has(row.pid)&&row.executableName==='node');
}
export function createPiDetachedResumeIntegration(deps:{db:Database.Database;guard:SeatDeliveryGuard;tmux:TmuxAdapter;resume:PiResumeAdapter;store?:NativeDutyLaunchStore;launchEnvironment:SeatLaunchEnvironment;launchPath:string;stateRoot:string;runnerEntryPath:string;piProve:(session:string)=>Promise<PiNativeProof|null>;piRunnerState:(session:string)=>PiRunnerState|null;configurationDigest:(session:string)=>string|null|undefined;resolvePosture:(binding:PiDetachedBinding)=>'floor'|'full_bypass';sessionEnv?:Record<string,string|undefined>;runtimeSessionEnv?:Record<string,Record<string,string|undefined>>;snapshotRoot:string}){
 const managed=async(nodeId:string)=>{const target=deps.guard.maybeTarget(nodeId);if(!target?.pane||!target.occupant||!deps.guard.ownsRunnerRehost(nodeId))return null;const row=deps.db.prepare("SELECT runtime,resume_token FROM nodes n JOIN sessions s ON s.node_id=n.id WHERE n.id=? ORDER BY s.id DESC LIMIT 1").get(nodeId) as any;const configurationDigest=deps.configurationDigest(target.session);if(row?.runtime!=='pi'||!row.resume_token||!configurationDigest)return null;return {nodeId,sessionName:target.session,generation:target.occupant,runtime:'pi' as const,configurationDigest,pane:target.pane,resumeToken:row.resume_token,lifecycleReserved:false};};
 const preflight=async(b:PiDetachedBinding,detached:boolean,originalRunnerEntryPath?:string)=>{if(!deps.store||!deps.guard.ownsRunnerRehost(b.nodeId)||!await deps.launchEnvironment.usesNativeDuty(b.sessionName,b.nodeId))throw new Error('Pi managed supervision unavailable');deps.store.assertReady();const target=deps.guard.target(b.nodeId);if(target.session!==b.sessionName||target.occupant!==b.generation||!detached&&!target.pane)throw new Error('Pi binding changed');const digest=deps.configurationDigest(b.sessionName);if(!digest)throw new Error('Pi configuration unavailable');const posture=deps.resolvePosture(b);if(posture!=='floor'&&posture!=='full_bypass')throw new Error('Pi launch policy unavailable');accessSync(deps.runnerEntryPath,constants.R_OK);if(originalRunnerEntryPath!==undefined){
  for(const file of [originalRunnerEntryPath,deps.runnerEntryPath]){if(!path.isAbsolute(file)||path.normalize(file)!==file||/[\0\r\n]/.test(file)||realpathSync(file)!==file||!lstatSync(file).isFile()||lstatSync(file).isSymbolicLink())throw new Error('Canonical regular runner provenance required');}
  if(!readFileSync(originalRunnerEntryPath).equals(readFileSync(deps.runnerEntryPath)))throw new Error('Runner contents changed across releases');
 }const harness=structuredNativeExecutable('node',[],deps.launchPath,b.cwd);const paths=piSeatPaths(deps.stateRoot,b.sessionName);const args=buildPiRunnerArgs({runtime:'pi',runnerEntryPath:originalRunnerEntryPath??deps.runnerEntryPath,sessionName:b.sessionName,stateRoot:deps.stateRoot,cwd:b.cwd,model:b.model,trust:posture==='full_bypass'?'approve':'no-approve',sessionFile:b.nativeId,launchId:'preflight'});const configuration=['settings.json','models.json'].map(file=>{try{return {file,hash:hash(readFileSync(paths.agentDir+'/'+file))};}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return {file,absent:true};throw error;}});return {posture,digest:hash({configurationDigest:digest,posture,harness,args,configuration,runner:hash(readFileSync(deps.runnerEntryPath))})};};
 return new PiDetachedResume({db:deps.db,guard:deps.guard,tmux:deps.tmux,snapshotRoot:deps.snapshotRoot,validateHistory:validatePiDetachedHistory,
 runnerEntryPath:deps.runnerEntryPath,preflight:(b,detached)=>preflight(b,detached),preflightAtOriginalRunner:preflight,
 terminalAbsent:async b=>{const p=await deps.tmux.probeSession(b.sessionName);return p.state==='absent'||p.state==='transport_unavailable';},proveNativeAbsent:provePiIdentityAbsent,
 createTerminal:async b=>{const env:Record<string,string>={};for(const source of [deps.sessionEnv,deps.runtimeSessionEnv?.pi])for(const [k,v] of Object.entries(source??{}))if(v!==undefined)env[k]=v;Object.assign(env,{OPENRIG_NODE_ID:b.nodeId,OPENRIG_SESSION_NAME:b.sessionName,OPENRIG_OCCUPANT_GENERATION:b.generation,OPENRIG_RUNTIME:'pi'});const created=await deps.tmux.createSessionForRunnerResume(b.sessionName,b.cwd,env);if(!created.ok)throw new Error('Pi terminal creation refused');const pane=await observeSolePane(deps.tmux,b.sessionName);if(!pane.ok)throw new Error('Pi terminal is not sole pane');return {pane:pane.pane};},
 resume:(b,p)=>deps.resume.resume(b.sessionName,'pi_session_file',b.nativeId,b.cwd,b.model,p.posture,b.generation),
 observeReplacement:async b=>{if(!deps.store)return null;const current=await managed(b.nodeId),latest=deps.store.latest(b.nodeId,b.generation),state=deps.piRunnerState(b.sessionName);if(!current||!latest||current.resumeToken!==b.nativeId||latest.intent.configurationDigest!==current.configurationDigest||!state?.ready||state.exited||state.sessionFile!==b.nativeId)return null;const rows=await listNativeProcesses(),identity={OPENRIG_NODE_ID:b.nodeId,OPENRIG_SESSION_NAME:b.sessionName,OPENRIG_OCCUPANT_GENERATION:b.generation,OPENRIG_RUNTIME:'pi'};const panePid=await deps.tmux.getPanePid(current.pane);if(!panePid)return null;const supervisors:number[]=[];for(const row of piSupervisorCandidates(rows,panePid))if(await verifyNativeDutyProcessIdentity(row.pid,identity,[latest.intent.installedNode.path,latest.intent.installedSupervisor.path,'--supervise',latest.intent.configPath]))supervisors.push(row.pid);if(supervisors.length!==1)return null;const proof=await observeNativeDutyLaunch(deps.store,{scope:latest.intent,launchId:latest.intent.launchId,supervisorPid:supervisors[0]!},{currentBinding:managed,tmux:deps.tmux,piProve:deps.piProve});const native=await deps.piProve(b.sessionName);if(!proof||native?.state!=='present'||native.generation!==b.generation||native.launchId!==state.launchId)return null;const history=validatePiDetachedHistory(b,readFileSync(b.nativeId));if(state.lastEntryId!==history.lastEntryId||native.lastEntryId!==history.lastEntryId)return null;return {supervisorLaunchId:proof.launchId,nativeFingerprint:native.fingerprint,nativeIdentity:history.nativeIdentity,sessionFile:b.nativeId,generation:b.generation};}
 });
}
